### ISSUE TITLE
Error validating input parameters

### ISSUE THREAD

**Issue by brookeaddams** [MicrosoftDocs/powerapps-docs#519] opened 2019-07-16 20:33 UTC
I have done exactly what was asked for in this post. I used the POST method and (URI)/api/data/v9.0/WinOpportunity
 with request content {"Status":3,"OpportunityClose":{"subject":"Won Opportunity","opportunityid@odata.bind":"(URI)/api/data/v9.0/opportunities(OpportunityID)"}} . I received an error that an error occured while validating input parameters, that the absoluteuri should contain servicerouteuri.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 270e7eda-738e-f16b-febf-c6e752dd3d5d
* Version Independent ID: 98638d74-04c7-cc4c-a89f-0945ae1cc7fa
* Content: [Use Web API actions (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/use-web-api-actions?view=dynamics-ce-odata-9#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/use-web-api-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/use-web-api-actions.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-07-02 00:08
@brookeaddams Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:08 UTC
Labels: open-for-too-long
