### ISSUE TITLE
Returns content window before it's been properly parsed

### ISSUE THREAD

**Issue by paulhasell** [MicrosoftDocs/powerapps-docs#1654] opened 2020-08-11 10:30 UTC
We're using this to initialise our web resources in a model driven app but get random failures telling as the method is not defined. This implies the getContentWindow is returning before the browser has fully parsed the page and javascript. As this now seems to be the preferred/recommended way to initialise it needs to work 100% of the time.

[Microsoft Edge (Chromium)]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4c796e-ad9f-1929-f530-f088462522f9
* Version Independent ID: 40e67735-ac26-30a4-3191-0a86fd7b4b50
* Content: [getContentWindow (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/getcontentwindow)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment] 2020-11-11 18:52
@paulhasell Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 18:52 UTC
Labels: assigned-to-author, client-api
