### ISSUE TITLE
CRM Team Blog: Thread Safety in Plug-ins link - 404 page not found

### ISSUE THREAD

**Issue by jhewetson** [MicrosoftDocs/powerapps-docs#1296] opened 2020-04-23 02:57 UTC
https://blogs.msdn.com/b/crm/archive/2008/11/18/member-static-variable-and-thread-safety-in-plug-in-for-crm-4-0.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1e71b1-7a82-b4b8-27ad-d1bbb78e3814
* Version Independent ID: 7c28f677-aba1-bd0d-173e-eaf187bf32e9
* Content: [Develop IPlugin implementations as stateless - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/best-practices/business-logic/develop-iplugin-implementations-stateless#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/best-practices/business-logic/develop-iplugin-implementations-stateless.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/best-practices/business-logic/develop-iplugin-implementations-stateless.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by phecke** [comment] 2021-11-11 02:00
@jhewetson 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-11-11 02:00 UTC
Labels: assigned-to-author, open-for-too-long
