### ISSUE TITLE
errorOptions.message is not displayed in the dialog

### ISSUE THREAD

**Issue by zhaparoff** [MicrosoftDocs/powerapps-docs#815] opened 2019-11-26 11:19 UTC
Dynamics CRM `v9.0.9.4`, on premise.
Specifying any of `errorOptions.message` and `errorOptions.details` gives the same result - passed value is put into the file for download.
When both are specified, `details` takes precedence and `message` value is lost.
But no combination of input parameters leads to a change of the message displayed in the dialog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea3c9c94-1f26-c3a4-8789-3b0cef9f1e6b
* Version Independent ID: fe0311f8-20c5-5ddb-a618-2ead070afb80
* Content: [openErrorDialog (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openerrordialog)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openErrorDialog.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openErrorDialog.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by aovar** [comment] 2020-01-08 15:27
Same behavior occurs in current Online instance

**Comment by Nkrb** [comment] 2020-11-12 17:35
@zhaparoff @aovar Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-12 17:35 UTC
Labels: assigned-to-author, client-api
