### ISSUE TITLE
Common Data Service permission "user_impersonation" not always necessary?

### ISSUE THREAD

**Issue by KimBon** [MicrosoftDocs/powerapps-docs#2144] opened 2021-02-22 20:18 UTC
I am wondering if you always need CDS "user impersonation" as API Permission.
If you are solely using this app registration for server-to-server authentication, and will only act as the Application User itself, this permission is not needed? Isn't this only needed when you want to have the user's consent and act on behalf of him/her?

Not clear in this documentation, and I see other power platform samples doing this as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11caa291-2e98-ac3a-d5d1-ecd416b93bdf
* Version Independent ID: 4f30cddd-8849-1887-ada0-a83a3d2a0027
* Content: [Tutorial: Register an app with Azure Active Directory (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/walkthrough-register-app-azure-active-directory)
* Content Source: [powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/walkthrough-register-app-azure-active-directory.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by KimBon** [comment] 2021-03-03 19:34
Like in the linked issue #2077 , I guess you only need delegated permissions if you want to act on behalf of the logged in user?

**Comment by phecke** [comment] 2022-05-24 23:48
@KimBon 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-05-24 23:48 UTC
Labels: assigned-to-author, open-for-too-long

**Comment by fowl2** [comment] 2022-05-25 00:46
This question is still relevant

**Comment by KimBon** [comment] 2022-05-25 15:39
Indeed still relevant as this scenario works but is undocumented

Op wo 25 mei 2022 om 02:46 schreef James May ***@***.***>:
