### ISSUE TITLE
db_owner role must use the database diagramming functionality

### ISSUE THREAD

**Issue by ugreg** [MicrosoftDocs/powerapps-docs#2340] opened 2021-05-05 20:25 UTC
How can I enable this role to see my DB diagrams?

![image](https://user-images.githubusercontent.com/8151045/117204589-5576f300-ada5-11eb-8056-ab8dd8f760df.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ead09d9-3e51-04ce-dc6e-ac9bb59816ec
* Version Independent ID: 94d19f8d-3c5e-8ed9-53ee-4b6173f49144
* Content: [Use SQL to query data (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query)
* Content Source: [powerapps-docs/developer/data-platform/dataverse-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/dataverse-sql-query.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment] 2022-05-24 22:23
@ugreg 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-05-24 22:23 UTC
Labels: assigned-to-author, open-for-too-long
