### ISSUE TITLE
Custom Workflow Activities not being registered

### ISSUE THREAD

**Issue by dmognaschi** [MicrosoftDocs/powerapps-docs#3766] opened 2022-10-21 16:43 UTC
Dear,
registering a package, all assemblies that expose at least one plugin type are correctly registered;
all public types that implement IPlugin are also correctly registered;
however, any custom workflow activities exposed by the assembly are not registered.

If it is a desired behavior (to push the adoption of the most modern CustomAPI) perhaps it would be better to explain it.

Ty,
Davide

**Comment by dmognaschi** [comment] 2022-10-21 16:51
Duplicate of #3767

**Comment by phecke** [comment] 2022-10-22 00:38
Duplicate of #3767

**Closed by phecke** 2022-10-22 00:38 UTC
