### ISSUE TITLE
ALM

### ISSUE THREAD

**Issue by boltlol** [MicrosoftDocs/powerapps-docs#2727] opened 2021-09-14 09:39 UTC
Hi,

I started trying out this preview feature. It seems to be missing information regarding how ALM works regarding the NEW_ solution namespace. How do we set it up to be under a different namespace? @Nkrb @srinathkannan 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b64c8d-3c3d-4e4d-afb1-5e0a54c84046
* Version Independent ID: 8180bdbe-ec98-642e-b7ee-1f57954ee502
* Content: [Create virtual tables using virtual connectors (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by srinathkannan** [comment] 2021-09-14 15:07
hi - all you have to do for ALM support is to add the virtual table, its connection reference and any other component you created using the virtual table into a new solution and export/ import into the new environment. Once the solution is imported, you will need to update the connection reference with values specific to the environment (powerapps environment ID, clientID and client secret).

**Comment by boltlol** [comment] 2021-09-15 07:37
What about the solution namespace, while working on a virtual entities project with FO the namespace was MSERP_ here it is the old NEW_ ? Do you intend to merge the solutions and thus rendering the current preview feature ALM structure broken? 

Am I missing something on how to change the NEW_ namespace to include it in our solution with a different namespace than the default solution?

**Comment by srinathkannan** [comment] 2021-10-04 15:38
Hi - you can create a new solution with any prefix and add the virtual table and the connection reference associated to that table export/ import in a new environment.  Happy to connect with you online to see your setup and issue you are having. You can email the team at dvvt@microsoft.com. thanks.

**Comment by JimDaly** [comment] 2022-03-28 20:37
Unless there are further issues related to the documentation here, I'm closing
Please re-open if you feel the issue isn't addressed.

**Closed by JimDaly** 2022-03-28 20:37 UTC
Labels: assigned-to-author
