### ISSUE TITLE
Add HttpClient

### ISSUE THREAD

**Issue by Ben-Fishin** [MicrosoftDocs/powerapps-docs#1306] opened 2020-04-24 20:57 UTC
Suggest adding examples for HttpClient patterns and anti-patterns as in...

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/best-practices/business-logic/set-timeout-for-external-calls-from-plug-ins

using (HttpClient client = new HttpClient())
{
  client.Timeout = TimeSpan.FromMilliseconds(15000); //15 seconds
  client.DefaultRequestHeaders.ConnectionClose = true; //Set KeepAlive to false
  

 

  HttpResponseMessage response =  client.GetAsync(webAddress).Result; //Make sure it is synchonrous
  response.EnsureSuccessStatusCode();

 

  string responseText = response.Content.ReadAsStringAsync().Result; //Make sure it is synchonrous
  tracingService.Trace(responseText);
  //Log success in the Plugin Trace Log:
  tracingService.Trace("HttpClientPlugin completed successfully.");
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf58f6eb-2257-4f80-65de-b181d9d19efe
* Version Independent ID: e3aef051-739c-1cea-ff03-9ca97ff46661
* Content: [Set KeepAlive to false when interacting with external hosts in a plug-in - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/best-practices/business-logic/set-keepalive-false-interacting-external-hosts-plugin#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/best-practices/business-logic/set-keepalive-false-interacting-external-hosts-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/best-practices/business-logic/set-keepalive-false-interacting-external-hosts-plugin.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by phecke** [comment] 2021-11-02 01:47
@Ben-Fishin 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 01:47 UTC
Labels: doc-enhancement, assigned-to-author, open-for-too-long
