### ISSUE TITLE
Managed solutions, why?

### ISSUE THREAD

**Issue by robdawsoncranhillinsight** [MicrosoftDocs/powerapps-docs#610] opened 2019-08-29 10:29 UTC
Why does this support only managed solutions? If we have chosen unmanaged specifically, does this mean we cannot use the PowerApps build tools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73ec2747-81eb-32df-8120-0215a2b8543d
* Version Independent ID: 674f07e3-f3a7-9a90-2df2-7582cdabedef
* Content: [Build tools tutorial and FAQ - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tutorial-faq#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-tutorial-faq.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-tutorial-faq.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by DeanGross** [comment] 2019-09-16 15:21
I have the same question

**Comment by mgr1054** [comment] 2019-09-19 15:42
It is a Best Practise to use unmanaged Solutions only for development, therefore you should not need unamanged Solutions in other environments. 

> **Deploying unmanaged solutions to production**
Deployment of unmanaged solutions is not true deployment. It is the placement of unmanaged component customizations into the target environment. This is the same as making that change directly within the target environment and is analogous to directly updating source code.


> Would you allow an authorized user to directly change source code in your production customer facing web site?

> If not, you should not allow an authorized user to directly change source code in your production Line of Business application.

**Comment by mikkelsen2000** [comment] 2019-09-23 22:01
Echoing mgr1054, unmanaged solutions should only be used for development. That said, the Build tools support both managed and unmanaged

**Comment by phecke** [comment] 2022-07-02 00:45
@robdawsoncranhillinsight Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:45 UTC
Labels: open-for-too-long
