### ISSUE TITLE
getNamedReference doesn`t return EntityReference type

### ISSUE THREAD

**Issue by MaTeMaTuK** [MicrosoftDocs/powerapps-docs#1704] opened 2020-08-27 19:32 UTC
When I call getNamedReference, I expect to see an etn value.
Instead I have _etn or logicalName
My package.json

> {
>   "name": "pcf-project",
>   "version": "1.0.1",
>   "description": "Project containing your PowerApps Component Framework (PCF) control.",
>   "scripts": {
>     "build": "pcf-scripts build",
>     "clean": "pcf-scripts clean",
>     "rebuild": "pcf-scripts rebuild",
>     "start": "pcf-scripts start"
>   },
>   "dependencies": {
>     "@ant-design/colors": "^4.0.5",
>     "@types/node": "^10.12.18",
>     "@types/powerapps-component-framework": "^1.2.3",
>     "@types/react": "^16.9.46",
>     "@types/react-dom": "^16.9.8",
>     "gantt-task-react": "^0.1.5",
>     "react": "^16.13.1",
>     "react-dom": "^16.13.1"
>   },
>   "devDependencies": {
>     "pcf-scripts": "^1",
>     "pcf-start": "^1"
>   }
> }

![image](https://user-images.githubusercontent.com/26743903/91486585-296dae80-e8b5-11ea-850d-e6fe5d185bb9.png)

**Comment by phecke** [comment] 2020-08-28 17:17
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/entityrecord/getnamedreference

**Comment by Nkrb** [comment] 2020-09-03 17:40
@MaTeMaTuK Thanks for the feedback. This is a known issue and we are fixing it. Will update it when we finish fixing the issue.

**Comment by Nkrb** [comment] 2020-10-22 21:20
Duplicate of #https://github.com/MicrosoftDocs/powerapps-docs/issues/1465. Closing the issue here. Please follow the other issue for updates on this.

**Closed by Nkrb** 2020-10-22 21:20 UTC
Labels: Component-framework, assigned-to-author, product-bug
