### ISSUE TITLE
"Return records size cannot exceed 134217728" error message although query should return fewer rows

### ISSUE THREAD

**Issue by TrutzS** [MicrosoftDocs/powerapps-docs#1476] opened 2020-06-05 11:51 UTC
Hi all,
We connect to the endpoint and are able to retrieve data using _SELECT Count(...) FROM..._ as well as _SELECT TOP(1000) ... FROM ..._ statements
But if we want to retrieve all lines from a table that has ~143000 rows we receive the following error message. Using select _SELECT TOP(150000) ... FROM ..._ provides the same error although the limit stated in the error message is much higher.

```
Msg 40000, Level 16, State 1, Line 1
Return records size cannot exceed 134217728. Make sure to filter result set to tailor it to your report.
RequestId: TDS;b38c756e-2bd5-49dd-a9ac-e4a6402839ff;10
Time: 2020-06-05T11:44:43.5006966Z
```

![image](https://user-images.githubusercontent.com/38720925/83872881-1d99a280-a733-11ea-9263-8c2690243244.png)

Any help is appreciated.

Kind regards,
Trutz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60540f3d-b959-2daa-23a1-2938de01919d
* Version Independent ID: 07b12c3a-a0db-47f1-1aca-04008c9efca9
* Content: [Use SQL to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query)
* Content Source: [powerapps-docs/developer/common-data-service/cds-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/cds-sql-query.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by mayadumesh** [comment] 2020-06-10 00:33
The size of data retrieved can not exceed 128MB. 134217728 B   ÷   1024 ÷   1024 = 128 MB. 

Please use OData endpoint for such operations.

**Comment by phecke** [comment] 2021-11-02 01:16
@TrutzS 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 01:16 UTC
Labels: assigned-to-author, open-for-too-long
