### ISSUE TITLE
不明

### ISSUE THREAD

**Issue by eruza1** [MicrosoftDocs/powerapps-docs#3920] opened 2022-12-27 00:52 UTC
エクセルのファイルがサーバエラーでダウンロードできません。

求めている方法は　ProductImage[image]　で格納する方法ですがこちらが該当するのでしょうか

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 learn.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 95252238-504d-de48-8b61-ac3b38ef67f1
* Version Independent ID: 408cdb15-7e59-89d9-ab3c-5bc3e116e6c9
* Content: [Power Apps での Image コントロール - Power Apps](https://learn.microsoft.com/ja-jp/power-apps/maker/canvas-apps/controls/control-image)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-image.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/canvas-apps/controls/control-image.md)
* Service: **powerapps**
* Sub-service: **canvas-maker**
* GitHub Login: @chmoncay
* Microsoft Alias: **chmoncay**

**Comment by bishalgoswami** [comment] 2022-12-27 02:00
Thanks for your comment, @eruza1. This issue has been assigned to the doc author for review.

**Comment by mduelae** [comment] 2023-01-10 00:31
@Dealgan12  Is there an issue with this help article? Can you provide more details?

Thanks,
Mints

**Comment by Dealgan12** [comment] 2023-01-10 09:42
Hi @mduelae this is not specific to Japanese, the issue also happens on English source content where an error occurs when you try to download the excel document. 

on the page https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/control-image and search for "Download this [Excel file](https://pwrappssamples.blob.core.windows.net/samples/FlooringEstimates.xlsx), and save it on your local device."

**Comment by mduelae** [comment] 2023-01-18 00:25
@Dealgan12 Now I see what the issue is. Thank you for pointing this out. I'm going to look into this and I will get back soon.

Thanks,
Mints

**Comment by mduelae** [comment] 2023-01-19 21:05
@Dealgan12  - I have updated the link to the excel file.  You should see the changes on the help topic in about 15 minutes. 

Thanks,
Mints

**Closed by mduelae** 2023-01-19 21:05 UTC
Labels: assigned-to-author, in-progress, resolved, doc-needs-updating

**Comment by Dealgan12** [comment] 2023-01-20 11:07
Many thanks @mduelae . The change will be picked up in our next handoff and will be available next week.
