### ISSUE TITLE
Following the steps result in 401 error

### ISSUE THREAD

**Issue by fadyanwar** [MicrosoftDocs/powerapps-docs#1339] opened 2020-05-05 00:38 UTC
Is the client id up to date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80534df2-e9da-fd0a-80bf-4bfc0dbb2fcc
* Version Independent ID: b8053ca7-e385-2f0b-06af-81b908f345a1
* Content: [Set up a Postman environment (Common Data Service for Apps) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/setup-postman-environment#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/setup-postman-environment.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/setup-postman-environment.md)
* Service: **powerapps**
* GitHub Login: @susikka
* Microsoft Alias: **susikka**

**Comment by fadyanwar** [comment] 2020-05-05 00:43
In Postman, under Authorization tab, "Add authorization data" needs to be set to "Request Headers", kindly update the article accordingly. Thanks.

**Comment by phecke** [comment] 2023-01-30 21:29
@fadyanwar Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2023-01-30 21:29 UTC
Labels: assigned-to-author, open-for-too-long
