### ISSUE TITLE
Map to Standard missing

### ISSUE THREAD

**Issue by imran-siddique** [MicrosoftDocs/powerapps-docs#937] opened 2020-01-10 23:50 UTC
&gt;To leverage the Common Data Model with your dataflow, select the Map to Standard transformation in the Edit Queries dialog.

When I try to load data from Azure Synapse, in the Edit Queries dialog, I don't see this "Map to Standard" option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3abf73d-60b9-675f-61e7-1c2dc622d055
* Version Independent ID: 352c1196-0631-9f40-e382-bba13d5e27e9
* Content: [Create and use dataflows in Power Apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-and-use-dataflows)
* Content Source: [powerapps-docs/maker/common-data-service/create-and-use-dataflows.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-and-use-dataflows.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment] 2021-07-28 23:06
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 23:06 UTC
Labels: assigned-to-author, open-for-too-long
