### ISSUE TITLE
Where can I get an AccessToken from an sample?

### ISSUE THREAD

**Issue by vaclavrozsypal** [MicrosoftDocs/powerapps-docs#1926] opened 2020-11-13 12:00 UTC
How do I get an external data source connection configuration from a virtual entity?

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: f38df8a3-58d1-6cd9-2dac-4ea6c857f01e
* Version Independent ID: 7bb3e8c6-067d-321b-375b-c1f9752e91b8
* Content: [Sample: Generic virtual entity data provider plug-in (Common Data Service) - Power Apps](https://docs.microsoft.com/cs-cz/powerapps/developer/common-data-service/virtual-entities/sample-generic-ve-plugin?source=docs)
* Content Source: [powerapps-docs/developer/common-data-service/virtual-entities/sample-generic-ve-plugin.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/virtual-entities/sample-generic-ve-plugin.md)
* Service: **powerapps**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment] 2022-08-13 00:52
@vaclavrozsypal  Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-08-13 00:52 UTC
Labels: assigned-to-author, open-for-too-long
