### ISSUE TITLE
SQL Error - Specified Cast is not valid (Object Explorer)

### ISSUE THREAD

**Issue by Sudheerreddyn14** [MicrosoftDocs/powerapps-docs#1428] opened 2020-05-21 03:08 UTC
I could connect to the server using SSMS, but while expanding the Databases I was getting this error "Specified Cast is not valid (Object Explorer)".

![image](https://user-images.githubusercontent.com/37790033/82519072-6d2a7c80-9b3e-11ea-8da4-ab69cdc3c6ee.png)

**Comment by phecke** [comment] 2020-05-22 00:06
@Sudheerreddyn14 Are you trying to access the entity tables using the new SQL endpoint of CDS?

**Comment by phecke** [comment] 2021-11-02 01:30
@Sudheerreddyn14 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 01:30 UTC
Labels: assigned-to-author, open-for-too-long
