### ISSUE TITLE
Sites being created Private but no way to make them Public yet

### ISSUE THREAD

**Issue by MattyBearBytes** [MicrosoftDocs/powerapps-docs#3713] opened 2022-10-05 06:52 UTC
This announcement for the Power Pages new Site Visibility is frustrating.
We have new sites that are being created and in the default state of "Private"

However, the Power Pages UI for the site, under the Setup menu, does not have the Visibility option.  Our users are D365/Power Platform Administrators.

What do we do when we are in this state of limbo?
Site Visibility defaults to PRIVATE for new Power Pages sites
WE have the proper Administration role in the Tenant
Our tenant does not have the Site Visibility toggle available to us to make it PUBLIC?

This page should address it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7279ee4-dc2b-3352-e2eb-fd8fbcd8100d
* Version Independent ID: 79984658-d334-45a9-329e-4ed4d9939df3
* Content: [Important upcoming changes and deprecations in Power Apps portals - Power Apps](https://learn.microsoft.com/en-us/power-apps/maker/portals/important-changes-deprecations#controlling-site-visibility-changes-in-power-pages)
* Content Source: [powerapps-docs/maker/portals/important-changes-deprecations.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/important-changes-deprecations.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
* Microsoft Alias: **sandhan**

**Comment by nickdoelman** [comment] 2022-10-11 14:15
Can you please indicate if you are still experiencing this issue, and what region your portal/site is located in?

**Comment by MattyBearBytes** [comment] 2022-10-11 14:23
Many thanks

It seems to have resolved itself after the last updates for Power Pages late last week. The screen appears now to make it public.

This was in Australia region

-M

On 11 Oct 2022, at 10:15 pm, nickdoelman ***@***.***> wrote:

﻿

Can you please indicate if you are still experiencing this issue, and what region your portal/site is located in?

**Comment by nickdoelman** [comment] 2022-10-11 16:50
Thank you for confirming the issue is resolved. If it happens again, please raise a [support ticket](https://learn.microsoft.com/power-platform/admin/get-help-support). Thank you also for your feedback. 

Closing the issue.

**Closed by nickdoelman** 2022-10-11 16:50 UTC
Labels: assigned-to-author
