### ISSUE TITLE
what happens if we Columnset contains attribute which is not in entity ? 

### ISSUE THREAD

**Issue by Kaviarasi** [MicrosoftDocs/powerapps-docs#1137] opened 2020-03-12 06:52 UTC
will this throw exception or will it retrieve columns which are available in the entity ignoring the non existent column 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce94640c-f5be-9ec4-b57c-bf8baf5102b1
* Version Independent ID: ce3a204b-bf0b-4885-c944-287acdf09684
* Content: [Retrieve specific columns for an entity via query APIs - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/best-practices/work-with-metadata/retrieve-specific-columns-entity-via-query-apis)
* Content Source: [powerapps-docs/developer/common-data-service/best-practices/work-with-metadata/retrieve-specific-columns-entity-via-query-apis.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/best-practices/work-with-metadata/retrieve-specific-columns-entity-via-query-apis.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by phecke** [comment] 2020-03-13 22:19
@Kaviarasi I do not know.  You could try it with some sample data. However, you should be following what is stated in our documentation because whatever functionality you may discover is not guaranteed to stay the same in the future.

Is there a particular documentation page that you would like clarification on? If so, please provide a link. Thanks

**Comment by phecke** [comment] 2020-03-13 22:24
@Kaviarasi I do know that you can write code for late-bound entities or attributes which may not exist in the system. Is this what you are doing? So the question becomes what behavior do you see when you try to access that data if that attribute does not exist (not in any solution). I will check on this, but let me know if this is what you are looking for first.

**Comment by phecke** [comment] 2021-11-11 03:16
@Kaviarasi 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-11-11 03:16 UTC
Labels: assigned-to-author, open-for-too-long
