### ISSUE TITLE
Cannot get the gridcontext for subgrid in the main form

### ISSUE THREAD

**Issue by sabin-sharma** [MicrosoftDocs/powerapps-docs#4497] opened 2023-06-27 21:19 UTC
Hi,

I am trying to get the gridcontext and then get the subgrid using getGrid() function and  then rows in subgrid using getrows() function.

onSave Event of the subgrid, onChange event of the subgrid, I have the following code.
`function doSomething(executionContext)
{

  var formContext = executionContext.getFormContext();
  var oppSubgridContext =  formContext.getControl('subgridname'); // this returns null
  var oppSubgrid = oppSubgridContext.getGrid();
  var oppSubgridRows = oppSubgrid.getRows();
  if(oppSubgridRows.getLength() > 0)
  {
    oppSubgridRows.forEach(function(attribute,index)
     {
          console.log("attribute: " + attribute);
          console.log("index: " + index);
      });
  
  }
}`

executionContext is passed as parameter and subgrid name is also correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e83c71d7-6c0e-14cd-a171-971e0bea398e
* Version Independent ID: 31c7103e-e49f-ed58-20bb-cefc3b430eb3
* Content: [Client API grid context in model-driven apps - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/clientapi-grid-context)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/clientapi-grid-context.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/clientapi-grid-context.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by bishalgoswami** [comment] 2023-06-27 23:00
Thanks for your comment, @sabin-sharma. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment] 2023-06-27 23:25
@sabin-sharma 

Thanks for your feedback. 

The issue you seem to be experiencing is that the [formContext.getControl](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/controls/getcontrol) is returning null.

You seem sure that the `subgridname` value you are using is correct, but that seems to be the most likely point of failure.
Have you double-checked that the value you are using is returned by examining the values of the `formContext.ui.controls` collection?

The issues in this repository are for feedback regarding the documentation. Without knowing the root cause of the issue you are experiencing, there isn't anything actionable from a documentation perspective. I would look for what guidance we can provide to help other avoid this issue. 

I'm afraid I can't help in troubleshooting this further. If you need help or believe this is a bug, please contact technical support.

**Closed by JimDaly** 2023-06-27 23:25 UTC
Labels: assigned-to-author
