### ISSUE TITLE
.NET Framework version plugin support could be highlighted

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/powerapps-docs#2930] opened 2021-12-20 15:25 UTC
Having raised support ticket 2112130050001744 with the Power Platform team, I understand there's a known limitation of Solution Checker in that it can't support/analyse plugins written against .NET Framework versions earlier than 4.6  Whilst it would be nice to have that made visible when starting solution checker, maybe a note in the documentation about this would make it less likely to trip people up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b06e51-1090-87c7-33ff-a19b1c8a8ada
* Version Independent ID: b4a96b9e-62d2-55bf-3585-435474696771
* Content: [Use solution checker to validate your apps in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/use-powerapps-checker)
* Content Source: [powerapps-docs/maker/data-platform/use-powerapps-checker.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/data-platform/use-powerapps-checker.md)
* Service: **powerapps**
* Sub-service: **dataverse-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment] 2023-01-12 16:38
@rrhkpmg - “Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, reopen or create a new issue.

**Closed by Mattp123** 2023-01-12 16:38 UTC
Labels: assigned-to-author, waiting-on-internal-feedback
