### ISSUE TITLE
User().Email returns UPN not email

### ISSUE THREAD

**Issue by DavesTechTips** [MicrosoftDocs/powerapps-docs#582] opened 2019-08-19 15:57 UTC
Hi everyone.
Please note that the User().Email function returns the UPN and not the Email address. This is typically not a problem if the Email and UPN is the same, but it is important to be aware of if these are not the same. Below is a quick video to explain more.

https://youtu.be/6FU1xGxJK5w

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5ca5a0a-bc28-3938-fb72-bf24deaede99
* Version Independent ID: ade2f96a-f1ce-e96c-422c-a344ea5b0c84
* Content: [User function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-user)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-user.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-user.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by DTronD** [comment] 2020-05-21 21:57
Yes, it would greatly help if this was corrected so the Email property actually contained the user's primary email address instead of the UPN mislabeled as Email.

**Comment by DTronD** [comment] 2020-05-21 22:30
Also, it might be useful to note a workaround to get the actual (primary) email for a user is to use the Office365 Connector and either of the GetMyProfileV2 or GetUserProfileV2 actions/methods. E.g.
Set(global_CurrentUserEmail, Office365Users.MyProfileV2().mail);

**Comment by Nkrb** [comment] 2020-10-15 16:26
Duplicate of #https://github.com/MicrosoftDocs/powerapps-docs/issues/1725. Closing the issue here. Please follow the other issue for updates.

**Closed by Nkrb** 2020-10-15 16:26 UTC
Labels: CanvasApp, assigned-to-author, product-bug, waiting-on-internal-feedback
