### ISSUE TITLE
When I use this function to set entitytype for regarding, sometime regarding “Change View” can not see some entity I set.

### ISSUE THREAD

**Issue by zstCreating** [MicrosoftDocs/powerapps-docs#950] opened 2020-01-15 01:42 UTC
When I use this function to set entitytype for regarding, sometime regarding “Change View” can not see some entity I set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171767a7-8acf-6025-68d2-e752dacea431
* Version Independent ID: 0c5045ab-df21-7d82-3eee-364955ea2920
* Content: [setEntityTypes (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/setentitytypes#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setEntityTypes.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/setEntityTypes.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by zstCreating** [comment] 2020-01-15 01:58
![1](https://user-images.githubusercontent.com/13195570/72398313-8af56880-377d-11ea-8fd4-b9fc31386378.JPG)
![2](https://user-images.githubusercontent.com/13195570/72398314-8af56880-377d-11ea-9750-377bc9a739a9.png)
![3](https://user-images.githubusercontent.com/13195570/72398315-8af56880-377d-11ea-8bf9-349216073224.png)

**Comment by zstCreating** [comment] 2020-01-15 02:01
I use this function on a custom entity form "OnLoad" event.

**Comment by simes1** [comment] 2020-04-02 10:59
I have the same problem restricting the parentcustomerid lookup on Contact Quick Create form to just Accounts:
![image](https://user-images.githubusercontent.com/11423243/78242123-5fab2b80-74d9-11ea-94e9-8ab635494831.png)

**Comment by Nkrb** [comment] 2020-11-11 18:55
@zstCreating @simes1 Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 18:55 UTC
Labels: assigned-to-author, client-api
