### ISSUE TITLE
Missing information on basic paging

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#549] opened 2019-07-31 17:47 UTC
While we have a topic dedicated to paging large result sets with the paging cookie [Page large result sets with FetchXML](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/page-large-result-sets-with-fetchxml)

I don't see anything about the simple approach to get the next page by simply setting the `page` attribute value. i.e. `<fetch page='2' >` without a paging cookie.

For example:
```
<fetch count='2' page='1' >
  <entity name='account' >
    <attribute name='name' />
    <order attribute='name' />
  </entity>
</fetch>
```
Changing `page` to 2 will bring the next 2 records.

Paging cookie is an optimization for large result sets, but it adds a good deal of complexity to what could be very simple, especially for ad hoc queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55426bf-e3ed-2d4f-d2e9-1edf60ebe6c6
* Version Independent ID: d26739ec-4b1e-77da-7ba3-fa87e7723300
* Content: [Use FetchXML to query data (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-fetchxml-construct-query)
* Content Source: [powerapps-docs/developer/common-data-service/use-fetchxml-construct-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-fetchxml-construct-query.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by aabdelmotaleb** [comment] 2019-08-02 14:47
FetchXML queries can return as many pages as required without using Paging Cookie if the number of rows in the entities is less than 12500 rows. If we try to retrieve pages of rows after the first 12500 rows, then we will get an error that Paging Cookie is required.

**Comment by aabdelmotaleb** [comment] 2019-08-02 14:50
In the documentation here:
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/page-large-result-sets-with-fetchxml

It's written:
_When you use the paging cookie with FetchXML, make sure that you use the correct encoding. The following example shows the correct encoding when using the paging cookie with FetchXML_

Without explanation on how to convert the paging cookie returned in the http response to this form. It took from me couple of hours to find that the returned paging cookie is doubly html encoded, so I had to decode it twice and then escape the xml special characters to get the paging-cookie provided in the example

**Comment by phecke** [comment] 2022-07-02 00:10
@JimDaly Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:10 UTC
Labels: open-for-too-long
