### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by olavt** [MicrosoftDocs/powerapps-docs#1775] opened 2020-09-24 07:52 UTC
In this article it states "The apps you build and publish with Power Apps are discovered and used in Dynamics 365 on the web.". This is a bit misleading. The application may also show up there, but many PowerApps are not related to Dynamics 365 and they should not show up there. PowerApps published to AppSource are certainly also available to find on https://appsource.microsoft.com/. PowerApps may also be discovered through the PowerApp on mobile devices. I was very confused by the article and thought that PowerApps would only show up on "Dynamics 365 on the web". The article should be updated to be less Dynamics 365 focused. The same goes for the link "More information: Discover apps via AppSource." (https://docs.microsoft.com/en-us/powerapps/user/app-source)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7234cd54-0c55-b16a-12ec-7aac98c021db
* Version Independent ID: 7d742fff-efc7-6bd7-1efe-09aeb57fd2be
* Content: [Publish your app on AppSource (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/publish-app-appsource)
* Content Source: [powerapps-docs/developer/common-data-service/publish-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/publish-app-appsource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by phecke** [comment] 2021-11-02 00:31
@olavt 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 00:31 UTC
Labels: assigned-to-author, open-for-too-long
