### ISSUE TITLE
Pass a Parameter to Power BI Tile Not Working

### ISSUE THREAD

**Issue by dnachimow** [MicrosoftDocs/powerapps-docs#297] opened 2019-03-25 17:33 UTC
This documentation is the only place where I've seen this functionality reported as available. Everyone else I've looked has indicated that this is not possible. I've attempted this several times, none of which have been successful. Can someone please confirm that this feature is simply mis-documented here and is not in fact available.

Pass a parameter
By passing a single parameter from the app, you can filter the results that appear in a Power BI tile. However, only string values and the equals operator are supported, and the filter might not work if the table name or the column name contains spaces.

To pass a single filter value, modify the value of the TileURL property, which follows this syntax:

"https://app.powerbi.com/embed?dashboardId=&lt;DashboardID&gt;&tileId=&lt;TileID&gt;&config=&lt;SomeHash&gt;"

To that value, append this syntax:

&$filter=&lt;TableName&gt;/&lt;ColumnName&gt; eq "&lt;Value&gt;"

The parameter will filter a value in the dataset of the report where the tile originates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9804ada3-9503-a2de-5239-540d5e702e36
* Version Independent ID: 8bf085bb-bd86-3a79-4758-d40d99ba0cc6
* Content: [Power BI tile control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-power-bi-tile#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-power-bi-tile.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by StefKorson-JS** [comment] 2019-04-18 06:35
I can confirm this feature currently isn't working. No filter is applied to the tile when the parameter is passed. Could this be fixed?

**Comment by jovanms** [comment] 2019-04-18 22:23
Hi, I have this working when appending the following to TileUrl:

`&$filter=MyTable/MyProvince eq 'MyValue' `

It looks like the docs give double quotes around the value, but single quotes are correct.

Does that fix it?

**Comment by fikaradz** [comment] 2019-04-18 23:43
Thanks for pointing this out, we are fixing the docs now.

**Comment by AFTOwen** [comment] 2019-04-19 01:14
Thanks to @dnachimow for raising the issue, @StefKorson-JS for confirming, and @jovanms for publishing the fix before we did. Closing the issue.

cc: @fikaradz

**Closed by AFTOwen** 2019-04-19 01:14 UTC
Labels: 01canvas, assigned-to-author
