### ISSUE TITLE
Publication process change

### ISSUE THREAD

**Issue by BrianLevenson** [MicrosoftDocs/powerapps-docs#619] opened 2019-09-04 02:34 UTC
To become a publisher in Microsoft's commercial marketplace (AppSource included), partners sign up through Partner Center rather than the AppSource nomination link. Registration is done here: aka.ms/joinmarketplace and more generally, I'd recommend pointing to the publisher guide rather than having separate content in this repo to avoid updating so many locations. This page is not managed or monitored by the marketplace team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7234cd54-0c55-b16a-12ec-7aac98c021db
* Version Independent ID: 7d742fff-efc7-6bd7-1efe-09aeb57fd2be
* Content: [Publish your app on AppSource (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/publish-app-appsource#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/publish-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/publish-app-appsource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by phecke** [comment] 2022-07-02 00:49
@BrianLevenson Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:49 UTC
Labels: open-for-too-long
