### ISSUE TITLE
Error: Resource not found for the segment contact.

### ISSUE THREAD

**Issue by thebruuu** [MicrosoftDocs/powerapps-docs#3070] opened 2022-02-09 15:13 UTC
[Enter feedback HI
i am not able to have the expected results from the Web APi wlakthrough
Is there any specific condition on the portal to be created?
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9480e54f-8118-3213-dc4c-b3c26140422c
* Version Independent ID: 9480e54f-8118-3213-dc4c-b3c26140422c
* Content: [Tutorial: How to use the portal Web API - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/webapi-tutorial#step-5-use-the-web-api-to-read-view-edit-create-and-delete)
* Content Source: [powerapps-docs/maker/portals/webapi-tutorial.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/webapi-tutorial.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by nickdoelman** [comment] 2023-01-16 14:15
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by nickdoelman** 2023-01-16 14:15 UTC
Labels: assigned-to-author
