### ISSUE TITLE
Enabling SLAs on a vanilla Dataverse Organization

### ISSUE THREAD

**Issue by brianilland** [MicrosoftDocs/powerapps-docs#2262] opened 2021-04-09 17:02 UTC
This article seems to indicate that SLAs can be enabled on custom entities in a Dataverse, non Dynamics 365 organisation. Is this correct? 

On a vanilla dataverse organisation the checkbox for enabling entities for SLAs is no longer appearing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb5038e1-dc34-dad5-7359-10ab87a5839e
* Version Independent ID: b5105a02-a98b-99da-dafe-d62e04572121
* Content: [Apply SLAs to entities (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/apply-slas-entities)
* Content Source: [powerapps-docs/developer/data-platform/apply-slas-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/apply-slas-entities.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-05-24 23:35
@brianilland 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-05-24 23:35 UTC
Labels: assigned-to-author, open-for-too-long
