### ISSUE TITLE
Update this page to reflect new restricted entities?

### ISSUE THREAD

**Issue by robdawsoncranhillinsight** [MicrosoftDocs/powerapps-docs#680] opened 2019-10-02 11:15 UTC
Charles Lamanna confirmed in conversation with Steve Mordue that the list of restricted entities will be revised. The recently published Oct 19 licensing makes reference to restricted entities, but this page is stale since 2018. When will this list be made available please? Thanks
https://stevemordue.com/steve-has-another-chat-with-charles-lamanna/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecf0cd5-9a4c-780a-7cc9-c189d399efa5
* Version Independent ID: 32aeab29-70b5-97b3-1a6b-96c6bfcecc3c
* Content: [Restricted entities requiring Dynamics 365 licenses - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by iangpgh** [comment] 2020-04-06 23:07
@robdawsoncranhillinsight Article is recently updated with the list of restricted entities.
 
[Restricted entities requiring Dynamics 365 licenses](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities)

**Comment by iangpgh** [comment] 2020-04-15 18:30
@robdawsoncranhillinsight Correction: the list of restricted entities was not updated in this article. We are working on updating these soon.

**Comment by Mattp123** [comment] 2021-07-28 23:05
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 23:05 UTC
Labels: assigned-to-author, open-for-too-long
