### ISSUE TITLE
InsertOptionValue Action Sample Code

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/powerapps-docs#307] opened 2019-04-05 02:58 UTC
I want to Insert a new option into a global option set using the `InsertOptionValue Action`, but don't see any sample code or REST call, can you add it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87414a4-998b-7269-536f-b86aa256f47d
* Version Independent ID: 3ff8d533-40dd-a052-84b8-ae423df6dec3
* Content: [Create and update option sets using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/create-update-optionsets#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/create-update-optionsets.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/create-update-optionsets.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by gregdegruy** [comment] 2019-04-08 17:34
Any feedback on this team? I still do not have the right URL or example payload data to send with my `POST` request.

Feel like I'm getting close with this, I think I need to use actions in some way, but don't know the syntax `https://myorg.api.crm.dynamics.com/api/data/v9.0/GlobalOptionSetDefinitions(06d1a507-4d57-e911-a82a-000d3a1d5203)/Microsoft.Dynamics.CRM.OptionSetMetadata/Options.InsertOptionValue`

**Comment by mkalinov** [comment] 2019-07-16 15:26
Thy OOB actions:

https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/insertoptionvalue?view=dynamics-ce-odata-9

**Comment by johnstairs** [comment] 2019-09-23 22:03
I came across this as well. It looks like the docs could be improved. 

You can invoke the action with something like this:

``` HTTP 
POST [root]/InsertOptionValue

{
  "OptionSetName": "abc_foo",
  "Label": {
      "LocalizedLabels": [
          {
              "Label": "Bar",
              "LanguageCode": 1033
          }
      ]
  }
}
```

**Comment by mylle** [comment] 2020-11-03 09:00
> Any feedback on this team? I still do not have the right URL or example payload data to send with my `POST` request.
> 
> Feel like I'm getting close with this, I think I need to use actions in some way, but don't know the syntax `https://myorg.api.crm.dynamics.com/api/data/v9.0/GlobalOptionSetDefinitions(06d1a507-4d57-e911-a82a-000d3a1d5203)/Microsoft.Dynamics.CRM.OptionSetMetadata/Options.InsertOptionValue`

Did you find the solution?

**Comment by phecke** [comment] 2021-06-17 00:56
@gregdegruy

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-06-17 00:56 UTC
Labels: open-for-too-long
