### ISSUE TITLE
The documentation describes how to create a package in Dynamics 365 and not in PowerApps

### ISSUE THREAD

**Issue by dansemedo** [MicrosoftDocs/powerapps-docs#2282] opened 2021-04-14 20:16 UTC
I would like to have a documentation that shows how to publish/create a package using only PowerApps instead of Dynamics 365, the steps 2 and 3 describes only Dynamics 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2c7898-1e5f-184c-bb89-8acdf96c0023
* Version Independent ID: f46bf08e-14dc-4111-c74e-db374f377566
* Content: [Step 3: Create an AppSource package for your app (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/create-package-app-appsource)
* Content Source: [powerapps-docs/developer/data-platform/create-package-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/create-package-app-appsource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by phecke** [comment] 2022-05-03 21:38
@dansemedo 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-05-03 21:38 UTC
Labels: assigned-to-author, open-for-too-long
