### ISSUE TITLE
Web Resource being loaded twice

### ISSUE THREAD

**Issue by paulhasell** [MicrosoftDocs/powerapps-docs#1825] opened 2020-10-19 08:10 UTC
Hi, we followed this sample but have had issues where the resource would sporadically get reset. On investigation we can see that the HTML web resource gets loaded twice by the page framework so race conditions apply and randomly the resource is reset after being initialised at page load.

Is there a better event to use to initialise the web resource?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4c796e-ad9f-1929-f530-f088462522f9
* Version Independent ID: 40e67735-ac26-30a4-3191-0a86fd7b4b50
* Content: [getContentWindow (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/getcontentwindow)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2020-10-19 18:38
@paulhasell Thanks for contacting us. We will verify the issue from our side and get back to you.

**Comment by Nkrb** [comment] 2021-06-16 23:35
Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2021-06-16 23:35 UTC
Labels: assigned-to-author, client-api
