### ISSUE TITLE
Incorrect return type

### ISSUE THREAD

**Issue by BetimBeja** [MicrosoftDocs/powerapps-docs#1740] opened 2020-09-14 14:41 UTC
The documentation and the typings seem to be not aligned with the Online Version of the CRM. Just like issue #1738 
![image](https://user-images.githubusercontent.com/11160171/93099790-b764da00-f6a8-11ea-8510-7ff3e46c97e9.png)

![image](https://user-images.githubusercontent.com/11160171/93099884-d4011200-f6a8-11ea-9606-dd430a783964.png)

![image](https://user-images.githubusercontent.com/11160171/93099953-ea0ed280-f6a8-11ea-9c81-f41787c6e9b0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adb7aec-f488-0653-4b0e-2793d9b75509
* Version Independent ID: aa79b169-3a80-1a06-dba3-d173d8e22aa0
* Content: [lookupObjects - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/utility/lookupobjects)
* Content Source: [powerapps-docs/developer/component-framework/reference/utility/lookupobjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/utility/lookupobjects.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2020-11-11 19:25
@BetimBeja Thanks for contacting us. We have created a internal work item for the respective dev team to update the return type. Will update the docs when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 19:25 UTC
Labels: Component-framework, assigned-to-author, product-bug
