### ISSUE TITLE
Instructions for New Publisher from PowerApps.com wrong maybe

### ISSUE THREAD

**Issue by DTronD** [MicrosoftDocs/powerapps-docs#641] opened 2019-09-17 17:12 UTC
I cannot locate the "Common Data Service - Custom App" when I follow the steps in the "Create a solution publisher and solution" section.  Instead, I used the "Solutions" menu item on the left nav of PowerApps.com, and then "Advanced Customizations" from the upper-left "gear" icon menu, then that menu's "Publishers" Item.  I have the new/modern theme on in PA.com (i.e. top menu offers "Switch to classic."  But that doesn't explain why I cannot find the CDS-"Custom App"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcb108dd-66c5-1901-8ee9-9636dd251044
* Version Independent ID: 2c811eaa-92a6-5934-05ef-2398968a89ff
* Content: [Introduction to solutions - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/introduction-solutions)
* Content Source: [powerapps-docs/developer/common-data-service/introduction-solutions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/introduction-solutions.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by ghdunn** [comment] 2020-01-15 11:31
Likewise, I cannot locate "Common Data Service - Custom App".  Unfortunately I also cannot locate the gear icon on the upper left.  There is a gear icon upper right, but it doesn't have Advanced Customizations.  Any workaround for the workaround :) ?

**Comment by apoloduvalis** [comment] 2020-06-14 18:11
Yes, the instructions seem to be wrong (or outdated). The procedure that worked for me was at powerapps.com:

1. At the bottom of the left menu, select "Solutions".
2. At the top tools ribbon, click on "+ New Solution".
3. At the "New solution" form, in the Publisher field, select the "+ Publisher" option. A new window will open.
4. At the new window "Publisher: New Publisher / Information" fill the required fields and click in "Save and Close".

**Comment by phecke** [comment] 2022-07-02 00:57
@DTronD Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:57 UTC
Labels: open-for-too-long
