### ISSUE TITLE
incorrect example

### ISSUE THREAD

**Issue by sharonbn1** [MicrosoftDocs/powerapps-docs#330] opened 2019-04-16 08:15 UTC
in the example, the boundary values in the request and response don't match. very confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af14071e-83a5-8dde-6346-d158b4d5d66a
* Version Independent ID: 8fb0f4fb-17ff-7491-d057-a1edf9242bc8
* Content: [Execute batch operations using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/execute-batch-operations-using-web-api#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/execute-batch-operations-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment] 2019-05-10 19:35
@sharonbn1 The $batch operation shown in the example has a unique identifier of value `AAA123` and a change set with a unique identifier of `BBB456`. This is shown in the response as well.

**Comment by sharonbn1** [comment] 2019-05-12 06:38
the response shows following identifiers: 
--batchresponse_c1bd45c1-dd81-470d-b897-e965846aad2f  
--changesetresponse_ff83b4f1-ab48-430c-b81c-926a2c596abc  

do a search on these strings and you'll see what I am talking about.
I repeat: in the current state, the example is very confusing

**Comment by susikka** [comment] 2019-05-18 10:48
@sharonbn1 Thanks for your response. We are working on updating the batch operations topic; will comment on this issue once we publish the updated doc.

**Comment by JimDaly** [comment] 2019-08-18 17:20
@susikka 
The issue I think that @sharonbn1  is referring to is how the unique identifiers in the request and response examples don't match.

For example in the [Reference URIs in an operation](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/execute-batch-operations-using-web-api#reference-uris-in-an-operation) section, the **Request** example uses `batch_AAA123` and the **Response** example uses `batchresponse_3cace264-86ea-40fe-83d3-954b336c0f4a`. I think that the expectation is that the values should correspond with each other? 

While that makes sense, IDK if that is the way this actually works. If the unique identifier parts of these are generated on the server, it may be something we should call out. I plan to do some work with this today and I'll get back if I find anything to confirm the behavior people should expect.

If the issue is about how the boundary and changeset delimiters are used, I think we are following the pattern in the OData Version 4.0 Part 1: Protocol spec : [11.7.2 Batch Request Body](http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Toc372793750)

**Comment by anandkgpt03** [comment] 2019-08-29 07:33
I have a query @sharonbn1.
Suppose I am executing long-running two or more parallel batch request exporting millions of records through each of them.
Is it necessary to provide unique_identifier to all the parallel request or they can use the same unique_identifier?
What's the possible problem can occur if using the same identifier in all the parallel requests?

**Comment by phecke** [comment] 2021-06-17 01:00
@sharonbn1

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-06-17 01:00 UTC
Labels: open-for-too-long
