### ISSUE TITLE
Usage of relationship attribute in entityrecord pageType of pageInput object in navigateTo() API

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/powerapps-docs#1589] opened 2020-07-14 20:37 UTC
What is the usage of the following attribute in the navigateTo() API?
_relationship: (Optional) Object. Define a relationship object to display the related records on the form._
I used the createFromEntity and it populates the mapping fields properly but do we still need to add the values for relationship object?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c917fb9-84c8-2676-9c6a-f33f03ba5da7
* Version Independent ID: 057dd7ac-8383-1650-ceb5-cbea3995180c
* Content: [navigateTo (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment] 2020-10-15 18:22
Duplicate of  #1576.  Closing the issue here. Please follow the other issue for updates.

**Closed by Nkrb** 2020-10-15 18:22 UTC
Labels: assigned-to-author, client-api
