### ISSUE TITLE
Package Deployer lifecycle

### ISSUE THREAD

**Issue by Finickyflame** [MicrosoftDocs/powerapps-docs#784] opened 2019-11-12 23:16 UTC
There're some details missing regarding the lifecycle of the package deployer and how it can be integrated in a continuous delivery workflow by limiting manual activities.
 
1. Do you have to create a new Package Deployer for each release?
2. Do you keep the same project and edit it for each patch?
3. Can you keep this project in a source control (Git) and reference it in your deployment definition?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b0e3a7-a385-942e-1261-53d1aeac1673
* Version Independent ID: 95ad8dd4-3458-8fb2-9e1f-8780fea5853a
* Content: [Create packages for the Package Deployer (Common Data Service) - PowerApps](https://docs.microsoft.com/en-ca/powerapps/developer/common-data-service/package-deployer/create-packages-package-deployer)
* Content Source: [powerapps-docs/developer/common-data-service/package-deployer/create-packages-package-deployer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/package-deployer/create-packages-package-deployer.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-07-02 01:13
@Finickyflame Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 01:13 UTC
Labels: open-for-too-long
