### ISSUE TITLE
Can you please update the document to specify whether File Columns are supported or not

### ISSUE THREAD

**Issue by StevenRasmussen** [MicrosoftDocs/powerapps-docs#3705] opened 2022-09-30 20:36 UTC
I'm looking to understand if File Columns are supported in PCF controls.  This would be good to have in the documentation.  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3b2e635-6c60-0efc-d894-e43216dca90e
* Version Independent ID: 9828125d-c061-465e-d486-b4ea609190e1
* Content: [Property Element - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/manifest-schema-reference/property)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/property.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/manifest-schema-reference/property.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @noazarur-microsoft
* Microsoft Alias: **noazarur**

**Comment by bishalgoswami** [comment] 2022-09-30 21:00
Thanks for your comment, @StevenRasmussen. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment] 2022-09-30 21:53
@StevenRasmussen 
Thanks for your feedback.

@noazarur-microsoft  

In the Remarks for this topic we have a list of `of-type` properties that are supported.

We also have a table with a list of `of-type`  [Value elements that are not supported](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/manifest-schema-reference/property#value-elements-that-are-not-supported)

But File is not in either list. Neither is Image.

Can you provide information to update these lists?

**Comment by JimDaly** [comment] 2022-12-15 22:32
@kaushikkaul 

I added a note saying:

> [!NOTE]
> At this time File columns are not supported. More information: [File columns](../../../../maker/data-platform/types-of-fields.md#file-columns)

But it still doesn't mention image columns.

**Comment by JimDaly** [comment] 2023-08-21 20:47
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by JimDaly** 2023-08-21 20:47 UTC
Labels: assigned-to-author, Component-framework
