### ISSUE TITLE
How to use filters?

### ISSUE THREAD

**Issue by imranakram** [MicrosoftDocs/powerapps-docs#1456] opened 2020-05-27 10:12 UTC
I have reached a hair pulling point with applying filters basically. Here's how I'm setting up filterXml. Nothing seems to be having any effect on the view. I have tried with a specific view and without. With `entityLogicalName` and without also. This is onprem v9.0. This is in using web client legacy UI. Any tips or suggestions?
```
lookupOptions = {
  entityTypes: ["account"],
  defaultEntityType: ["account"],
  allowMultiSelect: false,
  viewIds: ["{xxxxxxx-xxxx-xxxx-xxxx-xxxxxxx}"],
};
lookupOptions.filters = [
  {
    entityLogicalName: 'account',
    filterXml:
      '<filter type="and"><condition attribute="statecode" operator="eq" value="0" /><condition attribute="xxxxx_id" operator="eq" value="' +
      result.xyzz +
      '" /></filter>',
  },
];
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ec38d57-dbf5-8547-fe4d-2f05351f728e
* Version Independent ID: 474145c5-988a-2422-343c-ecea727c4404
* Content: [lookupObjects (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/lookupObjects.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by RedsGT** [comment] 2020-05-27 22:16
@imranakram You're probably better off posting over on the community forums at [https://community.dynamics.com/crm](https://community.dynamics.com/crm) .  Power users and MS Support monitors them.

**Comment by Nkrb** [comment] 2020-11-11 18:53
@imranakram Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 18:53 UTC
Labels: assigned-to-author, client-api
