### ISSUE TITLE
Incorrect return type

### ISSUE THREAD

**Issue by BetimBeja** [MicrosoftDocs/powerapps-docs#1738] opened 2020-09-13 19:34 UTC
The documentation states that:

Name | Type | Required | Description
-- | -- | -- | --
successCallback | Function | No | A function to call when a record is created. An object with the following properties will be passed to identify the new record:<ul><li>entityType: String. The entity logical name of the new record.</li><li>id: String. GUID of the new record.</li></ul>

but then it states that return value for the function call is [Promise&lt;Entityreference&gt;](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/entityreference) which is different than the successCallback definition.

The actual call to the function in an online instance (version 9.1.0000.22242) returns the value described in the successCallback.

But the sample component [TS_WebAPI](https://github.com/microsoft/PowerApps-Samples/tree/68bf0cb97baa9784c57ae721bf47c27efcc34e9d/component-framework/TS_WebAPI) and the [powerapps-component-framework](https://www.npmjs.com/package/@types/powerapps-component-framework) typings use the Promise&lt;EntityReference&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d976623-48b2-06bb-f661-48c96c5f93fd
* Version Independent ID: 511dec41-fd89-5007-0467-c7f213fd2ea6
* Content: [createRecord - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/webapi/createrecord)
* Content Source: [powerapps-docs/developer/component-framework/reference/webapi/createrecord.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/webapi/createrecord.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2020-11-11 19:26
@BetimBeja Thanks for contacting us. We have created a internal work item for the respective dev team to update the return type. Will update the docs when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 19:26 UTC
Labels: Component-framework, assigned-to-author
