### ISSUE TITLE
PowerShell script incorrect

### ISSUE THREAD

**Issue by orangetoken** [MicrosoftDocs/powerapps-docs#648] opened 2019-09-19 10:56 UTC
The PS script shown above misses the first line:
function New-PowerAppsCheckerAzureADApplication

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e92c215-b337-b864-3fee-b9542e4e30c8
* Version Independent ID: 8f26538c-5863-6746-8c2c-ee4438165da4
* Content: [Build tools tasks - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tasks)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-tasks.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment] 2022-07-02 00:58
@orangetoken Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:58 UTC
Labels: open-for-too-long
