### ISSUE TITLE
Build Task support for YAML

### ISSUE THREAD

**Issue by DavidLHannah** [MicrosoftDocs/powerapps-docs#956] opened 2020-01-18 02:45 UTC
The YAML Task Assistant interface in Azure DevOps allows you to select the PowerApp Build Tools. However, it looks like those tasks will not actually run when you trigger the pipeline. As per the docs @ https://github.com/microsoft/PowerApps-Samples/tree/master/azure/build-tools , recreating the same build process with the Classic editor seems to run fine.

Can we call this out in the docs, as YAML is now the default pipeline interface is Azure DevOps? Or do we have a timeline for YAML support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e92c215-b337-b864-3fee-b9542e4e30c8
* Version Independent ID: 8f26538c-5863-6746-8c2c-ee4438165da4
* Content: [Build tools tasks - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tasks)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-tasks.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by kkanakas** [comment] 2022-07-17 20:38
@DavidLHannah Did you check the latest Power Platform Build tools task. Your comment on this matter is from nearly 2 years ago. 

Cc: @mikkelsen2000

**Comment by phecke** [comment] 2022-07-26 00:06
@DavidLHannah Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-26 00:06 UTC
Labels: assigned-to-author

**Comment by DavidLHannah** [comment] 2024-03-29 04:12
> @DavidLHannah Did you check the latest Power Platform Build tools task. Your comment on this matter is from nearly 2 years ago. 
> 
> Cc: @mikkelsen2000 

Yes, the latest tools solve this issue. Thanks!
