### ISSUE TITLE
MSCRM.SuppressDuplicateDetection supported other than CREATE/UPDATE web api request?

### ISSUE THREAD

**Issue by arunvinoth** [MicrosoftDocs/powerapps-docs#2166] opened 2021-03-03 19:25 UTC
Pls update the documentation, if this works differently for **QualifyLead** compared to CREATE and UPDATE request.

Originated from: https://stackoverflow.com/q/66389963/7920473
Reference: https://blog.magnetismsolutions.com/blog/isaacnichols/2019/07/22/using-the-qualify-lead-action-in-dynamics-365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a48217ac-43b9-cefb-70bf-163c82175080
* Version Independent ID: 70af49c3-2b41-bbde-235c-d348b2f47a2d
* Content: [Detect duplicate data using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/manage-duplicate-detection-create-update)
* Content Source: [powerapps-docs/developer/data-platform/webapi/manage-duplicate-detection-create-update.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/webapi/manage-duplicate-detection-create-update.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment] 2022-05-24 23:42
@arunvinoth 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-05-24 23:42 UTC
Labels: assigned-to-author, open-for-too-long
