### ISSUE TITLE
allowMultipleFiles does not let you pick multiple files via mobile apps

### ISSUE THREAD

**Issue by james-reinhardt** [MicrosoftDocs/powerapps-docs#1882] opened 2020-11-03 20:41 UTC
Similar to earlier issue.
Have implemented pickFile with allowMultipleFiles set to true. In browser am able to select multiple files. In mobile I am restricted to one file (Android 11). Have confirmed with other tablets and a few iphones.

I believe the mobile app(s) are not respecting the allowMultipleFiles flag.

I tested the following and was unable to upload multiple files from my android phone apps. All of these items allow for selection of multiple files in the web app.
1.	Custom ribbon button
3.	A custom control that allows ‘multiple file uploads.
4.	Adding email attachments
5.	Uploading documents to the sharepoint library from within a record

I also tried the ‘Power Apps Mobile’ app with the same result on the email attachment test. The 'Field Service Mobile (Dynamics 365) App' is also impacted.

**Comment by Nkrb** [comment] 2020-11-11 18:44
@james-reinhardt Thanks for contacting us. We have created a internal work item for the respective feature team. Will update the docs if required when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 18:44 UTC
Labels: client-api

**Comment by james-reinhardt** [comment] 2020-11-30 18:50
@Nkrb Would you be able to provide any detail on if/when this might be addressed?
We have a client and one of their original requirements was the ability to upload multiple photos. Thank you very much.

**Comment by RawPork01** [comment] 2023-12-13 06:57
Hello @james-reinhardt @Nkrb.
Is there any update on this topic? It would be a huge improvement for our clients app.
