### ISSUE TITLE
Preparing package on a non windows os

### ISSUE THREAD

**Issue by bshimrit** [MicrosoftDocs/powerapps-docs#1528] opened 2020-06-21 05:02 UTC
I've prepared my package on mac os which caused the submission to fail multiple time due to some mac os hidden files. couldn't resolve it till I got a support call from microsoft (which mentioned it happens to a lot of partners...)

You should show a disclaimer on step3 that the package MUST be prepared on windows os.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2af3070-30b8-395e-ea51-86e954e3b006
* Version Independent ID: c1e95af9-6261-7da1-07ce-1b8986ef3738
* Content: [Step 3: Create an AppSource package for your app (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-package-app-appsource)
* Content Source: [powerapps-docs/developer/common-data-service/create-package-app-appsource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/create-package-app-appsource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by phecke** [comment] 2020-10-01 01:36
@bshimrit  Thanks for mentioning this. Do you happen to know if the submission works for a package compressed on a Linux computer?

**Comment by phecke** [comment] 2021-11-02 01:03
@bshimrit 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 01:03 UTC
Labels: assigned-to-author, open-for-too-long
