### ISSUE TITLE
Documentation for editing CSS out of date

### ISSUE THREAD

**Issue by jdivis** [MicrosoftDocs/powerapps-docs#3568] opened 2022-08-12 15:46 UTC
It seems like this documentation might be out of date, as I don't have a palette on the left hand side of the screen, and see a "themes" drop down instead in the top menu bar while editing the app. It is not apparent where I can go to edit the css of the app though.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bc12134-33e6-ef48-6b2a-d832f3c7872f
* Version Independent ID: 7f4534e1-4742-2b7d-c2c2-160f9b8cf846
* Content: [Edit CSS for themes - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/edit-css#customize-bootstrap)
* Content Source: [powerapps-docs/maker/portals/edit-css.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/edit-css.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**

**Comment by bishalgoswami** [comment] 2022-08-12 17:00
Thanks for your comment, @jdivis. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment] 2022-08-12 20:51
Can you provide a screen shot of what you are seeing?

**Comment by nickdoelman** [comment] 2022-10-05 12:50
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by nickdoelman** 2022-10-05 12:50 UTC
Labels: assigned-to-author
