### ISSUE TITLE
Example of how to use relationship object 

### ISSUE THREAD

**Issue by vaibhav21791** [MicrosoftDocs/powerapps-docs#690] opened 2019-10-04 11:46 UTC
Tried several ways to understand what is the use of relationship object. But it did not work for me. 
An example of this would be good to understand it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b204ee0a-69a2-e52d-f110-2291be66c1af
* Version Independent ID: 8ac980df-6b5f-2b33-707f-11efb597ba6a
* Content: [openForm (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by debajdu** [comment] 2020-04-21 05:10
Same here. I am getting this question every now and then I really could not understand how the relationship parameter works. Don't know whether my assumption is right but I think this is used in  combination with createFromEntity parameter.

Request to please put an example of make the documentation with more explanation to understand better. Will wait for it.

Cheers!
Debajit

**Comment by Nkrb** [comment] 2020-10-15 16:33
Duplicate of # https://github.com/MicrosoftDocs/powerapps-docs/issues/1576. Closing the issue here. Please follow the other issue for updates.

**Closed by Nkrb** 2020-10-15 16:33 UTC
Labels: assigned-to-author, client-api
