### ISSUE TITLE
FetchXML Paging Cookie

### ISSUE THREAD

**Issue by skoofy5** [MicrosoftDocs/powerapps-docs#400] opened 2019-05-20 23:39 UTC
The webapi doesn't return a paging cookie when using a FetchXML query. Will this be released in future developments? It would be helpful as a lot of queries used fetch with the XrmServiceToolkit in the past.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a077afea-0218-d8e3-6112-95ea4bb04501
* Version Independent ID: 00ba7831-fe82-4f86-2864-311a7b8375b9
* Content: [Query Data using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/query-data-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/query-data-web-api.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2021-06-17 01:08
@skoofy5

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-06-17 01:08 UTC
Labels: open-for-too-long
