### ISSUE TITLE
Restricted Entities 

### ISSUE THREAD

**Issue by stunc20** [MicrosoftDocs/powerapps-docs#1221] opened 2020-04-02 14:58 UTC
Hello,
In the licensing guide is written that restricted entities cannot be used with Power Apps licenses, but the licensing guide does not link a list of these restricted entities. 
So my question: Which entities may not be used with a Power Apps license?

**Comment by iangpgh** [comment] 2020-04-07 19:39
@stunc20 In the Power Apps licensing guide, at the bottom of page 20, there is a link to the list of restricted entities, in this article: [Restricted entities requiring Dynamics 365 license](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities).

**Comment by bthompson-365** [comment] 2020-04-07 19:48
But that link is a self referential link that takes you back to this page which although slightly updated (the warning that the list is out of date was removed by the last update) contains the same list of restricted entities as it was when it was first created back in March 2018.

Now I know there are a set of restricted entities within Dynamics 365 for Sales (Product, Lead and as a minimum the quote / sales pricing mechanisms are restricted) but the current published list of restricted entities does not mention them, nor state that the list is incomplete and subject to change.

**Comment by iangpgh** [comment] 2020-04-15 18:40
@stunc20 Correction: the list of restricted entities was not updated in this article. We are working on updating these soon.

**Comment by Mattp123** [comment] 2021-07-28 23:07
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 23:07 UTC
Labels: assigned-to-author, open-for-too-long
