### ISSUE TITLE
Only one action is shown.

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#1224] opened 2020-04-02 22:41 UTC
This documentation should explain that, while the Actions attribute (the outer one) is an array, the UCI will only display the first action specified in the array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 237cc665-0041-6374-bd81-56dcad94926f
* Version Independent ID: cfddf72f-0ee5-df62-3c29-3e8af4e6b26c
* Content: [addNotification (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/addnotification)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addNotification.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/addNotification.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment] 2020-11-11 18:54
@devlinl Thanks for contacting us. We have created a internal work item for the respective dev team to investigate if it should show all the actions. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 18:54 UTC
Labels: assigned-to-author, client-api
