### ISSUE TITLE
formContext.data.process.setStatus() callback executed before status has been changed

### ISSUE THREAD

**Issue by Emino273** [MicrosoftDocs/powerapps-docs#2170] opened 2021-03-05 11:38 UTC
When **formContext.data.process.setStatus(status, callbackFunction)** is called it returns undefined and the callback function is executed before the status is changed.

To overcome this problem we have followed two different ways:

1. setInterval

`formContext.data.process.setStatus("active");`

`var activeStage = setInterval(function () {
if (Xrm.Page.data.process.getStatus() === "active")
 {functionToBeCalledInAsCallback();
clearInterval(activeStage);}}, 100);`

2. formContext.data.refresh(true)

 `formContext.data.refresh(true) and then call  functionToBeCalledInAsCallback()`

**Comment by JimDaly** [comment] 2023-01-06 21:17
RE: [formContext.data.process.setStatus](https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-data-process/instance/setstatus)

**Comment by JimDaly** [comment] 2023-01-07 00:34
I understand this is a known issue. Looking for confirmation before closing.

**Comment by JimDaly** [comment] 2023-08-10 23:26
“Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue."

**Closed by JimDaly** 2023-08-10 23:26 UTC
Labels: assigned-to-author, client-api
