### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gable44** [MicrosoftDocs/powerapps-docs#1917] opened 2020-11-12 09:00 UTC
The Relationship actions link is broken. (404)
https://docs.microsoft.com/en-us/maker/common-data-service/create-edit-entity-relationships.md#actions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca50c028-2766-15ce-af7e-ebe083499458
* Version Independent ID: e36454bb-1ca3-f949-aa17-61bc14ceb5b8
* Content: [Table relationships in Project Oakdale - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/relationships-table)
* Content Source: [powerapps-docs/teams/relationships-table.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/teams/relationships-table.md)
* Service: **powerapps**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by NHelgren** [comment] 2020-11-12 16:36
It looks like this is one of the items that is pointing away towards CDS Maker content. We need to either:

Make a duplicate of this document for Oakdale (and just change the references to CDS) and then link to Actions https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-edit-entity-relationships.md

or 

Link to https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-edit-entity-relationships.md#actions

Let me know which you prefer.

**Comment by gable44** [comment] 2020-11-18 12:55
The second one. :)

**Comment by KumarVivek** [comment] 2020-11-18 16:38
@gable44 This is fixed now; thanks for reporting it.

**Comment by NHelgren** [comment] 2020-11-18 16:39
Excellent thanks!

**Closed by KumarVivek** 2020-11-18 16:38 UTC
Labels: assigned-to-author
