### ISSUE TITLE
Application User Form Change and Javascript Errors

### ISSUE THREAD

**Issue by iflyadesk** [MicrosoftDocs/powerapps-docs#694] opened 2019-10-07 02:29 UTC
The Application User Form now has `First Name` and `Last Name` instead of `Full Name` like the pictures (and instructions) above. Every combination I have thought of to try results in the form throwing Javascript errors.  Please help quickly as I really need to get an application user operational ASAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0f87a0a-9dd9-5188-7347-d910423902ca
* Version Independent ID: 9f532b04-f9c5-cbdd-a2bd-666b55ee942e
* Content: [Use Single-Tenant server-to-server authentication (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-single-tenant-server-server-authentication)
* Content Source: [powerapps-docs/developer/common-data-service/use-single-tenant-server-server-authentication.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-single-tenant-server-server-authentication.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-07-02 01:00
@iflyadesk Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 01:00 UTC
Labels: open-for-too-long
