### ISSUE TITLE
SQL Error - Specified Cast is not valid (Object Explorer)

### ISSUE THREAD

**Issue by Sudheerreddyn14** [MicrosoftDocs/powerapps-docs#1429] opened 2020-05-21 03:14 UTC
I could connect to the server using SSMS, but while expanding the Databases I was getting this error "Specified Cast is not valid (Object Explorer)".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60540f3d-b959-2daa-23a1-2938de01919d
* Version Independent ID: 07b12c3a-a0db-47f1-1aca-04008c9efca9
* Content: [Use SQL to query data (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/cds-sql-query.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/cds-sql-query.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **pehecke**

**Comment by Sudheerreddyn14** [comment] 2020-05-21 03:16
![image](https://user-images.githubusercontent.com/37790033/82519555-97c90500-9b3f-11ea-98aa-059da1aa55f2.png)


![image](https://user-images.githubusercontent.com/37790033/82519458-5fc1c200-9b3f-11ea-8ebc-8359d1b6b367.png)

**Comment by mayadumesh** [comment] 2020-05-21 22:31
we are looking into it, but have no updates at the moment.

**Comment by phecke** [comment] 2021-11-02 01:29
@Sudheerreddyn14 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 01:29 UTC
Labels: assigned-to-author, open-for-too-long
