### ISSUE TITLE
RetrieveFormattedImportJobResults doesn't work for ImportTranslation import jobs

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#948] opened 2020-01-14 17:56 UTC
Please see where this was reported for the on-premises docs:
https://github.com/MicrosoftDocs/dynamics-365-customer-engagement/issues/1541

Also, the on-premises topic should be redirected to this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c794ba37-6ca5-4b7a-9fc8-0794141a72bd
* Version Independent ID: 17df57b6-e28c-c863-67a0-557343b9ef05
* Content: [Customize labels to support multiple languages (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/customize-labels-support-multiple-languages)
* Content Source: [powerapps-docs/developer/common-data-service/customize-labels-support-multiple-languages.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/customize-labels-support-multiple-languages.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2023-01-21 00:24
@JimDaly Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2023-01-21 00:24 UTC
Labels: assigned-to-author
