### ISSUE TITLE
Import name missing for `DataSet` type

### ISSUE THREAD

**Issue by zeusttu** [MicrosoftDocs/powerapps-docs#2640] opened 2021-08-16 13:18 UTC
When looking at the reference documentation for the `DataSet` type, I see a lot of details, but it does not tell me how the type can be imported when using the PCF TypeScript bindings. An inspection of the code in `node_modules/@types/powerapps-component-framework/componentframework.d.ts` combined with looking at some other imports in the scaffolded code eventually helped me deduce that the following line of code was going to do the job:

```typescript
import DataSet = ComponentFramework.PropertyTypes.DataSet;
```

However, the process of figuring this out was far from intuitive, and probably still is for many other people.

#### Why do I (and presumably others as well) want to reference this type in code?

I need to declare some TypeScript properties of this type. In the code itself, this type can often be inferred from a property's initial value. In unit tests however (especially for a PCF code component's `updateView` method), I often have to explicitly declare a property as being of this type, which requires me to know how to import it.

#### You found your answer, can you submit a PR for this issue yourself?

I can! But it would be scoped to this specific type, while the same information seems to be lacking for other types as well (although I only checked for one other type). Also, I would have to introduce a new section for this, and I would likely give it a name and placement which may be inconsistent with your documentation guidelines (which I am unfamiliar with). Finally, I have not signed the Microsoft contributor agreement or whatever it's called, which may or may not be a prerequisite to having documentation commits accepted. So all things considered, I doubt I would save you any time by doing it myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58cd0e85-e5b8-c347-09b7-9e8fb597975f
* Version Independent ID: 0d28e089-a794-ed0e-cb63-e0cafc31cccf
* Content: [DataSet in Microsoft Dataverse - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/dataset)
* Content Source: [powerapps-docs/developer/component-framework/reference/dataset.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/reference/dataset.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2021-08-19 21:18
@zeusttu Thanks for reaching to us. Can you write up what you want to add in the docs. We will verify from our side and will add it to docs.

**Comment by zeusttu** [comment] 2021-08-20 15:12
Probably something like:

> # Import type in TypeScript
> ```typescript
> import DataSet = ComponentFramework.PropertyTypes.DataSet;
> ```

**Comment by JimDaly** [comment] 2022-10-10 16:49
I reached out to @noazarur-microsoft about this via email.

**Comment by JimDaly** [comment] 2023-08-10 23:40
“Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue."

**Closed by JimDaly** 2023-08-10 23:40 UTC
Labels: assigned-to-author, Component-framework
