### ISSUE TITLE
Unable  Common Data Service endpoint SQL connection with SSMS

### ISSUE THREAD

**Issue by kvrs09** [MicrosoftDocs/powerapps-docs#1370] opened 2020-05-11 19:49 UTC
Hi Team 
Trying toe Common Data Service endpoint SQL connection with SSMS . But getting network related errors. North America region.

TITLE: Connect to Server
------------------------------

Cannot connect to wwlpbdcrm.crm.dynamics.com,5558.

------------------------------
ADDITIONAL INFORMATION:

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.) (Microsoft SQL Server, Error: 10060)

For help, click: http://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&EvtSrc=MSSQLServer&EvtID=10060&LinkId=20476

------------------------------

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

------------------------------
BUTTONS:

OK
------------------------------

![image](https://user-images.githubusercontent.com/49271891/81604874-71f47100-9385-11ea-9e1a-9d63fb710a86.png)

**Comment by phecke** [comment] 2021-11-02 01:37
@kvrs09 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 01:37 UTC
Labels: assigned-to-author, open-for-too-long
