### ISSUE TITLE
Launch MS Teams from PowerApps canvas application 

### ISSUE THREAD

**Issue by jafar-pa** [MicrosoftDocs/powerapps-docs#1469] opened 2020-06-02 10:14 UTC
Hello,

I was doing an experiment with "Launch" function inside powerapps canvas application(this application is embedded with MS Team) , on button click event, based on the desired team passed as param, it will navigate to the desired team tab with in the Microsoft teams client app
I tried this way:
use Launch(<link to the team>) 

Any guidance on how to layer this in would be appreciated.

Regards
Jafar

**Comment by Nkrb** [comment] 2021-07-21 19:30
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Nkrb** 2021-07-21 19:30 UTC
Labels: CanvasApp, assigned-to-author, open-for-too-long, waiting-on-internal-feedback
