### ISSUE TITLE
My take on this

### ISSUE THREAD

**Issue by YoYoFreakCJ** [MicrosoftDocs/powerapps-docs#931] opened 2020-01-10 06:57 UTC
1. Even mobile devices have absolutely no problem to load, unload and cache large amounts of assemblies for various applications. Saying that there's a noticable impact on performance for D365 feels very outdated to me, even for instances on premise with limited hardware. Please do correct me if I'm wrong.
I have taken care of many different organizations, and for each one I have created an assembly for each purpose it's supposed to serve. I had up to 20 different plugin and CWA assemblies on a single organization. Then I was confronted with an organization which was handled by a third party who followed the single assembly guideline, their assembly took about 12MB in size. To this day we're having trouble with this single assembly. Never before have I encountered performance issues like this. Every action that triggers logic from this monster of an assembly takes a couple seconds longer than it has any right to. So from my experience, having a single large assembly makes performances worse.
If we really REALLY wanted to improve performance we'd take a look at .NET Native. That has been around since VS2015 yet we still have to compile all our plugins to IL.

2. More complex ALM? Isn't this article supposed to talk about D365 related things? If I don't know how to handle ALM with a ton of business logic now I won't know any better after reading this.
Here's a better approach: create assemblies as you see fit, but have them reuse code. This can be achieved by sticking every class library project into the same Visual Studio solution, and reusing code between them by using Shared Projects. Keep an eye on maintainability right from the start. Separation of concerns is where it's at.
When I develop a plugin the business logic and domain model are always in separate Shared Projects which do not even have to know that they're being called by a plugin. The plugin projects then contain code that's only related to the plugin side of things, like deciding where to get values from (image/input parameters/...) and deciding how to save values (execute an update/write to input parameters/...). All of this depends on the plugin registration like the message, the entity, the stage, whether it's sync/async, the images that are registered, the filtered attributes if any, etc. All these class library projects have to do with business logic is call it, but other than that their focus is on handling the plugin side of things.
Here's a bonus: sticking all class library projects in the same VS solution may create huge VS solutions, but thanks to filtered solutions introduced in VS2019 it's a breeze to work with it. https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019

In terms of deployment it's also better to use multiple assemblies packaged in their own CRM solution, one for each purpose. That way you have a single solution for a single purpose, as opposed to a single solution for all purposes. This allows you to reuse your functionality for other organizations and your deployments will take shorter (solutions with large assemblies and lots of items like plugin steps take longer to import). It's also easier to see which functionality is present in an organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 534be660-d37a-3142-f2ba-1ecfd6fb5c46
* Version Independent ID: 8097fd31-f16e-d156-45e9-cb3d2817dedf
* Content: [Optimize custom assembly development - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/best-practices/business-logic/optimize-assembly-development#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/best-practices/business-logic/optimize-assembly-development.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/best-practices/business-logic/optimize-assembly-development.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by phecke** [comment] 2022-07-02 02:13
@YoYoFreakCJ Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2022-07-02 02:13 UTC
Labels: open-for-too-long
