### ISSUE TITLE
Inconsistent to Licensing Guide

### ISSUE THREAD

**Issue by paul-way** [MicrosoftDocs/powerapps-docs#1284] opened 2020-04-21 21:50 UTC
Comparing this to the official licensing guide, there are inconsistencies.
https://go.microsoft.com/fwlink/p/?linkid=2085130

For example, the "Complex Entities" are included in the Power Apps per App & per User plans (pages 4 & 5).  Another example is that restricted entities are read-only within the Power Apps license; however, the examples do not distinguish between Read and full CRUD operations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40ad49cf-a978-52df-5c25-5114867c76b2
* Version Independent ID: c8fa37c7-42f9-1aaa-0f78-f63cf289cbd7
* Content: [License requirements for entities - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-entity-licenses#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-entity-licenses.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-entity-licenses.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Mattp123** [comment] 2021-07-28 23:10
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 23:10 UTC
Labels: assigned-to-author, open-for-too-long
