### ISSUE TITLE
What about Power BI integrations

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerapps-docs#2793] opened 2021-10-11 14:07 UTC
Hi, this documentation doesn't address Power BI integrations. There's two integrations that comes in mind: 
1) Embedding a Power Apps app within a Power BI report and embedding the Power BI report within Teams. 
2) Power BI accessing data in DataVerse

Please address also this situations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bffcc4d8-a8f0-83fe-3003-e9f9fcedadbd
* Version Independent ID: 6f4f89a2-fbc8-a2de-f16c-68e3dec4fa8e
* Content: [Microsoft Dataverse for Teams overview - Power Apps](https://docs.microsoft.com/en-us/powerapps/teams/overview-data-platform)
* Content Source: [powerapps-docs/teams/overview-data-platform.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/teams/overview-data-platform.md)
* Service: **powerapps**
* Sub-service: **teams**
* GitHub Login: @NHelgren
* Microsoft Alias: **nhelgren**

**Comment by Mattp123** [comment] 2023-01-12 16:26
@erapade - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, reopen or create a new issue.

**Closed by Mattp123** 2023-01-12 16:26 UTC
Labels: assigned-to-author, waiting-on-internal-feedback
