### ISSUE TITLE
Navigate with variable screen parameter

### ISSUE THREAD

**Issue by jjkinsey** [MicrosoftDocs/powerapps-docs#2027] opened 2021-01-05 17:16 UTC
While Navigate will accept a variable screen argument and perform the expected behavior of navigating to the screen value of the variable, unexpected behavior occurs when a context update record is provided: the screen being navigated to will not correctly update its context variables. Using multiple Navigate function calls inside a Switch statement or similar, where the screen value is hard-coded in each branch, performs the expected behavior (correct context variable updating).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9b5e7f-c7a3-4530-11dc-d3655e0c77d4
* Version Independent ID: 10b605d6-f30a-aef9-c69a-ebc267089fd2
* Content: [Back and Navigate functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-navigate)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-navigate.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-navigate.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment] 2021-08-03 20:56
Thanks for contacting us. We have identified this as a product bug. We have created a work item for the respective dev team. Will update the docs  when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2021-08-03 20:56 UTC
Labels: CanvasApp, assigned-to-author, product-bug
