### ISSUE TITLE
Save errorCallback missing error code list

### ISSUE THREAD

**Issue by clurdish** [MicrosoftDocs/powerapps-docs#976] opened 2020-01-29 17:36 UTC
The errorCallback specifies that it will return some errorCode on callback. To gracefully handle certain error codes, a list of possible error codes that can be returned and their descriptions should be included as a section in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d00568ac-9426-75f7-1662-7e6083f31c64
* Version Independent ID: 491a98a2-f216-8c6e-75fb-a8a64452c9ff
* Content: [save (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data/save)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/save.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/save.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by KendalBond007** [comment] 2023-08-10 22:25
@JimDaly 
I'm doing an Issues backlog clean up effort. Since you assigned this within the last year: is there a reason it should be kept open? If so, is MenantGaur a good contact? Any input is appreciated.

**Comment by JimDaly** [comment] 2023-08-10 23:21
“Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue."

**Closed by JimDaly** 2023-08-10 23:21 UTC
Labels: assigned-to-author, client-api
