### ISSUE TITLE
No description of handling keys in mapping

### ISSUE THREAD

**Issue by mikkelpkaas** [MicrosoftDocs/powerapps-docs#1344] opened 2020-05-06 14:01 UTC
There's no description of how you map a field to a key field on the target record in CDS. If I e.g. wants to map data to account, how do I chose which field is to be used as the primary key for the flow? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3abf73d-60b9-675f-61e7-1c2dc622d055
* Version Independent ID: 352c1196-0631-9f40-e382-bba13d5e27e9
* Content: [Create and use dataflows in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-and-use-dataflows#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/create-and-use-dataflows.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-and-use-dataflows.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment] 2021-07-28 23:10
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 23:10 UTC
Labels: assigned-to-author, open-for-too-long, waiting-on-internal-feedback
