### ISSUE TITLE
Broken link and statement mismatch in ja-jp

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/powerapps-docs#866] opened 2019-12-13 04:23 UTC
The following statement tells you can download the project from ここ(here). Although, this hyper link of ここ(here) is inactive and this statement is different from the original text. Should fix like this.

https://docs.microsoft.com/ja-jp/powerapps/developer/common-data-service/xrm-tooling/sample-quick-start-xrm-tooling-api

サンプルを実行する方法
1. ここ からサンプルをダウンロードして展開します。
>> [The issue statement] Download the sample from "here" and expand.

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/xrm-tooling/sample-quick-start-xrm-tooling-api#feedback

How to run the sample
1．Download and extract the sample so that you have a copy locally.
>> サンプルをダウンロードしローカルに展開してください。

**Comment by phecke** [comment] 2022-07-02 02:09
@ghost Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2022-07-02 02:09 UTC
Labels: open-for-too-long
