### ISSUE TITLE
List of WebAPI limitations in 9.x ?

### ISSUE THREAD

**Issue by DanielBruckhaus** [MicrosoftDocs/powerapps-docs#129] opened 2018-11-28 22:32 UTC
Quote: 
"The Web API allows you to do all the same operations as the organization service but presents them in an RESTful style."
Quote 2:
"The Common Data Service for Apps Web API provides complete parity with the capabilities of the organization service."

This still doesn't appear to be true in 9.1, however, there also doesn't appear to be an up-to-date list of these limitations.
(There is a link to a list of limitations for CRM 2016, but that's a link to the legacy 8.x docs)

In particular, the RetrieveAuditDetails Function is available via the WebApi, but it only exposed the AuditDetail complex type, and not the AttributeAuditDetail type, which would include the NewValue and OldValue properties required to access the actual Pre-/Post-Values of the record.
Is this a known limitation? When will it be fixed?

Thanks and warm regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227fd50c-3385-52c1-a57d-08dca61d36c4
* Version Independent ID: 3d616dde-59fa-4ab0-14e0-0ddbf972fe64
* Content: [Use the Common Data Service for Apps Web API (Common Data Service for Apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/overview)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/overview.md)
* Service: **crm-online**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment] 2019-05-14 11:03
@DanielBruckhaus Do you mean there is no **AttributeAuditDetail ComplexType** and if the feature team has a plan on introducing it ?

**Comment by tssvitaly** [comment] 2020-03-27 14:14
Is it fixed?   
I would like to get "new" and "old value" through  API.
I'm using PowerBI to pull the the data  quering the data from  https://******/api/data/v9.1/

**Comment by John-Bosch** [comment] 2020-12-23 22:55
I assume this has still not been fixed? This is causing me massive headaches in having to keep my audit monitoring and archiving azure functions as V1 functions as they have to continue use the CRM SDK rather than the Web API. Every other azure function I have has been migrated to V3 functions and uses the CRM Web API.

**Comment by phecke** [comment] 2021-06-17 00:35
@DanielBruckhaus 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-06-17 00:35 UTC
Labels: 01dev, assigned-to-author, waiting-on-internal-feedback
