### ISSUE TITLE
Dev Blog URL not working

### ISSUE THREAD

**Issue by pavansarma93** [MicrosoftDocs/powerapps-docs#2382] opened 2021-05-16 10:47 UTC
The Dev blog which was referred at text **CRM Team Blog: Thread Safety in Plug-ins** with url [https://blogs.msdn.com/b/crm/archive/2008/11/18/member-static-variable-and-thread-safety-in-plug-in-for-crm-4-0.aspx](url)

Is no longer working. Please get it updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46aca615-520e-aa4d-22a4-62a7c3c18db8
* Version Independent ID: b812c8cf-a8d4-153d-5e81-c4b83e14d637
* Content: [Develop IPlugin implementations as stateless - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless)
* Content Source: [powerapps-docs/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/best-practices/business-logic/develop-iplugin-implementations-stateless.md)
* Service: **powerapps**
* GitHub Login: @jowells
* Microsoft Alias: **jowells**

**Comment by phecke** [comment] 2022-05-24 22:21
@pavansarma93 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-05-24 22:21 UTC
Labels: assigned-to-author, open-for-too-long
