### ISSUE TITLE
Need to add a section on assigning records

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1245] opened 2020-04-10 19:51 UTC
This appears to be a common area of confusion.
See the notes  here https://github.com/simple-odata-client/Simple.OData.Client/issues/625

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08356781-8ff5-8696-0072-89fb392acc7a
* Version Independent ID: 80f74dc0-cb69-3ee7-0990-fc656e1c66ed
* Content: [Update and delete entities using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/update-delete-entities-using-web-api#basic-update)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/update-delete-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/update-delete-entities-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2021-11-11 02:48
@JimDaly 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-11 02:48 UTC
Labels: assigned-to-author, open-for-too-long
