### ISSUE TITLE
"<property>@odata.bind": null is ignored

### ISSUE THREAD

**Issue by JandosHk** [MicrosoftDocs/powerapps-docs#4268] opened 2023-04-05 00:23 UTC
The documentation says:

> If you want to disassociate, you can simply set the value to null...
> When disassociating in this manner, **you don't need to include the @odata.bind annotation**.

My experience shows if @odata.bind is included in the property name, then Web API just ignores it, and no disassociation happens.
Only property name without @odata.bind worked. So the documentation should say: **you shouldn't include the @odata.bind annotation**. Or maybe, it is because of bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce0b1cd-e7ce-a9b8-6b51-37be0a4dd848
* Version Independent ID: 54eecc75-29fe-29ba-94c9-0ad0b8694d69
* Content: [Associate and disassociate table rows using the Web API (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/associate-disassociate-entities-using-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/associate-disassociate-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/associate-disassociate-entities-using-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment] 2023-04-05 01:00
Thanks for your comment, @JandosHk. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment] 2023-04-05 15:54
@JandosHk 
All the samples we publish are tested and represent how the API should work in all cases.

If you are seeing different behavior, you can contact technical support. 

If you have some specific repro, you could share the details, such as fiddler traces, that would be interesting and give me something to work with, but we don't have the resources to troubleshoot this with you.

**Closed by JimDaly** 2023-04-05 15:54 UTC
Labels: assigned-to-author

**Comment by JandosHk** [comment] 2023-04-07 00:09
Here are the sample code I'm using:

```
using var rdr = await cmd.ExecuteReaderAsync();
if (rdr.HasRows)
{
    rdr.Read();
    while (true)
    {
        var unit = new JObject
        {
            { "cr7x5_code", (string)rdr["UnitCode"] },
            { "cr7x5_name", (string)rdr["UnitName"] }
        };

        if (rdr.IsDBNull(rdr.GetOrdinal("DepartmentCode")))
            unit["cr7x5_department"] = null;
        else
            unit["cr7x5_department@odata.bind"] = $"/businessunits(cr7x5_divisioncode='{(string)rdr["DepartmentCode"]}')";
```

I use [Web API Service](https://github.com/microsoft/PowerApps-Samples/tree/master/dataverse/webapi/C%23-NETx/WebAPIService) to send JObject to our dataverse table.
The above code works fine. Ideally, it would help if I hadn't to change property name when I need to set property to  null.

**Comment by JimDaly** [comment] 2023-04-07 00:54
@JandosHk 
It isn't clear from your code what you are doing with the JObject.  Are you using `POST` to create a new row, or using `PATCH` to update an existing row. Since the issue is about disassociating, I have to assume PATCH, but I don't see that you are setting any primary keys, unless `UnitCode` and `UnitName` are alternate keys.

Like I mentioned, I've tested this using the` contact` entity `parentcustomerid_account` single-valued navigation property. I wouldn't publish a sample that doesn't work. So, unless that sample code is not correct, there is nothing actionable for me with the docs. 

If it isn't working as documented for your case, that seems like a bug to me. You should contact tech support.

**Comment by JandosHk** [comment] 2023-04-07 01:33
Yes, UnitCode is alternative key, and I'm using batch upsert. I understand that the doc shouldn't change, and maybe it's a bug.
