### ISSUE TITLE
Document missing example: No way to do apply=groupby((value)) and sort by createdon descending?

### ISSUE THREAD

**Issue by wrharper-AASP** [MicrosoftDocs/powerapps-docs#4723] opened 2023-09-12 17:49 UTC
The document doesn't have an example showing how this can be possible. No where online seems to have this information. Can this even be done? How would you do this?
If you try groupby((createdon)) it says datetimes are not allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5424f5-e734-423d-2baf-d7f82d500c96
* Version Independent ID: 4c1116df-37f5-0be4-6c94-3e3939e4cdb2
* Content: [Query data using the Web API - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/query-data-web-api)
* Content Source: [powerapps-docs/developer/data-platform/webapi/query-data-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/query-data-web-api.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @divkamath
* Microsoft Alias: **dikamath**

**Comment by bishalgoswami** [comment] 2023-09-12 21:00
Thanks for your comment, @wrharper-AASP. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment] 2023-09-12 21:18
@wrharper-AASP 
Thanks for your feedback.

I believe that groupby requires some specific values. DateTime values contain information down to the millisecond, so unless there is a way to refer to a specific part of the date (year, month, day) there aren't any specific values to group by.

FetchXml has an ability to specify a `dategrouping` to isolate the different parts of a date.

```
<fetch aggregate='true'>
   <entity name='account'>
      <attribute name='numberofemployees'
         alias='Total'
         aggregate='sum' />
      <attribute name='createdon'
         alias='Day'
         groupby='true'
         dategrouping='day' />
      <attribute name='createdon'
         alias='Week'
         groupby='true'
         dategrouping='week' />
      <attribute name='createdon'
         alias='Month'
         groupby='true'
         dategrouping='month' />
      <attribute name='createdon'
         alias='Year'
         groupby='true'
         dategrouping='year' />
      <attribute name='createdon'
         alias='FiscalPeriod'
         groupby='true'
         dategrouping='fiscal-period' />
      <attribute name='createdon'
         alias='FiscalYear'
         groupby='true'
         dategrouping='fiscal-year' />
      <order alias='Month' />
   </entity>
</fetch>
```

I've not heard that OData supports this.
I found this https://github.com/OData/WebApi/issues/793 ask for it, and it took me to the [spec](http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs02/odata-data-aggregation-ext-v4.0-cs02.html#_Toc435016583) which seems to talk about the potential for 'custom aggregates'.

I'll ask the dev team about this, but AFAIK, this isn't supported.
We could call out that grouping by datetime values isn't supported.

**Comment by JimDaly** [comment] 2023-09-12 23:26
@wrharper-AASP 
I heard back from the dev team and they have confirmed it isn't supported now.
You should get a specific error: `Groupby on datetime field is not supported.`

I've added a note to the docs.

Thanks for helping make our docs better.

Closing this.

**Closed by JimDaly** 2023-09-12 23:26 UTC
Labels: assigned-to-author

**Comment by wrharper-AASP** [comment] 2023-09-13 14:24
The fetchxml provided would not work for what I am doing.
I need to get a distinct list of a column string value and then sort those distinct column string values by the latest createdon for each name.
Example:
A latest time is 6/1
A not latest time 5/1
B latest time is 4/1
B not latest time 3/1

results, show only:
B
A

**Comment by wrharper-AASP** [comment] 2023-09-13 14:26
It cannot show anything else like odata info or any other junk that clutters up memory and speed on results.

**Comment by JimDaly** [comment] 2023-09-13 16:42
Issues for this repository must address the documentation content or functionality. 

This issue seems to be a request for technical support. We do not have the resources to troubleshoot issues. If you need help, please contact technical support.
