### ISSUE TITLE
Localization in plugins

### ISSUE THREAD

**Issue by mathiasbl** [MicrosoftDocs/powerapps-docs#840] opened 2019-12-05 12:26 UTC
According to this article (https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-solutions-support-multiple-languages#use-xml-web-resources-as-language-resources) you can retrieve webresources and then go and parse the resx file to localize messages in a plugin.
Aren't these heavy operations to do in a plugin? This logic would have to run every single plugin invoke aswel.

Can you confirm this is the way to do localization in plugins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f29787-5c9b-8f3c-51ff-a46f72627f02
* Version Independent ID: 71a8e229-78c6-77bb-e165-d024eaa81406
* Content: [Create solutions that support multiple languages (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/create-solutions-support-multiple-languages#use-xml-web-resources-as-language-resources)
* Content Source: [powerapps-docs/developer/common-data-service/create-solutions-support-multiple-languages.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/create-solutions-support-multiple-languages.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by mathiasbl** [comment] 2020-08-10 08:40
Any feedback?

**Comment by phecke** [comment] 2022-07-02 02:01
@mathiasbl Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 02:01 UTC
Labels: open-for-too-long
