### ISSUE TITLE
Inaccurate info on PowerApps Community Plan eligibility

### ISSUE THREAD

**Issue by dickscheel** [MicrosoftDocs/powerapps-docs#193] opened 2019-02-06 20:05 UTC
On this page (https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan#who-can-sign-up-for-the-powerapps-community-plan) it states "If you are a Visual Studio Dev Essentials user, PowerApps is included in your benefits." However, I am prevented from signing up for the Community Plan due to not having a work or school email account, even though I have PowerApps Community Plan listed in my Visual Studio benefits page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d27942c-51fc-c2dc-9857-bcbfbadba145
* Version Independent ID: 832089db-9a05-9d52-7529-429e3a6648f8
* Content: [PowerApps Community Plan -- a free development environment for individual use - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/dev-community-plan#who-can-sign-up-for-the-powerapps-community-plan)
* Content Source: [powerapps-docs/maker/dev-community-plan.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/dev-community-plan.md)
* Service: **powerapps**
* GitHub Login: @ImadYanni
* Microsoft Alias: **iyanni**

**Comment by dickscheel** [comment] 2019-02-06 20:08
![capture](https://user-images.githubusercontent.com/22014838/52370454-c92fc700-2a07-11e9-914b-bb44ec34f66c.JPG)
This screen capture shows the benefit on my VS benefits page.

**Comment by slate0** [comment] 2019-05-10 11:58
I ran into this as well.  You can't call it a Community plan and then restrict it to work accounts.. that's just not truth.

**Comment by PerJohannes** [comment] 2020-01-19 11:51
It would be nice if community plan was available for personal accounts. The information per 19th jan 2020 is still false: "If you are a Visual Studio Dev Essentials user, Power Apps is included in your benefits."

**Comment by mikewaretena** [comment] 2020-02-06 07:02
You can create a visual studio dev essentials subscription using an MSA or github account, from there, you should be able activate your community plan, no work or school account needed.

**Comment by mikewaretena** [comment] 2020-02-06 07:05
Oh, nevermind... :)

**Comment by monty0018** [comment] 2020-03-03 06:24
Same issue here.  The largest competitor to MS in this space allows for free development accounts and licensing.  Seems like it would be good business to empower as many people as possible with the training to develop on the platform.

**Comment by SeaDude** [comment] 2020-05-09 05:53
You could always purchase a domain ($5-10/yr.) and setup your own email account. That qualifies as a "work" account. Basically means anything but one of the big @gmail, @yahoo, etc. email addresses.

**Comment by joshieecs** [comment] 2020-07-06 09:00
What you have to do as an individual wanting to use the "Community" PowerApps is first create a free Azure AD tenant, which will automatically add your Microsoft account as an administrator for the tenant, but with a new login in the form of _user_@_tenant_.**onmicrosoft.com**. 

Use that login to register for PowerApps. That is considered a "work or school" account, even though in this case it would still be your "personal" account from your "personal" AD tenant. You could also add an entirely new user to the tenant to register with PowerApps. It doesn't have to be tenant user associated with your Microsoft account.

Instructions are here. [Quickstart: Create a new tenant in Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-access-create-new-tenant)

What "work or school account" really means is that it's a user in an Azure AD tenant, rather than a Microsoft account provisioned with consumer 365 services. Many of the resources used by PowerApps can only be provisioned in the context of an Azure AD tenant.

**Comment by KumarVivek** [comment] 2022-07-13 00:27
“Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue."

**Closed by KumarVivek** 2022-07-13 00:27 UTC
Labels: 01admin, assigned-to-author, open-for-too-long
