### ISSUE TITLE
Missing Overload of Patch of Data Source

### ISSUE THREAD

**Issue by daryllabar** [MicrosoftDocs/powerapps-docs#742] opened 2019-10-24 22:10 UTC
Looks like I'm able to create a new record in a data source (Azure SQL in may case) using the following code:
```
Patch('[dbo].[Contact]',
    {
        FirstName: "Bob", 
        LastName: "Smith"
    }
);
```
but each of the calls for patch using a datasource mark three parameters as required, not two.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b39cb78-75da-5e8c-f105-1f0b9ea1b830
* Version Independent ID: 28bfec67-a78a-4a0d-cfc6-e95a560f7092
* Content: [Patch function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-patch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-patch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment] 2021-07-21 19:26
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Nkrb** 2021-07-21 19:26 UTC
Labels: CanvasApp, assigned-to-author, in-progress, open-for-too-long, product-bug, waiting-on-internal-feedback
