### ISSUE TITLE
Auto-number attributes Can be added with the new field editor now

### ISSUE THREAD

**Issue by ZaarourOmar** [MicrosoftDocs/powerapps-docs#848] opened 2019-12-08 05:56 UTC
The information about not being able to create auto numbered fields is not updated as we currently can create auto number fields from the new form/field designer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5456f91-242e-a657-0dfd-b9c97c4231ec
* Version Independent ID: 398f49bd-15b8-e019-594f-475ef277561e
* Content: [Attribute metadata - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/entity-attribute-metadata#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/entity-attribute-metadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/entity-attribute-metadata.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-07-02 02:05
@ZaarourOmar Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2022-07-02 02:05 UTC
Labels: open-for-too-long
