### ISSUE TITLE
openForm: relationship attribute on the entityFormOptions does not work

### ISSUE THREAD

**Issue by ramarao9** [MicrosoftDocs/powerapps-docs#1928] opened 2020-11-13 20:21 UTC
When trying to use the Xrm.Navigation.openForm method to open a contact record and focus on the Cases navigation subgrid, it does not work.

Below is a simple script you can use to run on console in Developer tools. It opens the contact form but does not open the Cases tab and set focus on it.

(function () {

debugger;
var entityFormOptions = {};
entityFormOptions["entityName"] = "contact";
entityFormOptions["entityId"] = "71fecc3a-b07c-e911-81b1-00155dcfbf55";//some id of contact in the environment

var relationship={};
relationship["attributeName"]="contactid";
relationship["name"]="incident_customer_contacts";
relationship["navigationPropertyName"]="incident_customer_contacts";
relationship["relationshipType"]=0;
relationship["roleType"]=2;

entityFormOptions["relationship"]=relationship;

// Open the form.
Xrm.Navigation.openForm(entityFormOptions).then(
    function (success) {
        console.log(success);
    },
    function (error) {
        console.log(error);
    }
);

})();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b204ee0a-69a2-e52d-f110-2291be66c1af
* Version Independent ID: 8ac980df-6b5f-2b33-707f-11efb597ba6a
* Content: [openForm (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openform)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openForm.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2020-11-20 17:28
Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-20 17:28 UTC
Labels: assigned-to-author, client-api
