### ISSUE TITLE
Updated list of Restricted entities

### ISSUE THREAD

**Issue by bthompson-365** [MicrosoftDocs/powerapps-docs#1231] opened 2020-04-06 18:28 UTC
The previous version of this document made it clear that the list of restricted entities was out of date and I know that it is as there are a set of Dynamics 365 for Sales entities that should be on the list. 

Sadly instead of actually updating the list it seems you have just changed the data and added a link to the PowerApps license guide. Which would be fine if it included a list of restricted entities. Unfortunately it doesn't include said list it just provides a link back to this restricted entities page.

Given that this documentation is now well over a year out of date could someone check, and document the actual list of Dynamics 365 restricted entities and replace the previous message that the list is incomplete until the list has been updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecf0cd5-9a4c-780a-7cc9-c189d399efa5
* Version Independent ID: 32aeab29-70b5-97b3-1a6b-96c6bfcecc3c
* Content: [Restricted entities requiring Dynamics 365 licenses - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-restricted-entities#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/data-platform-restricted-entities.md)
* Service: **powerapps**
* GitHub Login: @lancedMicrosoft
* Microsoft Alias: **lanced**

**Comment by Mattp123** [comment] 2021-07-28 23:08
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 23:08 UTC
Labels: assigned-to-author, open-for-too-long
