### ISSUE TITLE
getStage() always return the active stage, not the next active stage.

### ISSUE THREAD

**Issue by michaelmouawaddo** [MicrosoftDocs/powerapps-docs#1780] opened 2020-09-25 09:06 UTC
> getStage: Returns a stage object. Except when the navigation moves to a new entity, the stage returned represents the destination stage object,that is, the next active stage.

**getStage()** actually returns the active stage, not the next one, even when not moving to a new entity.

Tested on D365 v9.1 online, opportunity entity.

Is this a bug?

> 2020 release wave 1 enabled
> Server version: 9.1.0000.22546
> Client version: 1.4.1444-2008.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11870b22-3232-c437-f8ea-7aff84d9c073
* Version Independent ID: 9c6d7f4a-8fb1-8ef5-c2d5-ed14e5f6a6e4
* Content: [OnPreStageChange Event (Client API reference) in model-driven apps in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/onprestagechange)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/events/onprestagechange.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/onprestagechange.md)
* Service: **powerapps**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Nkrb** [comment] 2020-10-27 21:10
@michaelmouawaddo Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.

**Closed by Nkrb** 2020-10-27 21:10 UTC
Labels: assigned-to-author, client-api
