### ISSUE TITLE
Xrm.Navigation.navigateTo not working in v9 on-premise

### ISSUE THREAD

**Issue by kgnzlz** [MicrosoftDocs/powerapps-docs#1310] opened 2020-04-27 17:37 UTC
I was wondering if this functionality was supported in Dynamics v9 On-Premise or if it only works for online version. Been following multiple tutorials and forums but it isn't working for me. My Dynamics current version is 9.0.15.9 . It is an issue with my version? with been on-premise?

**Comment by Nkrb** [comment] 2020-04-28 17:05
@kgnzlz Thanks for the feedback. The navigateTo method should work for on-premises orgs too. Please update your org to the latest version and see if you can use this method.

**Comment by kgnzlz** [comment] 2020-04-29 19:03
@Nkrb Thanks to you! Do you now the number of the latest version? Because the one mentioned in the first comment appears as the latest 'Cumulative' update for my organization. Can you tell me the update version I should have for it to work?

**Comment by Nkrb** [comment] 2020-05-01 18:08
@kgnzlz It is difficult  to say exactly which method is released with the version, because different methods within the navigteTo method are released in different client versions.

**Comment by Nkrb** [comment] 2020-05-12 15:44
@kgnzlz Please update to a newer version and see if you can use the method, or please raise a support ticket if that doesn't work. Closing the issue.

**Closed by Nkrb** 2020-05-12 15:44 UTC
Labels: assigned-to-author

**Comment by Volvere** [comment] 2021-01-12 00:14
@Nkrb , I have confirmed that it is not working in On-Prem Server version: 9.0.22.8 (DB 9.0.22.8) - November 2020 patch.

When traversing to the jscript code, it gets into the 'Invalid page type' line.

![image](https://user-images.githubusercontent.com/9946115/104252905-523ebb00-54c7-11eb-83ec-c542a8d4e970.png)

**Comment by Volvere** [comment] 2021-01-12 00:19
@Nkrb , 
![image](https://user-images.githubusercontent.com/9946115/104253164-f6c0fd00-54c7-11eb-8b7c-276c8fd5b1d3.png)
