### ISSUE TITLE
$expand and $ref with $select and $filter

### ISSUE THREAD

**Issue by carolinabbruno** [MicrosoftDocs/powerapps-docs#679] opened 2019-10-01 18:56 UTC
Hello,

I'm new at dynamics 365 API requested, being a dummies I have an issue when expanding a column.
I learn how to write, and it works: 

"https://microsoftsales.api.crm.dynamics.com/api/data/v9.1/leads?$filter=Microsoft.Dynamics.CRM.OnOrAfter(PropertyName=@p1,PropertyValue=@p2)&@p1='createdon'&@p2='01/01/2019'&$expand=createdby($select=_siteid_value;$filter=_siteid_value eq xxxxxxxxx),&$select=_ownerid_value, 
_createdby_value, estimatedamount_base, revenue_base, msp_cssdisposition, _campaignid_value, createdby, leadqualitycode, _accountid_value, numberofemployees, 
_parentaccountid_value, msp_primaryproductcode, subject, msp_leadnumber, msp_estimatedquantity, msp_countrycode, numberofemployees, createdon"

However, it gives me all data, I only want the ones associated with the $filter=_siteid_value eq xxxxxx. I tried to use $ref but it didn't work.
Can someone help with this issue?

Many thanks in advance.

**Comment by phecke** [comment] 2022-07-02 00:59
@carolinabbruno Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:59 UTC
Labels: open-for-too-long
