### ISSUE TITLE
The HTML webresource can be not ready when the method getContentWindow() is called

### ISSUE THREAD

**Issue by dmognaschi** [MicrosoftDocs/powerapps-docs#1914] opened 2020-11-11 19:52 UTC
Dear team,

if the HTML webresource doesn't contain the function setClientApiContext() directly, but references a js webresource, when the form calls getContentWindow() the js may not have loaded yet and the function setClientApiContext() is still undefined.

It is very important to be able to place the code in an external js webresource instead of as an inline script tag: many HTML webresource are complex and are written in TypeScript.

It would be nice to have a different way to pass the xrm and formContext references.
Reversing the logic, for example, it could be the webresource that warns the form with a window.postMessage() that it is ready to receive the context, having the reference to the form's window.

Thanks for your kind help,
Davide Mognaschi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4c796e-ad9f-1929-f530-f088462522f9
* Version Independent ID: 40e67735-ac26-30a4-3191-0a86fd7b4b50
* Content: [getContentWindow (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/getcontentwindow)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2020-12-08 21:53
@dmognaschi Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-12-08 21:53 UTC
Labels: assigned-to-author, client-api
