### ISSUE TITLE
Getting view data adjacent to the chart

### ISSUE THREAD

**Issue by nickbrandl** [MicrosoftDocs/powerapps-docs#1031] opened 2020-02-14 11:39 UTC
When using a custom web resource to display data in a chart, how can we access related data displayed on the view asociated to the chart? Currently in Unified Interface, there are no query string parameters to get this information, so the chart itself is useless to display data for view records.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2599de9f-88d9-afb3-9329-9b8099e4b1a1
* Version Independent ID: 0d5bd4e0-11d4-a86f-fe55-5b3cdc55dbc3
* Content: [Create a visualization (chart) (model-driven apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/create-visualization-chart#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/create-visualization-chart.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/create-visualization-chart.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by nickbrandl** [comment] 2020-02-14 11:43
When using deprecated web interface, then query string parameters are passed in. Among those parameters, we get the 'viewid' and 'typename' parameters, which would allow us to query the system to get data from records displayed in the associated view.

**Comment by JimDaly** [comment] 2020-02-17 18:51
Please assign this (and this topic) to someone on the Power Apps team since they own this functionality now.

**Comment by KumarVivek** [comment] 2022-11-08 00:13
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by KumarVivek** 2022-11-08 00:13 UTC
Labels: assigned-to-author, open-for-too-long
