### ISSUE TITLE
The method getWebResourceUrl() doesn't exists in the on-premises version of the product

### ISSUE THREAD

**Issue by dmognaschi** [MicrosoftDocs/powerapps-docs#1858] opened 2020-10-28 08:26 UTC
Dear team,
The method getWebResourceUrl() doesn't exists in the on-premises version of the product.
Could you please specify that?

Thank you,
Davide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626d27c2-272d-6154-6d80-4115fcbc1406
* Version Independent ID: 25153d08-6660-7abb-30d1-adba925caa02
* Content: [getWebResourceUrl (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/getglobalcontext/getwebresourceurl)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/getWebResourceUrl.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/getGlobalContext/getWebResourceUrl.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2020-11-11 18:59
@dmognaschi Thanks for contacting us. We have created a internal work item for the respective dev team to investigate if the method is available for on-premises version of the product. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 18:59 UTC
Labels: assigned-to-author, client-api
