### ISSUE TITLE
Example is not entirely correct

### ISSUE THREAD

**Issue by AleksandrRogov** [MicrosoftDocs/powerapps-docs#1222] opened 2020-04-02 16:13 UTC
I had to add `setInterval` inside `getContentWindow` callback to make sure that the `contentWindow` is fully loaded before calling `setClientApiContext`. It's done, because in some cases `setClientApiContext` was `undefined` during testing. Here's my working sample:

```js
function form_onload(executionContext) {
    const formContext = executionContext.getFormContext();
    const wrControl = formContext.getControl("new_myWebResource.htm");
    if (wrControl) {
        wrControl.getContentWindow().then(contentWindow =&gt; {
            let numberOfCalls = 0;
            let interval = setInterval(() => {
                if (typeof contentWindow.setClientApiContext !== "undefined") {
                    clearInterval(interval);
                    contentWindow.setClientApiContext(Xrm, formContext);
                }
                else
                    //stop interval after 1 minute
                    if (++numberOfCalls > 600) {
                         clearInterval(interval);
                         throw new Error("Content Window failed to initialize.");
                    }
            }, 100);
        });
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4c796e-ad9f-1929-f530-f088462522f9
* Version Independent ID: 40e67735-ac26-30a4-3191-0a86fd7b4b50
* Content: [getContentWindow (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/getcontentwindow)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by partridgetim** [comment] 2021-03-02 21:24
setClientApiContext was still occasically undefined in my testing even with the setInterval call. Must be some racing condition. I suspected it was because contentWindow was not being re-evaluated during each interval iteration. The value of contentWindow would remain "#document" without any associated DOM. I tweaked the example by calling getContentWindow in each setInterval call.

```javascript
function form_onload(executionContext, webResourceName) {        
    const formContext = executionContext.getFormContext();
    const webResouceControl = formContext.getControl(webResourceName);
    if (webResouceControl) {
        let numberOfCalls = 0;
        let interval = setInterval(() => {
            webResouceControl.getContentWindow().then(contentWindow => {
                if (contentWindow.setClientApiContext) {
                    clearInterval(interval);
                    contentWindow.setClientApiContext(Xrm, formContext);
                }
                else
                    console.warn("contentWindow.setClientApiContext is undefined");
                    //stop interval after 1 minute
                    if (++numberOfCalls > 60) {
                         clearInterval(interval);
                         throw new Error("Content Window failed to initialize.");
                    }
            });
        }, 1000);
    }
};
```

**Comment by JimDaly** [comment] 2023-08-10 23:22
“Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue."

**Closed by JimDaly** 2023-08-10 23:22 UTC
Labels: assigned-to-author, client-api
