### ISSUE TITLE
WAF Guidance Makes No mention that submitted form data may not be sent via your WAF at all (e.g. calls to svc.dynamics.com) 

### ISSUE THREAD

**Issue by braverbug** [MicrosoftDocs/powerapps-docs#3636] opened 2022-09-08 08:30 UTC
Hi There, 

We have noticed that some calls do not traverse the WAF at all e.g. (registration pages interacting with svc.dynamics.com). There should be warnings of cases where event registrations do not traverse the WAF. 

Thanks!

Dan 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6210e47a-bd42-415b-4a6f-2d3d98ea6842
* Version Independent ID: ef661b14-5ac0-3566-561e-24fc2d6351e7
* Content: [Set up Azure Front Door with portals - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/azure-front-door#set-up-a-custom-domain-name)
* Content Source: [powerapps-docs/maker/portals/azure-front-door.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/azure-front-door.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by bishalgoswami** [comment] 2022-09-08 09:00
Thanks for your comment, @braverbug. This issue has been assigned to the doc author for review.

**Comment by nickdoelman** [comment] 2022-09-12 19:44
Thank you for your comment. Can you let us know what portal template you are using?

**Comment by nickdoelman** [comment] 2022-10-05 12:41
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by nickdoelman** 2022-10-05 12:41 UTC
Labels: assigned-to-author
