### ISSUE TITLE
Package Deployer appears to be ignoring data mapping file, and defaulting to automatic mapping.

### ISSUE THREAD

**Issue by ryanperrymba** [MicrosoftDocs/powerapps-docs#1201] opened 2020-03-28 23:41 UTC
While I've confirmed file names match for the import data mapping file, and no errors are thrown, I am only able to import data as part of a package if the columns match the target system exactly.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b0e3a7-a385-942e-1261-53d1aeac1673
* Version Independent ID: 95ad8dd4-3458-8fb2-9e1f-8780fea5853a
* Content: [Create packages for the Package Deployer (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/package-deployer/create-packages-package-deployer)
* Content Source: [powerapps-docs/developer/common-data-service/package-deployer/create-packages-package-deployer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/package-deployer/create-packages-package-deployer.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by ryanperrymba** [comment] 2020-03-29 01:36
Determined cause of confusion:
The configimportmapfile/filename is the name of the file, including .xml
The configimportfile/associatedmap is the map name on the server, NOT the filename, and does not include a file extension.  Initially I left this blank under the assumption that I was not using an existing map.  Later, I added the map file name, which was incorrect.  

The documentation is not wrong, but it may be good to clarify this.

Thanks in advance.

**Comment by phecke** [comment] 2021-11-11 03:10
@ryanperrymba 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-11-11 03:10 UTC
Labels: assigned-to-author, open-for-too-long
