### ISSUE TITLE
Delta Sync Performance for Azure Synapse Link to Dataverse

### ISSUE THREAD

**Issue by jaspinder-singh** [MicrosoftDocs/powerapps-docs#2858] opened 2021-11-12 17:48 UTC
I'm having a hard time getting some definitive information on what kind of lag time you could expect from this "near real time" sync? Is it 15 minutes? An hour? Some guidance here would be much appreciated.

**Comment by phecke** [comment] 2021-11-12 21:34
@jaspinder-singh  Please provide a documentation link from where you read about a near real time sync.

**Comment by jaspinder-singh** [comment] 2021-11-29 16:16
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/export-to-data-lake.

**Comment by jaspinder-singh** [comment] 2021-12-09 17:59
Hi. Any update on this?

**Comment by ahmet269** [comment] 2022-12-21 15:05
Hi , any updates on this?

**Comment by Mattp123** [comment] 2023-01-12 15:46
@ahmet269 - Thanks for your feedback. We are either unable to find relevant information or reproduce this issue. If you're still experiencing the issue described here, reopen or create a new issue. 

More specifically, because the performance of a particular feature is determined by multiple aspects beyond the control of the feature (e.g. network, data size, etc.), it is difficult to appraise accurately. 

Closing issue.

**Closed by Mattp123** 2023-01-12 15:46 UTC
Labels: assigned-to-author, waiting-on-internal-feedback, open-for-too-long
