### ISSUE TITLE
Example to update  more than one record

### ISSUE THREAD

**Issue by FredLEGUEN** [MicrosoftDocs/powerapps-docs#441] opened 2019-06-12 09:29 UTC
In this article, you write that in order to update more than one record, the second argument is a BaseRecordTable.
But you don't give an example.
Can you please give an example of code to update more than 1 record. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5786697f-ee29-1b61-c59a-955086201d55
* Version Independent ID: d2130620-9767-c72f-5bd7-8417e48cf65d
* Content: [Patch function - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-patch#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-patch.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-patch.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment] 2021-07-21 19:25
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Nkrb** 2021-07-21 19:25 UTC
Labels: CanvasApp, assigned-to-author, in-progress, open-for-too-long, waiting-on-internal-feedback
