### ISSUE TITLE
Loses mapped fields from parent

### ISSUE THREAD

**Issue by PeterHale53** [MicrosoftDocs/powerapps-docs#3471] opened 2022-06-27 04:15 UTC
Hi

You neglect to add that if you do this on a child form on create from the parent, any mapped field values are lost as the form is refreshed,

Please confirm and add - would be great to keep any mapped values from the parent. This needs to be addressed

Pete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71065911-65c7-1464-97f9-d5c6a673c808
* Version Independent ID: 6573c9a2-6933-a8fe-eb70-a047990e3312
* Content: [setActiveProcess (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-data-process/activeprocess/setactiveprocess)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/activeprocess/setActiveProcess.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data-process/activeprocess/setActiveProcess.md)
* Service: **powerapps**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment] 2022-06-27 05:00
Thanks for your comment, @PeterHale53. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment] 2022-06-27 17:13
@PeterHale53 

Can you elaborate more on what you expect to find in the documentation about this?
Are you describing a bug, or is there some missing information that will help people get the desired outcome?

A new child record may be initialized with some default values set because the application uses the [InitializeFrom Function](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/initializefrom?view=dataverse-latest) and these values should be set in the form.

Seems like you are describing that the mapped values are lost when the setActiveProcess method is used. Am I understanding you correctly?

**Comment by JimDaly** [comment] 2022-06-28 20:46
@PeterHale53 
Thanks for your kind words. 

Dev team confirmed that setActiveProcess will re-load the form, which will discard any unsaved changes, which includes the data from the mapping. That is something we can document but isn't likely to change.

The Create form contains a record that hasn't been saved yet, so I'm not sure how a BPF could be associated to a record with no id yet. The fact that this seems to work for system administrators is something I can't explain.

Have you tried just saving the record? Does it re-load with the BPF in this case?

**Comment by PeterHale53** [comment] 2022-06-28 20:57
Hi Jim

Thanks for confirming the reload and loss of mapping. Agree, not sure anything can be done about it, but all I was really asking for was a warning on the page saying that if you do change the BPF in the OnLoad on a create you will lose the mapping as you have suggested can be done.

As for my issue, if the record is saved and closed and then reopened the bpf appears fine. Strange. Others seems to have had the issue over the years, but it appears very intermittent although in our case it is consistent. Dev and Test in our tenant and then when we move to customer environment for UAT it is the same. We haven’t provisioned Production at the customer yet (probably tomorrow or Friday).

Anyhow, thanks for your time. Keep up the good work.

Pete

**Comment by JimDaly** [comment] 2022-06-28 23:18
I've updated the topic to include a mention of the fact that calling setActiveProcess will reload the form.
I also updated the description with help from the dev team to try and bring more clarity, I think it got scrambled a bit over time with terminology changes.
Should go live this evening

**Closed by JimDaly** 2022-06-28 23:19 UTC
Labels: assigned-to-author
