### ISSUE TITLE
Samples download is not available on MSDN Code Gallery

### ISSUE THREAD

**Issue by Zoltango** [MicrosoftDocs/powerapps-docs#2472] opened 2021-06-21 08:16 UTC
Although it is mentioned in the document, it seems samples download is not available on MSDN code gallery. Can you please check it?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3c0933-2f1b-dd9e-750c-4120b6a5d3fd
* Version Independent ID: 9a0ac92c-e7ce-3a28-5b46-689d2cf6d13c
* Content: [Web API  Data operations Samples (Client-side JavaScript) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/web-api-samples-client-side-javascript)
* Content Source: [powerapps-docs/developer/data-platform/webapi/web-api-samples-client-side-javascript.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/web-api-samples-client-side-javascript.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment] 2021-06-21 16:05
Duplicate of #2473

**Closed by JimDaly** 2021-06-21 16:05 UTC
Labels: assigned-to-author
