### ISSUE TITLE
Mapping between Cosmos and D365 unclear

### ISSUE THREAD

**Issue by remyblok** [MicrosoftDocs/powerapps-docs#1016] opened 2020-02-10 11:11 UTC
Hello,

I'm trying to get this to work. with no luck yet. But This is also because the documentation is not always clear on what to to.

Under "Data type mapping" is says 'Azure Cosmos DB document in a collection named Orders'. But a 'collection' is not a thing in Cosmos DB, only databases and containers. So, I think it means a container here?

Under "Add a data source using the Azure Cosmos DB for SQL API Data Provider":
- Point 4, field "Collection Name" it says "The name of the Azure Cosmos DB database containing the collection you want to surface in a virtual entity." So this is the database name, but still referencing collection in stead of container. 
- The screenshot below shows "Collection Name: Orders", this is not very clear and/or right. Because this should be the database name not the container name, and the container name"Orders" has been established earlier in this document. So this makes it unclear what is meant here. The screenshot should be changes to have a different name for the database.

As I understand I now have a place to set the Cosmos database name, not the Cosmos 'collection'/container name. So where you I configure that? Looking at the neighbouring article about OData v4 Virtual entities (https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/virtual-entity-walkthrough-using-odata-provider) , there is a place to fill in the External name and External Collection name. I would assume that the Cosmos container name should be entered there?

Thank for updating this document with the needed clarifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31ff9b04-ff9a-2651-0f96-13684a168983
* Version Independent ID: e2e6cd00-18ff-6c72-bc3e-18a81d4218c1
* Content: [Preview Feature: Use the Azure Cosmos DB for SQL API Data Provider with Common Data Service - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/virtual-entity-documentdb-provider-requirements#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/virtual-entity-documentdb-provider-requirements.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/virtual-entity-documentdb-provider-requirements.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment] 2021-07-28 23:07
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 23:07 UTC
Labels: assigned-to-author, open-for-too-long
