### ISSUE TITLE
Token not valid for 90 days and throws an exception instead of returning all records

### ISSUE THREAD

**Issue by darshSWL** [MicrosoftDocs/powerapps-docs#3845] opened 2022-11-23 07:15 UTC
The documentation mentions "Changes will be returned if the last token is within a default value of 90 days. If it is more than 90 days, the system will return all the records."

In one of my latest projects I needed to use this feature and it is not working according to this documentation.

If the token is older than 30 days the request responds with an OrganizationServiceFault with the message "Version stamp associated with the client has expired. Please perform a full sync."
This means the token is not valid for 90 days, but 30. The request doesn't provide all the records in this case, but an exception.

The organization entity attribute "ExpireChangeTrackingInDays" is set to 30, not 90. We didn't change the value.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae183946-fb2a-1b2f-e199-273eb9a68d54
* Version Independent ID: 0cf78a90-f63b-af43-8075-c1cd4e934e7d
* Content: [Use change tracking to synchronize data with external systems (Microsoft Dataverse) - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-change-tracking-synchronize-data-external-systems)
* Content Source: [powerapps-docs/developer/data-platform/use-change-tracking-synchronize-data-external-systems.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/use-change-tracking-synchronize-data-external-systems.md)
* Service: **powerapps**
* Sub-service: **dataverse-developer**
* GitHub Login: @Peakerbl
* Microsoft Alias: **peakerbl**

**Comment by bishalgoswami** [comment] 2022-11-23 08:00
Thanks for your comment, @darshSWL. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment] 2022-11-28 00:54
@darshSWL 
Thanks for your feedback.
@Peakerbl 
We don't mention that the organization `expirechangetrackingindays` value is what controls this, but I can confirm it is set to 30 in my test environments. This seems to be the setting. Can you confirm and we can update this?

**Comment by Peakerbl** [comment] 2022-12-20 21:15
Default used to be 90 days, but the default was recently changed to 30 days. Using value > 30days, can result in a large SubscriptionTrackingDeletedObject table. This can grow really large depending on the customer activity. The tables track all deletes performed.  Cleanup happens for records older than expirechangetrackingindays.

**Comment by JimDaly** [comment] 2022-12-28 00:46
Topic has been updated to say:

> Changes will be returned if the last token is within a default value of 30 days. This is controlled by the value of the [Organization table ExpireChangeTrackingInDays column](https://learn.microsoft.com/power-apps/developer/data-platform/reference/entities/organization#BKMK_ExpireChangeTrackingInDays) and can be changed. If there are unprocessed changes older than the configured value, the system will throw an exception.

**Closed by JimDaly** 2022-12-28 00:46 UTC
Labels: assigned-to-author
