### ISSUE TITLE
this pages states it is not posible to write back to the model driven apps context... but this is not true longer, see this blogpost

### ISSUE THREAD

**Issue by iiu-dk** [MicrosoftDocs/powerapps-docs#1399] opened 2020-05-15 14:28 UTC
https://www.d365geek.co.uk/single-post/2020/04/16/Update-Model-driven-Record-from-Embedded-Canvas-App

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047b94ce-db9f-ad01-5a62-b0539f2433cc
* Version Independent ID: 1a8a9d3c-2d8b-e13c-042b-0a48fc444956
* Content: [Guidelines on working with embedded canvas apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-guidelines#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-guidelines.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-guidelines.md)
* Service: **powerapps**
* GitHub Login: @RichdiMSFT
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment] 2021-07-28 23:13
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 23:13 UTC
Labels: assigned-to-author, open-for-too-long, waiting-on-internal-feedback
