### ISSUE TITLE
PCF control is not updated

### ISSUE THREAD

**Issue by AlexeySazonov** [MicrosoftDocs/powerapps-docs#961] opened 2020-01-23 13:03 UTC
fireOnChange() does not force updating PCF control bound to the corresponding field.
Only changing attribute value programmatically triggers the refresh. 
Is that by design? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f66e752-4706-e627-8761-c4b32f135e21
* Version Independent ID: bd83f3c7-ef54-33c6-6bc8-52e49f7c25d2
* Content: [fireOnChange (Client API reference) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/fireonchange#feedback)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/fireOnChange.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/fireOnChange.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment] 2020-06-11 16:12
@AlexeySazonov Yes this is by design. Closing the issue.

**Closed by Nkrb** 2020-06-11 16:12 UTC
Labels: assigned-to-author, client-api
