### ISSUE TITLE
Connect / Link to Lake datatabases Virtual Tables data

### ISSUE THREAD

**Issue by gpitzalis** [MicrosoftDocs/powerapps-docs#2921] opened 2021-12-14 10:03 UTC
Dear Guys,

can you confirm that it will *NOT* be possible to:

- Connect to Virtual Table data using Power BI Dataverse connector;
- Include Virtual Tables in the Azure Synapse Link;

Thanks!
JP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b64c8d-3c3d-4e4d-afb1-5e0a54c84046
* Version Independent ID: 8180bdbe-ec98-642e-b7ee-1f57954ee502
* Content: [Create virtual tables using virtual connectors (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors?WT.mc_id=BA-MVP-5000177)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/create-virtual-tables-using-connectors.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by phecke** [comment] 2023-01-28 02:16
@gpitzalis Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2023-01-28 02:16 UTC
Labels: assigned-to-author, open-for-too-long
