### ISSUE TITLE
Power Apps import solution options

### ISSUE THREAD

**Issue by lokiRT** [MicrosoftDocs/powerapps-docs#1211] opened 2020-03-31 15:44 UTC
The Power Apps import solution has an option to activate workflows, does that also include SDK message processing steps?  A note should also be added that a publish is required after importing an unmanaged solution as the options do not make it clear that a publish is not performed before activating workflows for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e92c215-b337-b864-3fee-b9542e4e30c8
* Version Independent ID: 8f26538c-5863-6746-8c2c-ee4438165da4
* Content: [Build tools tasks - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-tasks)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-tasks.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-tasks.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by phecke** [comment] 2021-11-11 03:07
@lokiRT 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-11-11 03:07 UTC
Labels: assigned-to-author, open-for-too-long
