### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerapps-docs#637] opened 2019-09-15 15:59 UTC
Hello,
Beginners like me have no idea what to "Set the Redirect URI" to. This is also a largely unanswered question on Stack Exchange both here (https://stackoverflow.com/questions/49268418/when-registering-an-app-on-azure-active-direct-what-redirect-uri-or-sign-on) and here (https://stackoverflow.com/questions/46682708/azure-app-registrations-sign-on-url). 
Please provide more details for this specific area. 
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40006b60-8da2-47ad-c86f-97c584b75b47
* Version Independent ID: 4cb0e004-092c-3da7-8c7f-306ee2f1f2df
* Content: [Walkthrough: Register an app with Azure Active Directory (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/walkthrough-register-app-azure-active-directory#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/walkthrough-register-app-azure-active-directory.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/walkthrough-register-app-azure-active-directory.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-07-02 00:54
@SeaDude Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:54 UTC
Labels: open-for-too-long
