### ISSUE TITLE
Please clarify if there is a workaround for doing saveAndClose action, or it's deliberately impossible

### ISSUE THREAD

**Issue by skfd** [MicrosoftDocs/powerapps-docs#1622] opened 2020-07-27 21:44 UTC
Doc page says 

> Note that setting the saveMode does not actually take the corresponding action

I'm want to do delayed save and perform same actions as immediate save would do. Is it possible? Can not figure the definite answer to this from the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d00568ac-9426-75f7-1662-7e6083f31c64
* Version Independent ID: 491a98a2-f216-8c6e-75fb-a8a64452c9ff
* Content: [save (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/formcontext-data/save)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/save.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-data/save.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment] 2021-08-11 22:47
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Nkrb** 2021-08-11 22:47 UTC
Labels: assigned-to-author, client-api
