### ISSUE TITLE
Retrieve using alternate key

### ISSUE THREAD

**Issue by KimBon** [MicrosoftDocs/powerapps-docs#531] opened 2019-07-24 12:12 UTC
Hi

This page describes how to retrieve using alternate key. Since alternate keys allows lookups and other field types, it would be nice to see samples on how to use these types in retrieve requests (if supported).

https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/define-alternate-keys-entity

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 282c02a1-8af7-6429-300b-80174f287dc4
* Version Independent ID: a1344116-03d0-1510-9763-8319177f91d0
* Content: [Retrieve an entity using the Web API (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/retrieve-entity-using-web-api#retrieve-using-an-alternate-key)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/retrieve-entity-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/retrieve-entity-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-07-02 00:09
@KimBon Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:09 UTC
Labels: open-for-too-long
