### ISSUE TITLE
Is the PSA extension of Partner portal available for Project Operations as well?

### ISSUE THREAD

**Issue by somesh2207** [MicrosoftDocs/powerapps-docs#2260] opened 2021-04-09 07:55 UTC
[Enter feedback here]

Can you please confirm if the PSA extension of Partner portal available for Project Operations as well?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af86ea65-1051-a39c-5500-00841a4edb94
* Version Independent ID: 111fc348-81b4-c88a-dd2a-fb5fa62a7472
* Content: [Integrate Dynamics 365 Project Service Automation with a portal - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/customer-engagement-apps/integrate-project-service-automation)
* Content Source: [powerapps-docs/maker/portals/customer-engagement-apps/integrate-project-service-automation.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/customer-engagement-apps/integrate-project-service-automation.md)
* Service: **powerapps**
* GitHub Login: @sbmjais
* Microsoft Alias: **shjais**

**Comment by nickdoelman** [comment] 2022-05-31 14:53
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by nickdoelman** 2022-05-31 14:53 UTC
Labels: assigned-to-author, open-for-too-long
