### ISSUE TITLE
Distributing DMT assemblies with own tools

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/powerapps-docs#1312] opened 2020-04-28 06:54 UTC
Hello, given license for Configuration Migration Utility say: "you must comply with any technical limitations in the software that only allow you to use it in certain ways" and "You may not work around any technical limitations in the software". Does it mean that I can't directly use Microsoft.Xrm.Tooling.Dmt.ExportProcessor.dll to build CLI compatible version of the tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de3cedad-1a27-18c2-13e2-7bd3efbf3917
* Version Independent ID: 564bf539-85db-63f0-d592-ac4cfcf27611
* Content: [Developer tools and resources (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/developer-tools?view=dynamics-general-ce-9)
* Content Source: [powerapps-docs/developer/common-data-service/developer-tools.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/developer-tools.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2021-11-02 01:45
@FixRM 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 01:45 UTC
Labels: assigned-to-author, open-for-too-long
