### ISSUE TITLE
Input and Output parameters required to profile custom workflow activities

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#810] opened 2019-11-22 00:26 UTC
To investigate: Some report that plug-ins without input or output parameters cannot be profiled.
Also, what good is a custom workflow activity without input/output parameters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae2bca0-76de-3f98-b0e7-65a137baafa2
* Version Independent ID: eb803d04-bddc-0c43-3dcb-110187fbf379
* Content: [Debug Workflow Activities (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/workflow/debug-workflow-activites)
* Content Source: [powerapps-docs/developer/common-data-service/workflow/debug-workflow-activites.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/workflow/debug-workflow-activites.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-07-02 01:15
@JimDaly Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 01:15 UTC
Labels: open-for-too-long
