### ISSUE TITLE
invokeProcessAction does not work in UCI

### ISSUE THREAD

**Issue by bananamufu** [MicrosoftDocs/powerapps-docs#651] opened 2019-09-20 08:36 UTC
Error message: "This action is not supported"

Runs fine in legacy web interface, but as soon as I switch to UCI, it stops working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a261db5-f03e-8100-f9b9-592ba9a34cea
* Version Independent ID: 281480d2-01b3-1488-9f00-9e82fd6d93ef
* Content: [invokeProcessAction (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/invokeprocessaction)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/invokeProcessAction.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Utility/invokeProcessAction.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment] 2020-11-11 19:06
@bananamufu Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 19:06 UTC
Labels: assigned-to-author, client-api, product-feedback, waiting-on-internal-feedback
