### ISSUE TITLE
More information about new data types and AttributeType vs AttributeTypeName

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#1632] opened 2020-07-30 18:31 UTC
Information about AttributeType and AttributeTypeName should be updated.
The content we have only mentions Image data type, which has AttributeType.Virtual.

But since then, I believe there have been other new types of attributes that should be called out as well.

The legacy AttributeType is frequently misunderstood.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5456f91-242e-a657-0dfd-b9c97c4231ec
* Version Independent ID: 398f49bd-15b8-e019-594f-475ef277561e
* Content: [Attribute metadata - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/entity-attribute-metadata#attribute-types)
* Content Source: [powerapps-docs/developer/common-data-service/entity-attribute-metadata.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/entity-attribute-metadata.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2021-11-02 01:02
@JimDaly  Please provide a list of what should be added.

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 01:02 UTC
Labels: assigned-to-author, open-for-too-long
