### ISSUE TITLE
This method doesn't seem to work if the web resource is not visible 

### ISSUE THREAD

**Issue by DevMunster** [MicrosoftDocs/powerapps-docs#1872] opened 2020-10-31 12:23 UTC
In my case, the section containing the web resource was not visible - the web resource sets its own visibility depending on a query that it runs.
Like that, getContentWindow didn't work. I have to ensure that the web resource is visible before I call getContentWindow.
Microsoft Dynamics 365
2020 release wave 2 enabled
Server version: 9.1.0000.24344
Client version: 1.4.1641-2010.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4c796e-ad9f-1929-f530-f088462522f9
* Version Independent ID: 40e67735-ac26-30a4-3191-0a86fd7b4b50
* Content: [getContentWindow (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/controls/getcontentwindow)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/controls/getContentWindow.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2020-11-11 18:49
@DevMunster Thanks for contacting us. We have created a internal work item for the respective feature team. Will update the docs if required when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 18:49 UTC
Labels: assigned-to-author, client-api
