### ISSUE TITLE
PowerApp only instances cannot create application users

### ISSUE THREAD

**Issue by TigerJ** [MicrosoftDocs/powerapps-docs#817] opened 2019-11-26 17:50 UTC
The sitemap for PowerApp instances that have a common data service but do not have a dynamics license or product does not have a users area that can be navigated to in order to complete this guide. I have checked the advanced settings cog link from a model-driven app which opens the "old" dynamics experience. There is no place to add an application user. I have also tried using advanced find > users > new , this is also blocked from my PowerApp instance.

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/authenticate-oauth#manually-create-a-common-data-service-application-user

This documentation and guide is under PowerApps but appears you must have a Dynamics license instead to use this feature. Please comment.

**Comment by phecke** [comment] 2022-07-02 01:16
@TigerJ Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 01:16 UTC
Labels: open-for-too-long
