### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by nickbrandl** [MicrosoftDocs/powerapps-docs#1462] opened 2020-05-28 14:35 UTC
I'm struggling when working with sub-grids on a form. It would be really nice that you provide working examples for each scenario. It is not the same try accessing the content of a sub-grid from an event in the sub-grid than doing the same from a form event or a command in the ribbon.

I'm struggling now while trying to disable a field in an editable grid and so far, I've been unable to access it using this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83c71d7-6c0e-14cd-a171-971e0bea398e
* Version Independent ID: 31c7103e-e49f-ed58-20bb-cefc3b430eb3
* Content: [Client API grid context in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/clientapi-grid-context)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/clientapi-grid-context.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/clientapi-grid-context.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by JimDaly** [comment] 2023-08-10 23:23
“Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue."

**Closed by JimDaly** 2023-08-10 23:23 UTC
Labels: assigned-to-author, client-api
