### ISSUE TITLE
Stuck after add "Dynamics CRM" Permission in App Registrations

### ISSUE THREAD

**Issue by MebDevelop** [MicrosoftDocs/powerapps-docs#1064] opened 2020-02-24 14:55 UTC
I am adding "Dynamics CRM" Permission in Microsoft Azure/App Registrations/API Permissions following https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/walkthrough-register-app-azure-active-directory#create-an-application-registration 
Part 6 and Part 7.
But it is not adding permission and stuck in that screen for a long time.
I check the developer console and there is 400 error.
```
url: https://graph.windows.net/isDirectoryFeatureEnabled?api-version=1.6-internal

error: {"odata.error":{"code":"Request_InvalidRequestUrl","message":{"lang":"en","value":"Request url was invalid. The request should be like \/tenantdomainname\/Entity or \/$metadata. Tenant domain name can be any of the verified, unverified domain names or context id."}}}

```
How can I figure out this?

**Comment by phecke** [comment] 2021-11-11 03:18
@MebDevelop 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-11-11 03:18 UTC
Labels: open-for-too-long
