### ISSUE TITLE
formName and viewName parameters

### ISSUE THREAD

**Issue by rappen** [MicrosoftDocs/powerapps-docs#309] opened 2019-04-09 10:03 UTC
It would be very good to know which formName and viewName to use.
Is it the name in the organization's base language?
Or the name in the current (Maker) user's language?
Or will it perhaps tie to the current (using) user's language?

What happens if the name of the view/form is changed?
Do all CanvasApps using these methods need to be updated?
Or is the "connection" to the view/form stored by the id in the background, to make it more stable for changes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5033427-7b31-0b45-784e-1c90b5cfb559
* Version Independent ID: 99e40bcc-943e-2ebe-bb20-61cc5ddd2ce3
* Content: [Perform actions on the host form from within an embedded canvas app - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/embedded-canvas-app-actions)
* Content Source: [powerapps-docs/maker/model-driven-apps/embedded-canvas-app-actions.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/embedded-canvas-app-actions.md)
* Service: **powerapps**
* GitHub Login: @aneesmsft
* Microsoft Alias: **matp**

**Comment by aneesmsft** [comment] 2019-06-29 00:49
@rappen It is the name of the form as specified in the form's properties. This does not change based on any language. If the form name changes you will have to update the app. 
Long term we do want to uniquely identify a form but want to do better than asking makers to provide the GUID of the form. 
Current thought is a way to select from a list of forms so makers see display names and internally we store the corresponding GUID so name changes do not affect apps. However this needs more work and will not come in the near term.

**Comment by rappen** [comment] 2019-07-06 12:46
@aneesmsft I'm sorry but it seems you are wrong in this case.
The name of the form is always subject to localization, looking in the `customizations.xml` file you see it clearly:
![image](https://user-images.githubusercontent.com/2572253/60756260-b099fc00-9ffb-11e9-94f5-1c76dbc038ae.png)


Checking the form editor when my personal setting is English:
![image](https://user-images.githubusercontent.com/2572253/60756254-a1b34980-9ffb-11e9-994a-944fef58943f.png)

And same pic when I am using Swedish:
![image](https://user-images.githubusercontent.com/2572253/60756220-4b460b00-9ffb-11e9-8021-1ac25615f834.png)

Same behavior in the classic form editor, English:
![image](https://user-images.githubusercontent.com/2572253/60756296-3ddd5080-9ffc-11e9-90a6-6c8ae94ac9e3.png)

And Swedish:
![image](https://user-images.githubusercontent.com/2572253/60756340-a298ab00-9ffc-11e9-9d88-c9af739ba816.png)


The confusion is though very understandable, as the same property is called **"Form Name"** in classic, **"Title"** in maker experience, and **"LocalizedName/Description"** in the xml.

**Comment by rappen** [comment] 2020-05-10 19:36
Not sure if the docs have been updated and clarified, but this issue is still open an my question still does not have an answer.
Ping! 😊

**Comment by Mattp123** [comment] 2021-07-28 22:58
@rappen - I'm not the SME for embedded canvas apps but it seems to me that the formname and entityname would be using the unique name rather than the display name. E.g., if you have a custom table, it would look something like crfb6_customtable. 

I would also suggest you consider using the newly released to preview feature named custom pages, which is similar to the embedded canvas app control but more flexible when adding a canvas app to a model-driven app. https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/model-app-page-overview

We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 22:58 UTC
Labels: 01model-driven, assigned-to-author
