### ISSUE TITLE
Clarification required for delete lookup property values

### ISSUE THREAD

**Issue by dwcai** [MicrosoftDocs/powerapps-docs#173] opened 2019-01-30 06:21 UTC
In the sample that shows how to remove a single-value navigation property, we discussed the customerid field by removing the customerid_account navigation property. What if the lookup field has a value that points to contact, will it require another service call to remove customerid_contact navigation property? Does that mean that it requires two service calls to clear the lookup field's value entirely since the field can point to either entity? Will the service call fail if there is no value for the navigation entity? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6444b56-0e82-a336-244d-67e4c3aeed05
* Version Independent ID: cb15df8b-5ef7-25b4-24cb-a48a4ec14e9d
* Content: [Associate and disassociate entities using the Web API (Common Data Service for Apps) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api.md)
* Service: **crm-online**
* GitHub Login: @brandonsimons
* Microsoft Alias: **jdaly**

**Comment by kjetilroe** [comment] 2020-03-26 11:58
It is also possible to disassociate using this method:
DELETE [Organization URI]/api/data/v9.0/opportunities(00000000-0000-0000-0000-000000000001)/_customerid_value

Then you only use one request for the disassociation.

**Comment by phecke** [comment] 2021-06-17 00:44
@dwcai

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-06-17 00:44 UTC
Labels: 01dev, assigned-to-author
