### ISSUE TITLE
Connecting to SSMS when MFA is enabled

### ISSUE THREAD

**Issue by Ale-Cesetti** [MicrosoftDocs/powerapps-docs#1438] opened 2020-05-22 15:39 UTC
I would like to know if this is possible. I am trying and getting the following error:

"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication"

Is there any workaround other than disabling MFA for my user?
Are you considering adding this feature? When?

Thank you!!

**Comment by Nkrb** [comment] 2020-05-26 16:42
@Ale-Cesetti Can you point us to the doc you're are talking about, so that we can assign appropriate person.

**Comment by Ale-Cesetti** [comment] 2020-05-26 19:46
Hi @Nkrb 

I installed and configured the SSMS (SQL Server Management Studio) to use against the CDS and it is working when MFA is disabled but fails when enabled. I read the documentation here:

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query

Thank you!!!

**Comment by phecke** [comment] 2021-11-02 01:28
@Ale-Cesetti 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 01:28 UTC
Labels: assigned-to-author, open-for-too-long

**Comment by Ale-Cesetti** [comment] 2021-11-02 15:33
I am currently not using MFA in the environments where I am using SQL so I can't tell if it was fixed or not. What I can tell is that since this issue was created, I don't see any message saying someone was looking into it or found a fix to it. So not sure if this is no longer an issue or it still is and anyone could face it again in the future.

I'll reopen in case I do.

Thanks for the support!!
Ale
