### ISSUE TITLE
Lack of import from Excel permission detail.

### ISSUE THREAD

**Issue by AmonHouston** [MicrosoftDocs/powerapps-docs#2397] opened 2021-05-23 20:55 UTC
This page makes no mention on the level of permissions to allow users to import data via excel (the button in the horizontal bar in the model driven app). No page / official documentation actually lists the permission required, I've had to resort to setting users to Admins which is not suitable in the long run. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91aa21d9-0e21-b87a-4439-cfa800c9210c
* Version Independent ID: 25f91d7a-2fb6-06f4-4ab2-705ce6ea7986
* Content: [Import Data (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/import-data)
* Content Source: [powerapps-docs/developer/data-platform/import-data.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/import-data.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-05-24 22:19
@AmonHouston 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-05-24 22:19 UTC
Labels: assigned-to-author, open-for-too-long
