### ISSUE TITLE
Issue with Async Function in onchange event and pressing save

### ISSUE THREAD

**Issue by Miesjh** [MicrosoftDocs/powerapps-docs#1472] opened 2020-06-03 12:34 UTC
Maybe the documentation is missing something about running async functions in the onchange event of a field. 

We had a onchange event where we did an async call to an action. The result of this action was used in a calculation to fill a certain field. This onchange worked fine when we filled in the value in the field and then pressing TAB after that. 

Example: Field A = Field B * Result Action;

It failed when we filled in the field but instead of pressing TAB, we pressed the SAVE button. Because of the use of an async function in the onchange event, the save procedure already started. This resulted in the outcome of the calculation was not saved. So in this example Field A was not saved. Another thing we saw was that Field B returned a null value but it was not null on the form.

let fieldb = this.formContext.getAttribute('teq_fieldb).getValue();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5a1f535-c694-5408-3a9e-743edaef5cd7
* Version Independent ID: d37275be-3f9e-fb70-0789-77e436ae50ee
* Content: [Attribute OnChange Event in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/events/attribute-onchange)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/events/attribute-onchange.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/events/attribute-onchange.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by Nkrb** [comment] 2020-06-15 16:51
@Miesjh Thanks for the feedback. The issue with save is by design, you need to add logic to block the save until the async call returned.

**Comment by Nkrb** [comment] 2020-06-23 16:04
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-06-23 16:04 UTC
Labels: assigned-to-author, client-api

**Comment by Miesjh** [comment] 2020-06-24 12:52
Just wanted to mention it. Thanks anyway.
