### ISSUE TITLE
Custom Page does not include Invitation Codes option

### ISSUE THREAD

**Issue by dev717** [MicrosoftDocs/powerapps-docs#3215] opened 2022-03-24 15:24 UTC
I configured my custom page following the instructions on this page.  When I browse the new page it has sign in and sign up, but there doesn't seem to be a way to configure an option to accept invitation codes.

Screenshot attached.  

Kurt
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d71e01-9651-365a-0fc0-b0017d3866ca
* Version Independent ID: 507be630-f013-10d1-00dc-c57aa949f0cb
* Content: [Customize the Azure AD B2C user interface for portals - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/portals/configure/azure-ad-b2c)
* Content Source: [powerapps-docs/maker/portals/configure/azure-ad-b2c.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/configure/azure-ad-b2c.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @sandhangitmsft
![B2C Custom Page](https://user-images.githubusercontent.com/15719335/159950832-f9816fda-69d3-4329-ad11-1ed9e37a7c75.jpg)

* Microsoft Alias: **sandhan**

**Comment by dev717** [comment] 2022-03-25 18:12
Could you contact me on my Microsoft Email so I can include some internal users please.


Kurt

***@***.***
________________________________

**Comment by nickdoelman** [comment] 2023-01-16 14:17
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by nickdoelman** 2023-01-16 14:17 UTC
Labels: assigned-to-author
