### ISSUE TITLE
createFromEntity type doesn't match declared type in ComponentFramework.NavigationApi.EntityFormOptions

### ISSUE THREAD

**Issue by rn85apps** [MicrosoftDocs/powerapps-docs#1886] opened 2020-11-04 15:51 UTC
When attempting to use the createFromEntity option with `context.navigation.openForm(options, parameters)`, the declared Type doesn't match.

The documentation states:

> - createFromEntity: Lookup. Designates a record that will provide default values based on mapped attribute values. The lookup object has the following String properties: `entityType`, `id`, and `name`.

However, the declared Type for this object in the `ComponentFramework.NavigationApi.EntityFormOptions` uses the `EntityReference` interface, which has the following properties:

```
interface EntityReference {
        /**
         * The record id. Read-only.
         */
        id: { guid: string; };

        /**
         * The entity logical name. Read-only.
         */
        etn?: string;

        /**
         * The name of the entity reference. Read-only.
         */
        name: string;
    }
```

When attempting to use the `EntityReference` as the createFromEntity option, the code doesn't execute.  However, it will execute as expected when using the String properties that were mentioned in the documentation.
`entityType`, `id`, and `name`.

Workaround seems to be to insert @ts-ignore when creating the options object.  For example:
```

const createFromEntityLookupObj = {
					entityType: _lookupEntityType,
					id: _lookupId,
					name: _lookupName,
				};
				
				const options: ComponentFramework.NavigationApi.EntityFormOptions = {
					entityName: _targetEntityName,
					useQuickCreateForm: true,
					//@ts-ignore
					createFromEntity: createFromEntityLookupObj,
				};
				
				this._context.navigation.openForm(options).then(
					function (success) {
						console.log(success);
					},
					function (error) {
						console.log(error);
					}
				)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1584e4c-abec-d444-2fa5-cf84dc3b33fe
* Version Independent ID: 89452bfa-cd47-879c-90f5-64e327942b27
* Content: [openForm - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/navigation/openform)
* Content Source: [powerapps-docs/developer/component-framework/reference/navigation/openform.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/reference/navigation/openform.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2020-11-11 19:24
@rn85apps Thanks for contacting us. We have created a internal work item for the respective dev team to update the types. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 19:24 UTC
Labels: Component-framework, assigned-to-author
