### ISSUE TITLE
getText() function does not work for Two Options in UCI interface

### ISSUE THREAD

**Issue by PabloRoldanCRM** [MicrosoftDocs/powerapps-docs#1743] opened 2020-09-15 21:11 UTC
Hi, the method `getText()` from `formContext.getAttribute(arg).getText()` used to works on classic interface but now in UCI interface getText() no works for Two Options fields

> formContext.getAttribute(...).getText is not a function

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea615cf-a3fa-8faa-4e15-9b1f68d85556
* Version Independent ID: ca776ad1-9804-b37b-fd6d-a31d5cfcbed1
* Content: [getText (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/gettext)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getText.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/attributes/getText.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2020-11-11 18:51
@PabloRoldanCRM  Thanks for contacting us. We have created a internal work item for the respective feature team. Will update the docs if required when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2020-11-11 18:52 UTC
Labels: assigned-to-author, client-api, product-bug
