### ISSUE TITLE
Argument of type '{ entityName: string; entityId: { guid: string; }; }' is not assignable to parameter of type 'EntityFormOptions'.

### ISSUE THREAD

**Issue by gunjanbr** [MicrosoftDocs/powerapps-docs#1044] opened 2020-02-18 07:34 UTC
While using this example getting the error Argument of type '{ entityName: string; entityId: { guid: string; }; }' is not assignable to parameter of type 'EntityFormOptions'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4c9824-7fe7-269c-eae6-0d4ca3b8ecf1
* Version Independent ID: 73044005-f1a8-94ba-c746-5569943d9886
* Content: [DataSet Grid component - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/sample-controls/data-set-grid-control#feedback)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/data-set-grid-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/component-framework/sample-controls/data-set-grid-control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by Nkrb** [comment] 2021-07-21 19:29
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Nkrb** 2021-07-21 19:29 UTC
Labels: assigned-to-author, in-progress, open-for-too-long
