### ISSUE TITLE
Is Connection Reference not available in GCC tenant?

### ISSUE THREAD

**Issue by wtt32** [MicrosoftDocs/powerapps-docs#1838] opened 2020-10-22 02:15 UTC
I'm in GCC Tenant. In Power Apps Portal -> Solutions, I can see Connection References(Preview) from the solution dropdown list and I'm able to create Connection References manually. But from Power Automate Portal -> Solutions, there's no Connection References(Preview) from the dropdown. I tried to create a new solution, and add a new flow within the solution, What I see is still normal connections instead of Connection References. Is the feature not available to GCC? I didn't see GCC is out of scope from the new feature announcement page neither. https://powerapps.microsoft.com/en-us/blog/announcing-the-new-solution-import-experience-with-connections-and-environment-variables/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6296f1c9-8505-cca0-3b3c-50fbf988d663
* Version Independent ID: a5bf3054-8a46-39d0-9c3f-3270080d8fbc
* Content: [Connection references in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-connection-reference)
* Content Source: [powerapps-docs/maker/common-data-service/create-connection-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-connection-reference.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by bcobra** [comment] 2021-04-14 08:11
What is the status of this? Is there an ETA? I don't see it in the Roadmap. thanks

**Comment by bcobra** [comment] 2021-05-24 14:04
Any updates on this? thanks

**Comment by silgenfritz** [comment] 2021-07-19 14:45
Any ETA on this being resolved in GCC?

**Comment by Mattp123** [comment] 2023-01-12 15:57
@wtt32 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, reopen or create a new issue.

**Closed by Mattp123** 2023-01-12 15:57 UTC
Labels: assigned-to-author, open-for-too-long
