### ISSUE TITLE
The choices() does not return all columns as stated in the doc

### ISSUE THREAD

**Issue by Pitouli** [MicrosoftDocs/powerapps-docs#1510] opened 2020-06-16 03:00 UTC
In the doc, it is said:

> The Choices function returns a table of the possible values for a lookup column. [...] Choices returns all columns of the foreign table

In my app, I am using a SharePoint list as source, named "My Datas". In this SharePoint List, one of the column is named "Countries", and is a lookup to another List named "Countries" having 2 columns: Country Name (renamed "title" column) and Country Continent. 

When I automatically generate a PowerApps for "My Datas", it creates as expected a dropdown linked to the "Countries" List. 

The issue is: this link is made with the function `Choices([@'My Datas'].'Countries')`, but this function does not returns a table of object with properties "Country Name" and "Country Continent" for each country, but instead it returns a table of object with properties "@odata.type", "Id" and "Value" (which corresponds to the "Country Name").

Is this a bug with the Choices function, an error in the doc, or a misunderstanding on my side? 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70491d54-3aae-1104-bbe2-4162b34e4fb2
* Version Independent ID: 52ed1d09-e95f-4bb4-ac9e-cc3481cb7c93
* Content: [Choices function - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-choices#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-choices.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-choices.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by dcrosbie13** [comment] 2020-10-19 15:13
Hello, I am experiencing this same issue, any word on if this is a bug or when it will be fixed?

**Comment by Nkrb** [comment] 2021-08-02 20:24
Thanks for contacting us. We have identified this as product bug and an internal work item is created for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2021-08-02 20:24 UTC
Labels: CanvasApp, assigned-to-author, product-bug, waiting-on-internal-feedback
