### ISSUE TITLE
HelpDesk Tickets - unable to see tickets created ( Help Desk Sample )

### ISSUE THREAD

**Issue by GPZAR** [MicrosoftDocs/powerapps-docs#127] opened 2018-11-22 08:41 UTC
Hi 

I'm unable to see the tickets I created, on my ticket screen what could causes this?

**Comment by AFTOwen** [comment] 2018-12-08 06:37
Closing as duplicate of [this forum post](https://powerusers.microsoft.com/t5/General-Discussion/HelpDesk-Tickets-unable-to-see-tickets-created-Help-Desk-Sample/m-p/183040).

**Closed by AFTOwen** 2018-12-08 06:37 UTC
Labels: 01canvas, 02product
