### ISSUE TITLE
CType is also not supported

### ISSUE THREAD

**Issue by andrewtheart** [MicrosoftDocs/powerapps-docs#708] opened 2019-10-11 18:23 UTC
It is omitted here, but the CType keyword is also not supported in sandboxing mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc0efaf0-91bd-9e1c-2197-8130bba04ca0
* Version Independent ID: a378b133-38bb-d68f-cdfb-2c1d200ade2f
* Content: [RDL sandboxing - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/rdl-sandboxing#feedback)
* Content Source: [powerapps-docs/maker/model-driven-apps/rdl-sandboxing.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/model-driven-apps/rdl-sandboxing.md)
* Service: **crm-online**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment] 2021-07-28 23:06
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 23:06 UTC
Labels: assigned-to-author, open-for-too-long
