### ISSUE TITLE
"Column not bound to a table could used"

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/powerapps-docs#2539] opened 2021-07-12 23:55 UTC
>Can I access form context like I can in model-driven apps event handlers?

> Accessing form context directly in a control is not supported.... **Column not bound to a table could be used**...

Could this be elaborated upon?  What is a column not bound to a table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40ffcc9-c086-f819-2e2f-60ac66c06682
* Version Independent ID: a0406aa3-5035-a4db-3706-ee3b5dd908a5
* Content: [Power App component framework FAQs - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/component-framework/faq)
* Content Source: [powerapps-docs/developer/component-framework/faq.yml](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/faq.yml)
* Service: **powerapps**
* GitHub Login: @ghurlman
* Microsoft Alias: **grhurl**

**Comment by ghurlman** [comment] 2021-07-19 16:43
@bishalgoswami I'm not responsible for all docs, no need to include me in these unless it's a problem with content I'm responsible for directly.

**Comment by JimDaly** [comment] 2022-09-16 22:25
@noazarur-microsoft 
I'm reviewing old issues that haven't been addressed.
Agree with @fowl2  that the description of the workaround is not clear. 
Afraid I don't know what kind of column isn't bound to a table either.
If we don't have details to provide, recommend we remove description of the workaround that is ambiguous.

**Comment by JimDaly** [comment] 2023-08-10 23:37
“Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue."

**Closed by JimDaly** 2023-08-10 23:37 UTC
Labels: assigned-to-author, Component-framework
