### ISSUE TITLE
Finding he correct "Camera" value

### ISSUE THREAD

**Issue by treestryder** [MicrosoftDocs/powerapps-docs#270] opened 2019-02-27 20:04 UTC
Is there a way to present the user with a list of cameras for setting the Camera value? All of the examples I have found either use the default camera 0 or suggest a toggle to flip between "0" and "1". When, on a Pixel 3 the rear camera is "3".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b98c28-54c3-b8ab-bd42-0db8f4892b66
* Version Independent ID: 6eb48d98-df3a-f208-936a-b2003a542ab0
* Content: [Camera control: reference - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/controls/control-camera#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-camera.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/controls/control-camera.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by dmshow** [comment] 2019-03-26 14:09
You can use a Switch statement and add any number of cameras rather than a simple toggle.

**Comment by treestryder** [comment] 2019-03-26 18:31
@dmshow For testing, I used a radio button for the user to chose the camera. What I am looking for is a way to enumerate the possible values. Preferably. with some human readable names; i.e. front, back. In my situation, cameras 1 and 2 are both the front, 3 was the back and I have no idea how many potential camera values there may have been available.

**Comment by dmshow** [comment] 2019-03-26 18:53
I do not know of a way to read the camera's that are available. What I do is a cycle through 3 using a button or icon OnSelect event.

Switch(CamNum, 
                         0, UpdateContext({CamNum:1}),
                         1, UpdateContext({CamNum:2}),
                         2, UpdateContext({CamNum:0}))

The problem is you may not know the device or the number of cameras. Three should be enough. 
On the Screen OnVisual event you will need to initiate the value of CamNum to 0 
UpdateContext({CamNum:0})
or to your preferred camera. 

If you want a label stating the camera, just link it to the same variable. I wouldn't give a name as not all devices will be the same, just give the camera number.

**Comment by fikaradz** [comment] 2019-04-18 22:01
Currently there is no better way to do this.  However we are working on improving this mechanism by allowing you to access front or back cameras.

**Comment by AFTOwen** [comment] 2019-04-19 01:06
Thanks, @treestryder (and @dmshow)! Closing this issue.

**Closed by AFTOwen** 2019-04-19 01:06 UTC
Labels: 01canvas, assigned-to-author

**Comment by gregli-msft** [comment] 2020-04-08 03:59
There is a new **AvailableDevices** property on the Camera control which provides a table of available cameras.

**Comment by Old1977** [comment] 2022-02-22 14:27
Hi, All
I try set default property of dropwrow to:
First(Filter(Camera1.AvailableDevices,"back" in Name)).Name
Dropdow show default value, but camera is stuck on black scrren without image
I think its happend becouse I call to AvailableDevices
Maybe sameone have idea copy AvailableDevices to table variable and will used it? 
I tryed copy on onvisible scrren event but devices not copyed
Set(AllCameras, Camera1.AvailableDevices);

Any ideas?
Thanks
