### ISSUE TITLE
Xrm.Navigation.navigateTo not working in v9 on-premise

### ISSUE THREAD

**Issue by Volvere** [MicrosoftDocs/powerapps-docs#2060] opened 2021-01-18 04:37 UTC
hi there,

I am re-adding this issue. I have placed my comments in the original issue but it doesnt seem to re-open the issue.

Confirmed in On Prem v9, latest patch 9.0.22.8 (DB 9.0.22.8) that navigateTo is not working.

![image](https://user-images.githubusercontent.com/9946115/104872773-dfd84a00-59a2-11eb-9994-ef7765436898.png)

![image](https://user-images.githubusercontent.com/9946115/104872780-e49cfe00-59a2-11eb-8346-37627195f4e3.png)

We really need this feature as opening in new window is causing confusion for users.

Regards,
Henri

**Comment by Nkrb** [comment] 2021-04-01 16:30
Thanks for contacting us. We have created a internal work item for the respective dev team. Will update the docs if any when the issue is resolved. Closing the issue.  If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2021-04-01 16:30 UTC
Labels: assigned-to-author, client-api
