### ISSUE TITLE
"Limitations of virtual tables" needs a review

### ISSUE THREAD

**Issue by skfd** [MicrosoftDocs/powerapps-docs#2905] opened 2021-12-06 15:48 UTC
Looks like the limitations list is form the older version of virtual entities... This statement is not correct, is it?

> All tables in the external data source must have an associated GUID primary key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42ae2cb6-ce2a-21c7-cb81-b60e7b026753
* Version Independent ID: 5a3cb7c0-6881-1d96-0dc3-639324a4568c
* Content: [Get started with virtual tables (entities) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/get-started-ve)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md)
* Service: **powerapps**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment] 2023-01-28 02:21
@skfd Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2023-01-28 02:21 UTC
Labels: assigned-to-author, open-for-too-long

**Comment by skfd** [comment] 2023-01-31 01:35
still a problem. external system does not have to have guid key. it can be natural composite key!!! there is a swcial mechanism for that
