### ISSUE TITLE
Xrm.Navigation.navigateTo sample with relationship parameter

### ISSUE THREAD

**Issue by singapi** [MicrosoftDocs/powerapps-docs#1576] opened 2020-07-08 10:59 UTC
Hi Guys,

My goal is open some form of record using Xrm.Navigation.navigateTo method and show an associated view of the Documents entity (Sharepoint locations) at the same time. The form does not have the Documents subgrid but the form has Documents in Related tab (Navigation items). So, I tried to call navigateTo method passing a relationship object in pageInput parameter but it had no effect to display an associated view for Documents.

My parameters:

```
var pageInput = {
    pageType: "entityrecord",
    entityName: "vs360_job",
    entityId: "cb03f692-686a-e811-814e-480fcff4b171",
    relationship: { attributeName: 'regardingobjectid', name: 'vs360_job_SharePointDocumentLocations', navigationPropertyName: 'regardingobjectid_vs360_job', relationshipType: 0, roleType: 1 }
};
var navigationOptions = {
    target: 2,
    height: {value: 80, unit:"%"},
    width: {value: 70, unit:"%"},
    position: 1
};
Xrm.Navigation.navigateTo(pageInput, navigationOptions)
```

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c917fb9-84c8-2676-9c6a-f33f03ba5da7
* Version Independent ID: 057dd7ac-8383-1650-ceb5-cbea3995180c
* Content: [navigateTo (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/navigateto)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/navigateTo.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by bthompson-365** [comment] 2020-07-08 11:04
XRM.Navigation.navigateTo doesn't offer an option to determine which section or part of a form is loaded. The relationship parameter is for when you are creating a new record and you wish to pre-populate the form with the linked values from the originating relationship...

**Comment by singapi** [comment] 2020-07-10 16:22
It seems nobody was interested (sad).

**Comment by Nkrb** [comment] 2021-08-05 22:55
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Nkrb** 2021-08-05 22:55 UTC
Labels: assigned-to-author, client-api
