### ISSUE TITLE
Only works for Model Driven apps, completely unavailable for Canvas Apps

### ISSUE THREAD

**Issue by joenewstrom** [MicrosoftDocs/powerapps-docs#586] opened 2019-08-21 21:07 UTC
This documentation works for CRM =&gt; Dynamics 365 =&gt; Model Driven Apps, but using it for very simple PowerApps (Canvas Apps) appears to be impossible as the tables are not available nor are the multi-select attributes on the Activity Entities such as RequiredAttendees, OptionalAttendees, To, From, etc. Building a very basic Appointment viewing app where the end user may be one of multiple attendees and is not guaranteed to be the Appointment Owner is much harder than it needs to be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95859a47-574e-fbaa-3e35-8ca0b8467a1f
* Version Independent ID: 9086c00c-295f-e83c-9a14-aba9b805d295
* Content: [ActivityParty entity (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/activityparty-entity#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/activityparty-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/activityparty-entity.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by Tiago84** [comment] 2019-11-27 08:18
Any update on this? When will this be fixed?

**Comment by phecke** [comment] 2022-06-14 23:53
@joenewstrom 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-06-14 23:53 UTC
Labels: open-for-too-long
