### ISSUE TITLE
How long typically does the recertification process take?

### ISSUE THREAD

**Issue by ugreg** [MicrosoftDocs/powerapps-docs#618] opened 2019-09-03 22:24 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f273ba5e-67f5-c73c-5de0-b5423a56227e
* Version Independent ID: a67da8b4-9031-db4c-5868-ccbbaac55610
* Content: [Next steps: Submit your app on Partner Center (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/next-steps-submit-app-cloud-partner-portal)
* Content Source: [powerapps-docs/developer/common-data-service/next-steps-submit-app-cloud-partner-portal.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/next-steps-submit-app-cloud-partner-portal.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by phecke** [comment] 2022-07-02 00:48
@ugreg Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:48 UTC
Labels: open-for-too-long
