### ISSUE TITLE
Lack of Windows Support for Model-Driven Power Apps Should Be Noted Here

### ISSUE THREAD

**Issue by michaelbunney** [MicrosoftDocs/powerapps-docs#2947] opened 2022-01-01 06:15 UTC
[Another page](https://docs.microsoft.com/en-us/powerapps/mobile/run-powerapps-on-mobile) says that model-driven Power Apps cannot run on Windows (only on Apple and Android operating systems):  "If you're on a Windows device, you can only run canvas apps; model-driven apps aren't supported on Power Apps for Windows."

That's a major limitation—and an unexpected one, given how many organizations using the Power Platform are targeting users running Windows devices.  It seems like this should be called out prominently on this page (and/or other pages about model-driven apps).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2119255f-281e-11b0-54e1-921115e21a24
* Version Independent ID: 24314dee-2250-33b0-0e4d-66a4ca17f270
* Content: [Overview of building a model-driven app with Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/model-driven-app-overview)
* Content Source: [powerapps-docs/maker/model-driven-apps/model-driven-app-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/model-driven-app-overview.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **v-roryneary**

**Comment by Mattp123** [comment] 2022-01-19 22:33
@michaelbunney - The short answer is model-driven apps are supported and do run on all modern Windows operating systems.

The article you referenced in your issue is specific to Power Apps Mobile, which is a _mobile app_ that supports Android or iPhone modern devices. [Windows Phone was discontinued some time ago](https://support.microsoft.com/en-us/windows/windows-10-mobile-end-of-support-faq-8c2dd1cf-a571-00f0-0881-bb83926d05c5) so there isn't mobile app support for those devices.

For other Windows devices, including smaller screen devices such as some Surface models, know that the Unified Interface, which is the framework for model-driven apps, is responsive by design. You can experience the behavior by narrowing your browser window when running a model-driven app. 
![image](https://user-images.githubusercontent.com/21203819/150228892-3647126d-7acd-451b-8fe6-26dc6458c69b.png)

The result is very similar to what the mobile app provides. More information: [Usability for all](https://support.microsoft.com/en-us/windows/windows-10-mobile-end-of-support-faq-8c2dd1cf-a571-00f0-0881-bb83926d05c5)

Closing issue.

**Closed by Mattp123** 2022-01-19 22:33 UTC
Labels: assigned-to-author

**Comment by fowl2** [comment] 2022-01-19 23:57
Offline support only works in iOS and Android app though.
