### ISSUE TITLE
Incomplete response from the API

### ISSUE THREAD

**Issue by thuemmeryf** [MicrosoftDocs/powerapps-docs#766] opened 2019-11-05 20:02 UTC
In the example on this page and during my testing of this API message, the most useful field values are always NULL: duplicateruleid_value and duplicaterecordid_value.  duplicaterecordid_value is what should be used to retrieve the potential duplicate record from the system.  I believe this is a bug within the system as there doesn't appear to be any other way to retrieve information about the potential duplicate record within the system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b7bac13-7df2-3bc1-e5c0-0d2b05c787a6
* Version Independent ID: ea870af8-ee9f-e25c-7864-8ef94586f425
* Content: [Run duplicate detection (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/run-duplicate-detection#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/run-duplicate-detection.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/run-duplicate-detection.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by susikka** [comment] 2019-11-25 10:13
@thuemmeryf Thanks for creating this issue. We will investigate this and get back to you with updates.

**Comment by susikka** [comment] 2020-03-04 08:31
This seems like a product bug. Will be investigated by the product team.

**Comment by phecke** [comment] 2022-07-02 01:10
@thuemmeryf Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 01:10 UTC
Labels: open-for-too-long
