### ISSUE TITLE
Can you please document results from unknown colors and comparing colors ?

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/powerapps-docs#1093] opened 2020-03-03 20:41 UTC
in other words , what is the resulting value of 
ColorValue("foobar") ?

and why does comparing colors not work :
ColorValue("Red") = Color.Red
returns : False

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a00b4782-cc9f-e8ae-8db0-9319deca56a6
* Version Independent ID: 22077723-5f9f-cf88-34f6-9d23dc07caf7
* Content: [Color enumeration and ColorFade, ColorValue, and RGBA functions - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-colors)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-colors.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-colors.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by gregli-msft** [comment] 2020-03-28 17:47
Thanks for the question.  I'll give a partial answer now with more to come.

The ColorValue( "foobar" ) questions depends on error handling:

- If error handling is off, it returns Blank.  You can test this with IsBlank.
- If error handling is on, it returns Error.  You can test this with IsError.

We are close to enabling error handling as the default.  When enabled, this will show a popup toast that "foobar" was not found.  This popup can also be controlled with the IfError and OnError (coming sono) handler.  Each consumer of the color value will have to decide what to do with an error value, most will treat is as a blank and not use a color for that element.  As we prepare to roll out error handling, we will add to the docs what errors can be expected from the functions, including this case.

ColorValue( "red" ) not equaling Color.Red is a bug.  However, besides not being able to compare properly, both values will produce the same shade of red.   Internally colors with their alpha channel are packed into 32-bit quantities.  In one portion of the code, it is treating one of these as a signed quantity and sign extending vs. treating it as an unsigned quantity.  So there is a numerical difference, but not an actual difference when we pull the rgba quantities out to produce an actual color.  We agree that these should compare as the same and we are working on a fix.

**Comment by Nkrb** [comment] 2021-08-02 20:23
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Nkrb** 2021-08-02 20:23 UTC
Labels: assigned-to-author, in-progress, product-bug, waiting-on-internal-feedback
