### ISSUE TITLE
Cannot get the flow to run succesfully

### ISSUE THREAD

**Issue by Thonner** [MicrosoftDocs/powerapps-docs#32] opened 2018-08-15 12:38 UTC
Hi There! 
The App would be great for our corporation. But i cannot get the flow to work.
The flow fails in the last step where is should update the list entry such that the status is either "approved" or "open" depedning on the condition. 

Here is a screen shot from the fail: https://github.com/Thonner/PicturesForForums/blob/master/FlowFail.PNG
If anyone can help it would be appreciated

- Anthon  

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 379862e0-89e8-8e6b-b686-77d6836f0434
* Version Independent ID: 29fc7f25-b6b5-26d2-69f3-eada7fff64b3
* Content: [Install and configure the Expense Report sample for canvas apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/expense-report-install)
* Content Source: [powerapps-docs/maker/canvas-apps/expense-report-install.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/expense-report-install.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by caburk** [comment] 2018-08-20 18:12
@Thonner we've identified the root cause and we'll update the package download link with a new version. If you want an immediate work-around, you would need to create a new flow in your environment that uses the same configuration.

**Comment by AFTOwen** [comment] 2018-09-13 05:08
@Thonner Thanks for your feedback! I'm closing this issue, but please let us know if the problem persists.

cc: @caburk

**Comment by Gingermuppet** [comment] 2018-10-14 13:06
Hi Ann, Keith Whatling here, just installed the template and the flow gives the same error. My work around was to delete the two update item sharepoint actions and that sorted out the issue. I think the template uses old Actions.

**Comment by AFTOwen** [comment] 2018-10-14 15:09
Love the name, @Gingermuppet!
@caburk Any updates?

**Comment by stefanfilip** [comment] 2018-11-19 15:06
If anyone else installed templates exactly as instructed above and saw failures, check the flow and see what failed. I found a flow error on the final condition stage - pushing approved status back to sharepoint list - it mentions content type error.
The fix for this is to go back to your Expenses SharePoint list you created, go to list settings > advanced settings and select "yes" for Allow management of content types? This will ensure no errors in the imported JSON.

Sidenote: With flow and other new tools changing all the time will be interesting to see if MS can keep compatibility issues and bugs to a minimum! Powerapps is a great looking tool though.

**Comment by caburk** [comment] 2018-12-11 18:58
@mr-dang-msft - Can you help with this?

**Comment by morayf** [comment] 2019-02-14 08:01
I installed, and yes found an error in the fact that the flow and app were different in using Cost_xx0020_Center, however i also got the error at the last stage of the flow with "Bad Request"... I simply removed the settings in the last item - "ApproverName Claims"... this solved it for both approved and rejected.  haven't seen any issue with functionality removing this

**Comment by AFTOwen** [comment] 2019-02-22 16:27
@Thonner Looks like you have a few suggestions for addressing issues. If you continue to have problems with this app, please post to [the forum](https://powerusers.microsoft.com/t5/PowerApps-Community/ct-p/PowerApps1). Closing this issue.” 

cc: @mr-dang-msft.

**Closed by AFTOwen** 2019-02-22 16:27 UTC
Labels: 01canvas, 02product

**Comment by thegongben** [comment] 2019-06-27 20:40
I just downloaded the sample package today and followed the tutorials line by line, but I am still getting the badrequest flow error and could not run flow. So the problem still has not been fixed yet?
Thanks.
