### ISSUE TITLE
Handling of option set color attribute

### ISSUE THREAD

**Issue by MartMue** [MicrosoftDocs/powerapps-docs#2000] opened 2020-12-15 13:24 UTC
There is no documentation on how to handle the color attribute on option sets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87414a4-998b-7269-536f-b86aa256f47d
* Version Independent ID: 3ff8d533-40dd-a052-84b8-ae423df6dec3
* Content: [Create and update option sets using the Web API (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/create-update-optionsets)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/create-update-optionsets.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/create-update-optionsets.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment] 2020-12-15 17:34
**Color** is a property of the [OptionMetadata ComplexType](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/optionmetadata?view=dynamics-ce-odata-9) which also contains the **Value** and the **Label** properties. These properties aren't mentioned on this page either.

What is it you are trying to do? 
Are you writing code to define options in an optionset?

**Comment by JimDaly** [comment] 2022-09-16 23:52
“Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue."

**Closed by JimDaly** 2022-09-16 23:52 UTC
Labels: assigned-to-author
