### ISSUE TITLE
Virtual Entities Limitation - sorting/filtering lookup columns

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/powerapps-docs#2156] opened 2021-03-01 04:19 UTC
>Although you can add virtual entity columns as a lookup on a grid or other UI views, you cannot filter or sort based on this virtual entity lookup column.

This is not true - filtering and sorting works, although you must implement support in your virtual entity data provider plugin for the system created/logical attribute with the suffix "name" that has the AttributeOf property set to the logical name of the lookup attribute.

eg.
```csharp
private string MapAttributeToExternalName(string attributeLogicalName)
{
    var attribute = _metadata.Attributes.Single(x => x.LogicalName == attributeLogicalName);

    var retval = attribute.ExternalName;
    if (attribute.ExternalName == null)
    {
        if (attribute.AttributeOf == null)
            throw new Exception($"Attribute '{attributeLogicalName}' has no ExternalName and no AttributeOf");

        var parentAttribute = (LookupAttributeMetadata)_metadata.Attributes.Single(x => x.LogicalName == attribute.AttributeOf);

        var lookupEntity = _service.GetEntityMetadata(parentAttribute.Targets.Single());

        retval = parentAttribute.ExternalName + "/" + lookupEntity.Attributes.Single(x => x.IsPrimaryName == true).ExternalName;
    }

    var attributeMetadata = _metadata.Attributes.Single(a => a.LogicalName == attributeLogicalName);

    if (attributeMetadata.AttributeType == AttributeTypeCode.Lookup)
        retval = $"_{retval}_value";

    return retval;
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42ae2cb6-ce2a-21c7-cb81-b60e7b026753
* Version Independent ID: 5a3cb7c0-6881-1d96-0dc3-639324a4568c
* Content: [Get started with virtual entities (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/virtual-entities/get-started-ve)
* Content Source: [powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/data-platform/virtual-entities/get-started-ve.md)
* Service: **powerapps**
* GitHub Login: @Sunil-Garg
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment] 2022-05-24 23:46
@fowl2 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-05-24 23:46 UTC
Labels: assigned-to-author, open-for-too-long
