### ISSUE TITLE
Creating a new 'Help Page' - Setting Path

### ISSUE THREAD

**Issue by CoreySutton** [MicrosoftDocs/powerapps-docs#1392] opened 2020-05-14 00:09 UTC
Is there any available documentation to aid in creation of new Help Pages?

I am trying to create new Help Pages for the Opportunity entity. I understand how to populate 'Display Name', 'Content Type', 'Content' and 'Locale' fields, however I don't understand how to populate the 'Path' field.

Based on the Opportunity 'Help Page'  that came with the solution the path is:
`CDS/Apps/&lt;app_name&gt;/Entities/opportunity/Views/Default`

1. Can I construct a path that relates a Help Page to a specific system view?
2. Can I construct a path that relates a Help Page to a specific form?
3. What do I use to identify a form/view?

For example, if I wanted to relate a help page to a particular view could I do the following:
`CDS/Apps/&lt;app_name&gt;/Entities/opportunity/Views/&lt;view_guid&gt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca73ad14-c514-cbff-8be2-f9e36ebf395a
* Version Independent ID: 38f4187d-582a-551c-d65c-3374d4d74ce6
* Content: [Create custom help pages - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-custom-help-pages#feedback)
* Content Source: [powerapps-docs/maker/common-data-service/create-custom-help-pages.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-custom-help-pages.md)
* Service: **powerapps**
* GitHub Login: @matthewbolanos
* Microsoft Alias: **matp**

**Comment by wimcoor** [comment] 2020-06-16 02:41
Thanks for reaching out! 

By default, the Help Page records and all its fields will be completed through the custom help pane UI: [Author help pane content](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-custom-help-pages#to-author-help-pane-content). Through this UI, you won't need to worry about the _Path_ field and you also get a rich editor to create its content.

However, you  certainly can create those records directly too. 

**The _Path_ field follows the following pattern for Forms and Views:**  

`CDS/Apps/<AppName>/Entities/<EntityName>/<ComponentName>/Default`

where: 
- AppName: the unique name of the app. This value can be obtained from the properties pane in the model-driven app designer
- EntityName: The name of the entity. This value van be obtained from the settings on an entity in the entity designer,
- ComponentName: _Forms_ for help on a form and _Views_ for help on a view.

The preview release of custom help panes does not support a way to automatically define help for specific entity forms or views. So, all forms of the same entity link to the same help page, and all views of the same entity link to the same help page. Creating form or view specific help is definitely something we have on our roadmap. 

That being said, as a workaround, the preview release of custom help panes does support the creation of hyperlinks from one help page to another. The 2 (or more pages) would just need to have the same AppName, EntityName and ComponentName.  
There are a few use cases for this. It would for example allow you to define all the generic help content in the "Default" help page which is valid for all forms/views of a specific entity, and link to more detailed help pages for each of the separate forms. Of course the user would have to navigate manually. Linking to other help pages is also useful if you want to split up a large help page into multiple help pages. 
So, for a given entity the help page that is loaded for a form will have the _Path_:  
`CDS/Apps/<AppName>/Entities/<EntityName>/Forms/Default`
You can then manually create a help page with a _Path_ :  
`CDS/Apps/<AppName>/Entities/<EntityName>/Forms/DetailPage`, where "DetailPage" can be any name of your choice. You can even group them by using something like "ExtraHelp/DetailPage".
Finally, to create the link, you have to simply use that name in the hyperlink you define in the pphml for the default page"  
`<a href="Detailpage">More details here</a>` or `<a href="ExtraHelp/Detailpage">More details here</a>` if you named the 2nd page that way.

**The _Path_ field follows the following pattern for Dashboards:**  

`CDS/Apps/<AppName>/Dashboards/<DashboardGuid>`

where: 
- AppName: the unique name of the app. This value can be obtained from the properties pane in the model-driven app designer
- DashboardGuid: the GUID of the dashboard you are providing help on. When you navigate to the dashboard you'll see its GUID in the querystring next to the id parameter.

**Comment by wimcoor** [comment] 2020-06-16 02:46
Thanks Matt. I commented on the issue. Do I need to do something else or is that it?

Wim

**Comment by CoreySutton** [comment] 2020-06-16 03:05
@wimcoor Absolute legend! Exactly the information I was after. Thanks heaps, and really appreciate the response.

**Comment by bryansonofpatt** [comment] 2020-06-26 15:23
@wimcoor - we just implemented this in PowerApps and we were trying to combine Forms and Views content into one page. Thank you for clarifying and documenting the paths!

**Comment by AdrianSayasane** [comment] 2020-07-21 07:22
@wimcoor Is there any way to write generic content for all dashboards?

Something like 

 `CDS/Apps/<AppName>/Dashboards/Default`

**Comment by Mattp123** [comment] 2021-07-28 23:12
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2021-07-28 23:12 UTC
Labels: assigned-to-author, open-for-too-long, waiting-on-internal-feedback
