### ISSUE TITLE
Modification to live docs page fill-app-submission-form-appsource

### ISSUE THREAD

**Issue by dustindonahue** [MicrosoftDocs/powerapps-docs#503] opened 2019-07-08 23:05 UTC
Hi, 

Can you please modify the live docs.microsoft.com page with the changes attached? The Word doc attached has yellow highlights for the modification areas. 

https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/fill-app-submission-form-appsource.md

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/fill-app-submission-form-appsource

[fill-app-submission-form-appsource.docx](https://github.com/MicrosoftDocs/powerapps-docs/files/3370490/fill-app-submission-form-appsource.docx)

Thank you,
Dustin

**Comment by dustindonahue** [comment] 2019-07-24 20:51
Hello, can you provide an ETA on this edit please?

**Comment by susikka** [comment] 2019-07-25 07:26
@dustindonahue Thanks for creating this issue. We will review the doc you shared and make the required updates in the doc.

You can also submit doc updates by forking this repo, making changes in your forked repo and then, raising a pull request to merge your changes to the live topic. Please take a look at [Microsoft docs contributors guide](https://docs.microsoft.com/en-us/contribute/) for more info on this process.

**Comment by dustindonahue** [comment] 2019-07-25 23:37
Hi Susikka, thank you for the update and info. We'll take a look at the guide on the alternate process. We have to other submissions for the same area submitted on the same day. Can you also assist with those?

**Comment by phecke** [comment] 2022-07-02 00:04
@dustindonahue Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-07-02 00:04 UTC
Labels: open-for-too-long
