### ISSUE TITLE
Page information not correct

### ISSUE THREAD

**Issue by samwdp** [MicrosoftDocs/powerapps-docs#2264] opened 2021-04-09 18:04 UTC
I followed to the letter and HttpContext.GetTokenAsync("access_token") always returns null
AzureADDefaults.OpenIdScheme is being depricated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db187af-a897-e8df-f587-4b9763e0bf27
* Version Independent ID: b7446e9a-88eb-f6de-5d11-3f2e0489249a
* Content: [Quickstart: Blazor Server Web API sample (C#) (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/quick-start-blazor-server-app)
* Content Source: [powerapps-docs/developer/data-platform/webapi/quick-start-blazor-server-app.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/data-platform/webapi/quick-start-blazor-server-app.md)
* Service: **powerapps**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by JeremyLikness** [comment] 2021-04-30 19:00
@phecke and @samwdp this is older content, but I just started from scratch and followed the tutorial and was able to authenticate without issue. Are you seeing any errors at all?

**Comment by phecke** [comment] 2022-05-03 23:31
@samwdp 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-05-03 23:31 UTC
Labels: assigned-to-author
