### ISSUE TITLE
Info to Set, but not to Get.

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#3453] opened 2022-06-17 19:28 UTC
This page describes how to configure a form to allow for custom querystring parameters.

However, there does not appear to be any information on how to read the values of those parameters.

After some testing, I discovered that the relevant data is present in Xrm.Utility.getPageContext().input.data["My_Custom_Parameter"]

However, this is not mentioned in the getPageContext() documentation (https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-utility/getpagecontext).

Is Xrm.Utility.getPageContext().input.data the correct, supported way to access custom form parameters? 

If so, please update the documentation to explicitly state this.

If not, please create a new page explaining how to access the values of custom form parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ab1a46-e673-1783-7bc5-09725a878c4a
* Version Independent ID: 3e54ebd6-296b-815a-e502-cc9e19726013
* Content: [Configure a form to accept custom querystring parameters (model-driven apps) - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/configure-form-accept-custom-querystring-parameters)
* Content Source: [powerapps-docs/developer/model-driven-apps/configure-form-accept-custom-querystring-parameters.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/configure-form-accept-custom-querystring-parameters.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @HemantGaur
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment] 2022-06-17 21:00
Thanks for your comment, @devlinl. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment] 2022-06-17 21:29
@devlinl 
Thanks for your feedback.

@HemantGaur to confirm, but I believe this is by design.

The fact that `Xrm.Utility.getPageContext().input.data` is not documented means it is not supported.

The capability to set custom query string parameters is intended for the purpose mentioned in the doc:

> ...model-driven apps allows a specified set of query string parameters to be passed to a form. You use these parameters to set default values when you create a new record in the application. 

The values in the query string parameters should be available as the values of those columns in the form. 
I would expect them to be included within `formContext.data.entity`. Why not access them there?

How would accessing the data via `input.data` property add value?

**Comment by devlinl** [comment] 2022-06-17 22:42
You cut off the key part of the sentence you quoted... "By default..."

That same document continues:

In your applications, you may want to pass custom query string parameters to a form. This article provides information about how you can define a set of specific parameter names and data types that can be accepted for a specific form.

I'm not asking about the default query string parameters that are always available (the set of columns on the form). I'm asking about CUSTOM parameters that I define in the form editor, as this document explains how to do.

The data I'm passing in is not intended for a field value.

Liam Devlin
Application Architect
1 (949) 529-6952<tel:19495296952>
www.anthology.com<http://www.anthology.com/>
***@***.***<http://www.anthology.com/>

**Comment by JimDaly** [comment] 2022-06-17 22:56
@devlinl 
Thanks for clarifying.
Issue is that documentation doesn't describe how to access custom values that are not intended to set the value of a field in the form.
Request is for documentation and support for a way to access this data. Liam has found that the data is available using `Xrm.Utility.getPageContext().input.data`, but we have no documentation for that particular property in [Xrm.Utility.getPageContext()](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/xrm-utility/getpagecontext)

@HemantGaur 
Please review.

**Comment by HemantGaur** [comment] 2022-09-06 23:32
Currently the method to collect the URL parameters is not exposed (and hence supported). With the converged app and custom pages we expect a more mature PowerFx based model to be utilized for these use cases.

**Closed** 2022-09-07 00:22 UTC
Labels: assigned-to-author
