### ISSUE TITLE
Does it work on dashboard views?

### ISSUE THREAD

**Issue by umerjaved** [MicrosoftDocs/powerapps-docs#4236] opened 2023-03-28 13:06 UTC
[Enter feedback here]

Hi, can you please tell if this control will work on dashboard views?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 225f1305-7aea-3fdd-9a46-e0f258c670ff
* Version Independent ID: 225f1305-7aea-3fdd-9a46-e0f258c670ff
* Content: [Customized editable grid - Power Apps](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/sample-controls/customized-editable-grid-control)
* Content Source: [powerapps-docs/developer/component-framework/sample-controls/customized-editable-grid-control.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/component-framework/sample-controls/customized-editable-grid-control.md)
* Service: **powerapps**
* Sub-service: **pcf**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by JimDaly** [comment] 2023-03-28 15:21
@umerjaved 

Thanks for your feedback.

This is an article that describes a specific PCF dataset component sample.

So, if I'm understanding your question correctly: Are you asking if PCF dataset controls can be used on dashboard views?

As far as I know, based on the documentation we have today about dashboards, such as [Customize visualizations and dashboards](https://learn.microsoft.com/power-apps/developer/model-driven-apps/customize-visualizations-dashboards), this isn't the case. There would need to be a place to add and configure a control.

Can you elaborate on why you thought this might be possible? Am I missing something?

**Comment by umerjaved** [comment] 2023-03-29 08:38
Hi @JimDaly understood it describe a customisable PCF component for Dynamics 365 grid where the example shows the colour coding based upon some rules. However Dynamics 365 dashboard have a list component which uses the same grids hence my question would this PCF component also work within dashboard?

**Comment by JimDaly** [comment] 2023-03-29 16:05
@umerjaved 

I think you are referring to the component configuration experience documented here: [Set properties for a model-driven app chart or list included in a dashboard](https://learn.microsoft.com/en-us/power-apps/maker/model-driven-apps/set-properties-chart-list-included-dashboard).

Based on the screenshots in the docs (which might be out-of-date) and some manual testing it looks like these do not apply to dashboards. You would need to see the tab at the top of the properties that you have when configuring a control in a model-driven app form. I don't see those when editing a dashboard.  Are we looking at the same things?

So, I would say 'no'.

**Comment by JimDaly** [comment] 2023-08-17 21:24
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by JimDaly** 2023-08-17 21:24 UTC
Labels: assigned-to-author
