### ISSUE TITLE
Ensure the existing data satisfies the unique constraint before creating the key

### ISSUE THREAD

**Issue by pablolaurin** [MicrosoftDocs/powerapps-docs#870] opened 2019-12-15 17:21 UTC
If existing data has duplicated rows for the key, the customization tool allow to create the  key without any warning nor error message. However, the index creation fails and the unique constraint doesn't exist despite the UI showing the key object created.  You have to go to the system jobs to notice the problem. Duplicated data has to be removed and the key recreated to fix the problem. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50b4af08-9137-cd1f-3f0e-4e87dc8a2156
* Version Independent ID: 9579c6a4-f032-7ae9-0990-1aabeff6eb6c
* Content: [Work with alternate keys (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/define-alternate-keys-entity)
* Content Source: [powerapps-docs/developer/common-data-service/define-alternate-keys-entity.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/define-alternate-keys-entity.md)
* Service: **powerapps**
* GitHub Login: @mayadumesh
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-07-02 02:12
@pablolaurin Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2022-07-02 02:12 UTC
Labels: open-for-too-long
