### ISSUE TITLE
DateTimeValue changes timestamps to local time

### ISSUE THREAD

**Issue by ericthomas1** [MicrosoftDocs/powerapps-docs#2066] opened 2021-01-20 00:13 UTC
Might be beneficial to point out in these docs that DateTimeValue() wrapped around a timestamp in yyyy-mm-ddThh:mm:ssZ format will convert that timestamp to your local time. The term "locale" is used a lot in this doc, which is great for understanding date-time *formatting*, but doesn't address this specific piece.

**This can cause issues such as:** 

- If `rawTimestamp` = `2022-01-01T00:00:00Z`...

...wrapping it in DateTimeValue() will show the date time as `12/31/2021 4:00PM` if you are in Pacific Timezone (a completely different month and year)

![image](https://user-images.githubusercontent.com/42788729/105109064-92c2a980-5a70-11eb-9385-691e52cca173.png)

**The remedy is to use DateAdd() and TimeZoneOffset() like so:**
```
DateAdd(
    DateTimeValue(rawTimestamp),
    TimeZoneOffset(
        DateTimeValue(rawTimestamp)
    ), 
    Minutes
)
```
This *may* be mentioned in other docs, but some sort of link here would aid in understanding. 

Thank you

And thanks to RandyHaynes for [the explanation in the PA forums](https://powerusers.microsoft.com/t5/Building-Power-Apps/DateValue-and-TimezoneOffset/m-p/799112#M255201)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fda4c41-0a11-d2f5-8424-d79fa32c6103
* Version Independent ID: 5b21c7e2-cd5a-0d81-e9a3-97a65266aa17
* Content: [DateValue, TimeValue, and DateTimeValue functions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/functions/function-datevalue-timevalue)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-datevalue-timevalue.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/canvas-apps/functions/function-datevalue-timevalue.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by Nkrb** [comment] 2021-08-03 20:59
Thanks for contacting us. We have identified this as a product bug. We have created a work item for the respective dev team. Will update the docs when the issue is resolved. Closing the issue. If you need further help, please reopen the issue or open a new issue.

**Closed by Nkrb** 2021-08-03 20:59 UTC
Labels: assigned-to-author, product-bug
