### ISSUE TITLE
Different behavior between native client and Outlook.com thin client.

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#906] opened 2019-12-24 01:14 UTC
In the native dynamics web client, the data parameter can be decoded with a single call to decodeURIComponent. However, when openWebResource is called from the Outlook thin client in outlook.com, the data parameter appears to get encoded an additional time, resulting in the data string being incorrectly decoded on the other end, if not handled correctly.

The expected value "%3d%5b%7b%22" becomes "%253D%255B%257B%2522"

This discrepancy should be noted in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef001b56-f366-7866-693b-c403f84dbab3
* Version Independent ID: e3d1fbdc-84a5-ce3c-af1e-11e98b14418f
* Content: [openWebResource (Client API reference) in model-driven apps - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-navigation/openwebresource)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/model-driven-apps/clientapi/reference/Xrm-Navigation/openWebResource.md)
* Service: **powerapps**
* GitHub Login: @KumarVivek
* Microsoft Alias: **kvivek**

**Comment by JimDaly** [comment] 2022-12-14 20:20
@sriharibs-msft 
Assigning this to you.

**Comment by JimDaly** [comment] 2023-08-10 23:19
“Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue."

**Closed by JimDaly** 2023-08-10 23:19 UTC
Labels: assigned-to-author
