### ISSUE TITLE
Feedback on tools

### ISSUE THREAD

**Issue by smgtreker** [MicrosoftDocs/powerapps-docs#524] opened 2019-07-22 09:36 UTC
Can an email / link be provided to send feedback around the build tools; e.g. bugs / issues for investigation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a4bd57a-00f9-4e94-9273-d53094720f32
* Version Independent ID: e589dc8c-11a4-27dd-835d-f0ecff880d1b
* Content: [Build tools for Azure DevOps overview - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/build-tools-overview)
* Content Source: [powerapps-docs/developer/common-data-service/build-tools-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/build-tools-overview.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by thiagoleandro** [comment] 2019-09-26 19:02
I am having an issue on the export solution step "##[error]Access to the path 'd:\a\1\b' is denied." 

is this something caused by the tool?  (Note: when I try to do the same using the MSCRM component it works fine)

**Comment by patricgh** [comment] 2019-10-30 10:38
it is very good tool and all steps work fine me. Some errors which you see are for accessing git etc not form the tool

**Comment by chaithu312** [comment] 2019-11-26 07:31
Hi,

I installed PowerApps Tool Installer. I get the following error continuously.  Any help is really appreciated.



##[debug]System.Management.Automation.MethodInvocationException: Exception calling "ShouldContinue" with "2" argument(s): "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available." ---> System.Management.Automation.PSInvalidOperationException: Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.
##[debug]   at Microsoft.PowerShell.ConsoleHostUserInterface.HandleThrowOnReadAndPrompt()
##[debug]   at Microsoft.PowerShell.ConsoleHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
##[debug]   at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
##[debug]   at System.Management.Automation.MshCommandRuntime.InquireHelper(String inquireMessage, String inquireCaption, Boolean allowYesToAll, Boolean allowNoToAll, Boolean replaceNoWithHalt, Boolean hasSecurityImpact)
##[debug]   at System.Management.Automation.MshCommandRuntime.DoShouldContinue(String query, String caption, Boolean hasSecurityImpact, Boolean supportsToAllOptions, Boolean& yesToAll, Boolean& noToAll)
##[debug]   at System.Management.Automation.MshCommandRuntime.ShouldContinue(String query, String caption)
##[debug]   at System.Management.Automation.Cmdlet.ShouldContinue(String query, String caption)
##[debug]   at CallSite.Target(Closure , CallSite , PSScriptCmdlet , Object , Object )
##[debug]   --- End of inner exception stack trace ---
##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
**##[error]Exception calling "ShouldContinue" with "2" argument(s): "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available."**
##[debug]Processed: ##vso[task.logissue type=error]Exception calling "ShouldContinue" with "2" argument(s): "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available."

**Comment by patricgh** [comment] 2019-12-11 09:33
Did you fins the solution for that?

**Comment by KumarVivek** [comment] 2020-02-10 06:48
@smgtreker  To report issues and provide feedback about Power Apps Build Tools, please visit https://ideas.powerapps.com/.

cc: @mikkelsen2000 

Closing the issue.

**Closed by KumarVivek** 2020-02-10 06:48 UTC
Labels: assigned-to-author

**Comment by pedalocam** [comment] 2020-04-22 08:54
I am having a similar problem, getting this error message when using the PowerApps Tool Installer:
##[error]Exception calling "ShouldContinue" with "2" argument(s): "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available." 

Is there a way to force the step?

**Comment by JeroenDaniels** [comment] 2020-05-28 09:44
I have the same issue:
##[error]Exception calling "ShouldContinue" with "2" argument(s): "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available."

Is there a solution?

**Comment by thebiggfudge** [comment] 2020-06-11 21:48
I ran into the same issue. The resolution was to install/update PowerShellGet. You can install it by running the following PowerShell command, **Install-Module -Name PowerShellGet -Force**

**Comment by RodrigoGroener** [comment] 2020-07-23 08:28
Running **Install-Module -Name PowerShellGet -Force** did it for me. thank you @thebiggfudge
