### ISSUE TITLE
API limits and impersonation

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/powerapps-docs#2224] opened 2021-03-27 09:14 UTC
How is usage calculated during impersonation scenarios? If User A is connecting as User B, whose entitlement/service protection limits will be considered?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228fe864-af1c-34bb-c6d5-7507055ff26f
* Version Independent ID: a0b7352d-86a6-b85d-2c3a-93f93f6cd3ef
* Content: [API limits overview (Microsoft Dataverse) - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/api-limits-overview)
* Content Source: [powerapps-docs/maker/data-platform/api-limits-overview.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/data-platform/api-limits-overview.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment] 2021-03-27 17:53
This topic covers both entitlement and service protection limits.

I can speak to service protection limits, but those are covered in detail here: [Service protection API limits](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/api-limits)

For service protection limits there is currently some differences between the organization service and the web api. This is not by design. Eventually all the limits will be calculated the same way. We didn't call this out because it doesn't change the core guidance we provide for developers in handling service protection limits which is that their code must manage the re-triable error.

For entitlement limits, I'm looping in @cpdSeattle

**Comment by devlinl** [comment] 2021-03-27 20:39
Ok, while that's all great information, it doesn't really answer the question at hand.

I understand that there are differences between how the organization service and the web api currently count requests, and that eventually all the limits will be calculated the same way... but what way will that be?

You say you didn't call it out because it doesn't change the core guidance about handling service protection limits by managing the re-try errors. I fully understand that re-tries will still be received and need to be managed while impersonating. What is unclear is the potential scope of the impact of those re-tries...

Let's say for example, that I have two different processes connecting under a common service account, but they are each impersonating a different user. Will each process's throughput essentially be halved because they are connecting under a common account, and need to share requests, threads, and execution time? Or will each impersonated user's limits apply separately to each process?

Obviously, you could just have User A log into and run Process A, and have User B log into and run Process B, and avoid the whole impersonation question. It's just a matter of convenience to be able to achieve the same outcome using a service account and impersonation.

**Comment by JimDaly** [comment] 2021-03-28 01:02
Well, actually it looks like my information may be out of date. A year ago, the behavior was different per service.

The goal is that both services should apply limits according to the impersonated user. I can say that web api has been doing that. Not sure about the current behavior of the org service. It could be in alignment by now.

My main point is that looking for these kinds of optimizations may not pay off in the long run. The limits are there to protect the shared resources. If they aren't doing their job, we need to change them. If we detect patterns that are stressing the services, we will make changes, so this is why we are documenting the major themes. Additional tweaks will continue to be applied.

I hope this answers your question.

**Comment by AgileXRM** [comment] 2021-05-12 14:19
Hi Jim,
As of today (May-12-2021), we can confirm that the **org service is still not taking into account impersonated users' limits**. 
Limits are being applied to the service account (application user).

I do appreciate your point "_The limits are there to protect the shared resources._", however if I have 5000 paid User Subscriptions, I'd expect Microsoft to take care of balancing the load from these users between the resources (all be it that they are arriving via impersonation).

So, as long as no single user is abusing the limits (which are set by MS), the calls should all go through. 
We find ourselves in a situation where environments with higher User numbers are being penalized because the org service limitation system is not taking into account the user being impersonated.

Thanks

**Comment by AgileXRM** [comment] 2021-05-12 14:42
Just to add an interesting observation:
When we check the analytics in Power Platform Admin Center, it correctly reflects the API usage for the impersonated users!
So I'd say this is something that needs to be fixed in the limiter logic.

**Comment by JimDaly** [comment] 2023-08-10 23:35
I'm going to close this because the [Microsoft Dataverse API limits overview](https://learn.microsoft.com/en-us/power-apps/maker/data-platform/api-limits-overview) is an overview that compares the very different issues of **service protection limits** and **Power Platform Request (API Entitlement) limits.**. It isn't the authoritative article on either.

If you have feedback about these items, please open them on their respective pages:

- [Service protection API limits](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/api-limits?tabs=sdk)
- [Requests limits and allocations](https://learn.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)

**Closed by JimDaly** 2023-08-10 23:35 UTC
Labels: assigned-to-author
