### ISSUE TITLE
Empty page "Integration with Office 365"

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/powerapps-docs#1492] opened 2020-06-10 07:10 UTC
Hello,
I just came across this empty page:
[Integration with Office 365](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/online-integration-office-365)
[view Markdown on GitHub: Integration with Office 365](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/online-integration-office-365.md)

The header metadata `ms.date` is set to value 10/31/2018.

May add content or delete that page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdc027b4-38ef-c89e-c244-c15fd03aff9c
* Version Independent ID: 650756a9-32b7-3acd-7bc1-20b35dd61030
* Content: [Integration with Office 365 (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/online-integration-office-365)
* Content Source: [powerapps-docs/developer/common-data-service/online-integration-office-365.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/online-integration-office-365.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by Markus-Hanisch** [comment] 2021-10-30 06:17
@paulliew @tapanm-MSFT 
The Microsoft Docs page is still empty.

**Comment by phecke** [comment] 2021-11-02 01:15
@Markus-Hanisch 

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by phecke** 2021-11-02 01:15 UTC
Labels: assigned-to-author, open-for-too-long
