### ISSUE TITLE
Sort order when using multiple packages

### ISSUE THREAD

**Issue by halljames** [MicrosoftDocs/powerapps-docs#326] opened 2019-04-15 12:45 UTC
I am using the Package Deployer with multiple packages.  These, I want to be displayed in a certain order so that the user knows which order to install them in.  At the moment, the packages (of which there are 10) are shown in an unknown order.  It is the same order each time, but I do not know what the logic is that determines the order.  Is there a way to specify an order to show the packages, or perhaps a method to override the default viewing order.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b0e3a7-a385-942e-1261-53d1aeac1673
* Version Independent ID: 95ad8dd4-3458-8fb2-9e1f-8780fea5853a
* Content: [Create packages for the Package Deployer (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/package-deployer/create-packages-package-deployer#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/package-deployer/create-packages-package-deployer.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/package-deployer/create-packages-package-deployer.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by shmcarth** [comment] 2019-04-16 17:14
There is no interface to list the packages that they can install - you are providing your customers with a set of packages and you must give them instructions on any order that you need them to install them in.  If they are using a file browser - consider using a sequential number in the package name.

**Comment by halljames** [comment] 2019-04-16 17:24
I am using the User Interface for the Package Deployer, so it scans for the packages in the folder and the displays them on screen for the user to select. But, the order in which they are displayed seems random.

**Comment by phecke** [comment] 2021-06-17 00:58
@halljames

Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2021-06-17 00:58 UTC
Labels: open-for-too-long
