### ISSUE TITLE
'View Associated Records' button on charts

### ISSUE THREAD

**Issue by Niels-SL** [MicrosoftDocs/powerapps-docs#2713] opened 2021-09-10 07:49 UTC
Is there any documentation on how the new 'View Associated Records' button on charts is working? 

If you click the button on a chart that is on a dashboard, it works as has done until now. The specific view that is used in context of that particular chart will open (it has to be included in the app). E.g. the filters and the view columns that are relevant in that context are used. 

However, if you click on a chart that is on a form, you now need to make sure, that the relationship is added to that particular form via the classic solution explorer. Otherwise you will get an error like the one below. 

![image](https://user-images.githubusercontent.com/46558783/132812782-f59d4374-0bfa-4d55-8eb0-bfcb45331325.png)

1. The records will now be shown in the associated view - not the actual view, that is defined in context of chart on the form. E.g. it is not using the filter columns or the view columns that are specific to that chart when you click 'View Associated Records'. This is a big limitation that you have to use the same view for all charts. 

2. You now have to include the relationship in the navigation pane, which might not make sense if you already are showing opportunities in a sub-grid on another tab. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 033d52a6-1964-8f2b-02d4-a40c51eb6688
* Version Independent ID: 7695f505-20a5-b556-8a91-167c5ace076f
* Content: [Add model-driven app form navigation for related tables in Power Apps - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/add-edit-form-navigation-related-entities)
* Content Source: [powerapps-docs/maker/model-driven-apps/add-edit-form-navigation-related-entities.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/model-driven-apps/add-edit-form-navigation-related-entities.md)
* Service: **powerapps**
* Sub-service: **mda-maker**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment] 2023-01-12 16:24
@Niels-SL - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, reopen or create a new issue.

**Closed by Mattp123** 2023-01-12 16:24 UTC
Labels: assigned-to-author, waiting-on-internal-feedback
