### ISSUE TITLE
CanBeDeleted managed property is not included

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerapps-docs#507] opened 2019-07-09 22:51 UTC
Forms and Views have a CanBeDeleted managed property that isn't mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7afdabe8-29fe-15f6-5d77-fc3155175de9
* Version Independent ID: e67b084e-d344-066b-f8d5-598c033d637e
* Content: [Use managed properties (Common Data Service) - PowerApps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-managed-properties)
* Content Source: [powerapps-docs/developer/common-data-service/use-managed-properties.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/use-managed-properties.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **jdaly**

**Comment by phecke** [comment] 2022-07-02 00:07
@JimDaly Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Comment by JimDaly** [comment] 2022-07-02 00:22
@phecke 
See:
- [SystemForm.CanBeDeleted](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/systemform#BKMK_CanBeDeleted)
- [SavedQuery.CanBeDeleted](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/savedquery#BKMK_CanBeDeleted)

And add them to the list on this page.
Let me know if you have any questions

**Comment by phecke** [comment] 2022-07-15 18:53
@JimDaly Doc updated.

**Closed by phecke** 2022-07-15 18:53 UTC
Labels: doc-needs-updating
